### ISSUE TITLE
Waves Roulette resurrection

### ISSUE THREAD

**Issue by jaadasadet** [Waves-Association/grants-program#10]
- **Proposer:**
Joakim, S
- **Contacts:**
@JoSol
- **Github username:** 
jaadasaadet

## 👥  Team 

- Individual developer
- Startup
- Wheel of Pain

### Team members  (in case applying as a team or startup)

- Me

### Experience  

- Have systematically lost money gambling at casinos, online and on multiple blockchains (Including Waves, BTC, ETH, ICX and TRX)

## 🔍 Overview

- Waves-roulette.com was a failure. In my opinion this was because the game felt slow and didnt allow big enough bets. I want to aquire the domain and run a similar smart contract. It would be modified to be 1 block faster and allow higher limits.
- Obviously a superior solution that would be immensely more popular.
- Already integrated on Waves
- I want to gamble in a casino fashion on the waves blockchain
- Target audience would be degenerate gamblers that should be massing up around the Waves community with the current market conditions.
- Secret sauce is the faster gameplay made possible by having 1 block less delay between rounds
- Start up in 2 weeks
-Would require 10.000 Waves. I am willing to negotiate terms, funds provided could possible be returned in a given timeframe

### Ecosystem Fit

Some might consider dice and other dapps similar as they are not capable of comprehending the beauty of roulette.

## 🔩 Development Roadmap 
2020:
Preparation stage
2021:
Launch, 2 weeks after grant approval(Q1)
Roadmap(Q1/Q2)

### Overview

- **Total Estimated Duration:** Infinity
- **Total Costs:** 10.000 Waves

## Additional Information ➕

If rejected, please consider giving a new grant to MaDaMa so I can play roulette again

**Comment by KardanovIR** [comment]
Hey, Waves Association Grants & Funding working group reviewed your application and did not recommend your project to the Waves Association board.

Here are feedback and recommendations on what you can do before the working group will re-evaluate your application:

**Feedback:**

- The application is not by the Waves Roulette team and it is not clear who is behind the application
- The application claims that the new Waves Roulette will work faster than the older one, but there are no tech details
- 2 weeks durations looks like a meme :)

**Recommendations:**

- Add expenses breakdown
- Show the team tech skills and expertise to run such dApp
- Add tech details on how you’ll speed up the dApp

**Comment by jaadasadet** [comment]
Expenses breakdown:
All waves will be deposited to the Waves Roulette contract, I will cover other potential costs. 
If desirable, the deal can be evaluated after 1 year. Funds recieved may be returned to the Waves Association if the game is not living up to expectations. 


MaDaMa Labs, the original creators of Waves-Roulette are looking to sell the domain and code of the game
I am willing to spend my own funds to buy it and leech off their expertise

The old version of Waves Roulette gave players a 4 block delay between rounds to place bets . This can easily be altered to 3 blocks, increasing playability immensely.

2 weeks was kind of a meme. It should be possible to get it running within a week from grant approval
