### ISSUE TITLE
SIGN ART

### ISSUE THREAD

**Issue by christopheSeeka** [Waves-Association/grants-program#11]
- **Proposer:** Introduce yourself (name, surname) 
Christophe Verdot

- **Contacts:** Your email or telegram handle
@kriseekka

- **Github username:** Your Github login
christopheSeeka but i'm more active on private repos on bitbucket

## 👥  Team 

**- Are you applying to implement the grant as an individual developer or do you represent a team?**
I'm applying as a registered Web Developer, Director of Digital Chain Limited and sole developer of the project.

### Code Repos

Using private repo in bitbucket

![bitbucket](https://user-images.githubusercontent.com/50763365/101503846-82b5a580-39ad-11eb-9a81-ec64b0a0e814.jpg)

## 🔍 Overview

**Please describe your solution idea by the following structure:**

**- Short description of the solution you suggest**

Already on testnet, beta.sign-art.app, is the second product developed under Signature Chain. The first product, www.sign-web.app, was a tool to certify any file and document on the Waves Blockchain. 

SIGN Art expands on top of this feature to give Digital Artists a platform to create public and Blockchain Certified portfolio's as well as the option to tokenize their creation (NFT) and sell it on a primary and later on, a secondary market. 

SIGN Art Testnet demo: https://www.youtube.com/watch?v=aGGTqdwewfk

**- How does it solve the specified problem?**

Digital Art also known as CryptoArt is a heavily growing market giving artists a way to publish and sell digital artworks without fearing the risk of plagiarism with no way to prove ownership and paternity over their creation. Instead, by timestamping the hash of their creation sources before sharing it publicly, artists keep immutable proof at all times that they created and shared it first and can provide the sources matching the certified hash. 

On top of that, NFT's associated to these artworks ensure scarcity and immutability in the number of editions for each creation as well as a proof of ownership for the collectors with total transparency over every transaction. 

All data is stored in a decentralized manner, through blockchain data storage and IPFS in order to guarantee full transparency and permanency of this data at all times. 

**- How you will integrate this project into Waves / Gravity / Neutrino.**

The project is already in an advanced stage with a fully working product on testnet and a mainnet launch planned for mid January 2021.

The project requires the SIGN utility token on the artist's side for all actions requiring a fee but artists have the option to request payment for their creation in SIGN, WAVES and USDN from collectors, with an incentive if requested in SIGN token. SIGN Art will get a percentage on every sale. 

Artists can create accounts, add artworks, and set them for sale. Collectors can buy any Creation and receive the associated NFT. Both artists and collectors have their own public page to display creations and collections. 

NFT's are minted on buy only via the dApp. 

Collectors can transfer their NFT to anyone at any time. 

SIGN is also already used as a test token in SUSY implementation for cross chain transactions through Gravity Hub.

**- Why your team is interested in creating this project.**

When sign-web.app was created it was to solve a problem I faced while working on the creation of a Carbon Units Registry financed a popular bank, they asked about it but it finally wasn’t implemented on their side but I decided to build the tool for it as it was obvious it could solve several use cases. 

After the release of sign-web.app, I realized that we could extend this feature by giving it a more narrowed and specific use case focusing on Digital Art. Coming from an Art School background I instantly felt attracted by the idea of mixing the blockchain technology and the digital art to give artists a proper tool without most of the problems concurrents are actively facing.

**- What is the target audience of the final solution?**

Target audience are all digital creators, Digital Artists but also musicians or even traditional artists interested to jump into Art 3.0.

SIGN Art will start with exclusive rounds of artists, 10 artists every 10 days and 1 of them promoted each day on our social networks. The first batch is already selected and working on their art drop for the launch. 

In phase 2 the Artist application will be open to anyone. 

Final solution target Artists & collectors and grant will be heavily used to incentivise them to join.

**- What is the “secret sauce” of it?**

The secret sauce is the power and strength of the Waves blockchain and RIDE, this allows us to build a platform that solves most problems our concurrents are still unable to solve, the main one being the ridiculous GAS fee on Ethereum as well as the transaction speed. 
Another one is not forcing the use of a browser extension making it mobile friendly by default, among several other advantages. Also being a developer coming from an artistic background makes it easier to build the right tools, I build it as a future user myself and by doing that building the right one for all Digital Artists as well with the help of our SIGN Ambassadors. 
Collectors don’t need any account or registration to collect NFT's.

Our beta already has 30+ artists testing the platform and we're closely listening to their feedback to constantly improve.

**- What is the duration of the whole project?**

SIGN Art being already in an advanced development stage, the release of phase 1 (primary market) is set for mid January, the secondary market will follow end of Q1 or early Q2. The project is an ongoing project with no defined duration, constant evolution is planned and long-term adoption is expected.

**- Resources required to implement the grant task**

The main request is funding mostly to push adoption through heavy marketing, ads, contest and onboarding material for artists and collectors. A small part of it could also help support all expenses and the developer for the first few months until adoption and sustainability are reached. Also, a possible audit of the dApps before mainnet release could be a plus.

### Ecosystem Fit

**Are there any other projects similar to yours? If so, how is your project different?**

Yes there are, the market is growing exponentially and there are several well implemented platforms but most if not all in the top 5 are using Ethereum and by this suffer from GAS fees, which is the main complaint from artists and collectors that are waiting for a platform that will change this. 

This is where SIGN Art will be different, extremely low fees compared to others and amazingly fast transactions are key. SIGN Art also offers several extra features like attaching a license to an artwork or certifying the sources of a creation. 
These features are not available on any other platform.

## 🔩 Development Roadmap 

_This section should break out the development roadmap into a number of milestones. It helps to describe the functionality we should expect, plus how we can check that such functionality exists in the product. Whenever milestones are delivered, we refer to the roadmap to ensure that everything has been delivered as expected._

Phase 1 - Early Q1 2021: 

- The release of the main platform including: user accounts, artist's portfolio and the NFT primary market 
- Creation of onboarding material for Artists and Collectors (How to, Explainer video, Articles etc)
- Advertising and Marketing to push adoption
- Create incentives for users (Artists and Collectors) to join the platform through contests, rewardsetc

Phase 2 - Q1/Q2 2021: 

- Continue all marketing and onboarding actions
- Development of a GRPC cache updater (already in development) to cache all dApp data in a localPostgres DB
- Development of the API to interface sign-art.app to the local DB (Early version: https://apitest.sign-art.app/).
- Development of a complete secondary market dApp
- Alias management for artists/collectors for better URLs
- Implementation of an advanced Search engine/Filtering in sign-art.app

Priority after the Mainnet release will be to focus on adoption, for this SIGN Art is also open to any suggestions and/or close work with the Waves marketing team as well if needed.

### Overview

- **Total Estimated Duration:** Duration of the whole project
Ongoing project but with an estimate 6 to 8 months to reach full financial sustainability.

- **Total Costs:** Amount of Payment in Waves for the whole project. The total amount of funding needs to not more than 100k Waves.

10 000 Waves 

Considering the volatility of the market, around 10 000 Waves would allow to operate for around 8 months until the project becomes financially sustainable with a strong adoption/marketing actions and developer being able to work full time on the project. 

70% allocated for pushing adoption and marketing
30% to support development period.

## Additional Information ➕

Any additional information that you think is relevant to this application that hasn't already been included.

Current SIGN ecosystem:

SIGN WEB APP 
https://www.sign-web.app/ 
https://testnet.sign-web.app/ 
https://docs.sign-web.app/

SIGN ART 
https://beta.sign-art.app/ 
https://apitest.sign-art.app/ 
https://faucet.sign-art.app/ 

NODES 
https://node.sign-web.app/ 
https://testnode.sign-web.app/ 
Gravity node: 172.105.74.239

MORE INFOS
https://twitter.com/signArtApp  (Followers: 1800+, mostly artists)
https://t.me/SIGNArtApp (Followers: 250+, mostly artists)
https://twitter.com/SignatureChain
https://www.signature-chain.com/
https://medium.com/@signaturechain
https://medium.com/@crashartifacts

**Comment by KardanovIR** [comment]
Hey, Waves Association Grants & Funding working group reviewed your application and recommended your project to the Waves Association board.

The board will make the final decision, but the working group also provides the next feedback and recommendations.


**Feedback:**

- The team already built the signature-chain.com application on top of Waves Protocol and proved their skills
- The team was rewarded with a grant by Waves Labs before and they delivered all milestones
- All team members are well-known in the community and have a great reputation
- The digital arts industry is booming now and it looks like a perfect timing

**Recommendations:**

- Building a lead generation and conversion funnel will be the next required step from the marketing lead
- Add expenses breakdown

**Comment by christopheSeeka** [comment]
Thanks a lot for the feedback, here are more details regarding the upcoming lead generation plans as well as expenses breakdown

**PLAN FOR NEXT 9 MONTHS Q1 to Q3 2021**

_LEAD GENERATION AND FUNNEL:_

• Our primary audience is first focused on the already existing crypto artists and collectors as they understand the concept and are all eager to get alternative to the current ETH platform and their unsustainable fee. For this we will offer incentive to join as well as communicating over all the advantages of using SIGN Art over concurrent, starting from the fee but not limited to. Early registered artists will receive a commission free pass for 3 months. For this step, we already worked on reaching out since several months and have a good number of crypto artists following us and waiting for the release. We also have a selected batch of artists testing our platform, with the first 10 working on their launch drops. We plan to reach out to more artists through contests and incentive to join on SIGN Art. We are also working on different incentive actions for collectors.

• After that, targeting a wider audience of digital artists that are not yet into NFT/cryptoArt by reaching out to them through social media (twitter, Instagram, pinterest) and digital art platforms like deviantArt, behance, ArtStation  etc to offer them personal assistance and support to join and try the concept on our platform. This will be backed by all onboarding content we plan to create (explainer video, articles etc) and offering them similar incentive than in previous step. Offering a partnership to one of these platforms could be envisaged.

• Finally, reaching out to traditional artists and help them to do the jump into Digital Art and NFT. By working on this step, we will also learn from their feedback and this will be extremely helpful as ideally in the future, a bridge to sell digital and physical art linked to NFT could be implemented on the platform.

This coupled with different marketing, lead generations and incentive actions to attract artists and collectors.

_EXPENSES IN WAVES :_

• 3000 for the development allowing lead developer to focus on the project full time over next year and implement all listed features, manage all servers, technical support, study and define Q3 new features and future developments etc. 

• 1300 to reward current and potential upcoming ambassadors: SIGN is being developed by a single person, but the scope of the entire project and the targeted scale require help on different field. For this, a few selected SIGN Ambassadors have been and are doing a particularly good job since more than a year managing social media, reaching to artists, assisting online support, proof reading, working on case study and creating animation/articles. Being able to give them proper rewards until the project become sustainable to cover it would ensure the continuity of their support. 

• 1300 to hire extra working force: developing such a project alone have been a wonderful and exciting challenge but is also huge amount of work that required me to work near full time on it over the year of 2019. Adding a couple of working force is needed to move to the next level and ensure proper expansion, this would be used to hire a freelancer developer on per need basis and get the services of a marketing consultant for a year to assist in our marketing and lead generation plans.

• 5000 to 7500 set for marketing and adoption actions. With an already working product, the priority is adoption, lead generation and conversion of users. This amount will be used to incentive users to join, spread about the platform, work on SEO etc. Detail can be sent later. 
Marketing budget could be break down as follow:
Q1 3000/4000
Q2 1500/2000
Q3 500/1000

A marketing campaign can be as successful as the amount you are willing to put in it, this part is based on an estimation with a budget of 5000 to 7500 waves depending on what amount we receive. 

**TOTAL: 10 600 / 13 100 WAVES**

**Comment by christopheSeeka** [comment]
### **MARCH 2021 REPORT**

**Since the launch of the app on January 18 2021**
- We received 324 applications request from artists
- We added 141 artists and 100 created a profile
- 90 artists are still waiting to be added
- There were 653 artworks added to the platform
- 338 Sales
- 2 100 tx in last 30D as per dappRadar

**Artist’s sales volume from January 18 to march 15:**
- 1656 Waves
- 7 000 000 SIGN
- 710 USN

**SIGN Art received from commission and fee:**
- 165.671 Waves
- 1 074 066 SIGN 
- 71 USDN

To keep these number in perspective, we started with only 10 artists and only add limited number per week (between 10 to 25)

### **WHAT WAS DONE**
_Since we received the grant we built:_

- SIGN Art dedicated website: https://www.sign-art.app
- Application tracking for applicants: https://www.sign-art.app/users
- Telegram bot notifier: https://t.me/signartnotifier
- Added “Make an offer” option where anyone can offer price in WAVES SIGN USDN
- Several improvements for SEO, SSR, UI/UX
- Worked on the https://api.sign-art.app
- Developed a gRPC client to cache SIGN Art data in local postgres DB
- Met/Reached with several marketing agency.

**Comment by christopheSeeka** [comment]
### **APRIL 2021 REPORT**

**Since the launch of the app on January 18 2021**
- We received 650 applications request from artists
- We added 375 artists and 231 created a profile 
- There were 2 231 artworks added to the platform
- 1 204 Sales
- 5 300 tx in last 30D as per dappRadar (volume is hidden because it is calculated wrong by dappRadar)

![image](https://user-images.githubusercontent.com/50763365/116222064-cce2cc00-a780-11eb-84a1-eb8f2f977b98.png)

**Artist’s sales volume from January 18 to April 27:**
- Waves: 2834.72
- SIGN: 23 411 928
- USDN: 1 004 364

**SIGN Art received from commission and fee:** 
- Waves: 283.472 
- SIGN: 1 638 835
- USDN: 104 364

### **WHAT WAS DONE OR IS CURRENTLY IN PROGRESS** 
_Since the previous report of march 15 2021:_ 

- SIGN Art collector contest currently running with live results at: https://contest.sign-art.app for prize money of 5500$
- Telegram stickers contest currently running with prize money of 500$
- Hired an extra developer currently working on our own CRM to manage artists application requests
- Reworked the entire node infra to support the growing charge
- Reworking the cache updater 
- Hired an experienced COO to join the company
- Restructuring the company and working on materials to approach offline investors
- Starting the development of an accounting tool to help adjust to tax authorities requirements
- Optimized the webapp UI/UX and added several small features
- Secondary market in development on Testnet.

--------------------------------------------------------------------------------------------------------------------------------

**Q1 ESTIMATED KPI**
•	100 curated and verified artists on the platform. 
•	50 non curated artists
•	450 artworks
•	300 Collectors
•	900 NFT issued

**Q1 RESULTS**
•	72 curated and verified artists on the platform. 
•	159 non curated artists
•	2 232 artworks
•	N/A
•	1 205 NFT issued

During the process we decided to go a bit stricter on the “APPROVED” (curated) artists hence why we have less APPROVED but more REGULAR as initially planned. We could also have tripled these number by accepting any request but want to keep the focus on quality over quantity.

We are not able now to track the exact number of collectors as they don’t create any accounts and are often artists as well. Well build better tracking tool in future.
--------------------------------------------------------------------------------------------------------------------------------


**SIGN-ART.APP VISITS**
Current website visits stats show that the reach is global at the moment.

![image](https://user-images.githubusercontent.com/50763365/116222435-2fd46300-a781-11eb-8294-ccbd556d9871.png)

**Conclusion:**

The highest sale on a non ethereum platform took place on SIGN Art where a 1M$ sale took place.

The Web Application visits almost tripled this month, so we had to heavily scale up on the infrastructure, part of it, there is still some part to scale up soon.

The cache updater is an important tool and we are reworking it.

User base and sales are growing nicely, we plan to push it more with the release of the secondary market which is especially important to really reach the next level.

Hiring people and get the proper help was the focus of this month as it appear to be a necessary step prior to move forward consequently.

**Comment by christopheSeeka** [comment]
### SIGN ART REPORT - 07/07/2021 

--------------------------------------------------------------------------------------------------------------------------------

**Here a recap of Q2 milestones as proposed in December 2020:**

```
Milestone Q2:
Bid system, advance tags/filters/search engine and Secondary market
KPI:
• 300 selected and verified artists on the platform 
• 200 non curated artists
• 1500 Artworks
• 600 Collectors
• 2000 NFT issued
This is where we open up the platform more with curated and non curated artists with addition of the secondary market and more options built on top of the scalable architecture.
Here the results at the end of Q2:
```

**The following features were delivered:** 

- Bid system
- Advance tags/filters/search engine 
- Secondary market

**The following KPI were reached:**

- 290 Artist were accepted as we decided to adopt a 100% curated approach only.
- We received 800+ applications request from artists 
- There were 3662 artworks added to the platform 
- 2410 Sales (NFT issued)

**As of end of Q2, Major milestones have been met and all features delivered.**

--------------------------------------------------------------------------------------------------------------------------------

### WHAT WAS DONE IN DETAIL
**Since the previous report of april 27 2021:** 

- Secondary Market was released on Mainnet on July 5 2021 
 
![image](https://user-images.githubusercontent.com/50763365/124747958-1a37a280-df55-11eb-9880-f9bf78a18bec.png)

- Our Search and Filters feature that leverage on locally cached data was released on Mainnet on July 5 2021
 
![image](https://user-images.githubusercontent.com/50763365/124748104-494e1400-df55-11eb-8352-ba4c202b151e.png)

- Our custom-made CRM / Artists applications manager was release on July 7 2021
 
![image](https://user-images.githubusercontent.com/50763365/124748128-4eab5e80-df55-11eb-9607-54159d8a93da.png)

- We integrated with a 3rd party image processing service to optimize media loading

![image](https://user-images.githubusercontent.com/50763365/124748154-57039980-df55-11eb-93dd-cb33bec1e545.png)

- Aside of SIGN Art, Moore Cayman, Accountancy firm specialised in providing audit services to investment funds for around 200 hedge funds is now using SIGN to certify their clients’ financial audits. 

![image](https://user-images.githubusercontent.com/50763365/124748232-6b479680-df55-11eb-8df1-46d8d3ddf957.png)
https://finance.yahoo.com/finance/news/moore-cayman-launches-audit-verification-182000079.html 

- Our gRPC telegram bot was extended to stream new art drops on twitter as well

![image](https://user-images.githubusercontent.com/50763365/124748874-34be4b80-df56-11eb-9291-449a2013187a.png)

- Rewritten Caching App from dapp storage to local DB was rebuilt in Python and using block range approach, it was released mid-June 2021

- Our COO prepared all required materials to approach potential VC and equity investors and reached out to them

### WHAT IS NEXT FOR SIGN / SIGN Art

- Offer will be added on secondary market during summer.
- Collector’s profiles
- Timed Offer (primary and secondary market)
-  Direct swap from SIGN Art using Swop.fi dapps
- R&D to build a 3D/VR SIGN Art ThreeJS/WebGL gallery is in progress and we already have the dev resources needed, this will start once we receive the remaining part of the current Grant.
- We received several request to develop custom and white-label version of sign-web.app certification tool which is considered if we get more dev ressources.

**Conclusion:**

The drop of cryptocurrencies in may obviously had an important impact on every dapps and resulted in less activity around NFT in general as well but we remain fully confident that the NFT Art market is here to stay. It needs to mature more and such correction was needed.

Continuing to build during this time is the key to have one of the best platform in future when NFT will regain interest from a possible more educated and mature crowd of artists and collectors.

Several new features and improvement are needed and will be worked on during Q3

A 3D/VR gallery will be a good start to eventually bring SIGN Art and Waves into the fast growing metaverse world later.

More work is needed into growing community and onboarding users as it is still a challenge to attract users from chains with bigger community and already multiple crypto art platforms.

Our current focus is on developing everything listed in WHAT IS NEXT section which is still focused over SIGN Art but we plan to also push the certification feature more as interest for it started to grow significantly past couple of months. 

We may have to rewrite of the sign-web.app code base partially to offer a regularly requested white-label option of the certification tool.

**Comment by PascalParvex** [comment]
#During the process we decided to go a bit stricter on the “APPROVED” (curated) artists hence why we have less APPROVED but more REGULAR as initially planned. We could also have tripled these number by accepting any request but want to keep the focus on quality over quantity.

I have a question: Even though I seem to be the only one to offer unaltered still images directly out of camera, I got not approved. Does every NFT need an Photoshop overhaul?

**Comment by christopheSeeka** [comment]
> > During the process we decided to go a bit stricter on the “APPROVED” (curated) artists hence why we have less APPROVED but more REGULAR as initially planned. We could also have tripled these number by accepting any request but want to keep the focus on quality over quantity.
> 
> I have a question: Even though I seem to be the only one to offer unaltered still images directly out of camera, I did not get approved. Does every NFT need a Photoshop overhaul?

Hi Pascal, this is not the place for SIGN Art support, please reach out to the team by email, twitter, telegram or discord, thank you.

**Comment by christopheSeeka** [comment]
Hi Waves Association team,

SIGN Art team would like to request a grant extension to partially help us cover the listing of SIGN on Indacoin which would allow us to implement a direct SIGN <> FIAT buy option in both our products, sign-art.app and sign-web.app

Since our last grant milestones we completed quite some steps already on SIGN Art such as:

- Complete redesign of our website
- Redesign of the marketplace
- Release of our own custom 3D room: https://room.sign-art.app
- Release of integrated AMM for Waves, Sign, Usdn and ETH in SIGN Art (using swop dapps)
- Addition of a wallet feature supporting Waves, Sign, Usdn and ETH
- Addition of crosschain deposit/withdraw from/to the following networks ETH/ BSC/ POLYGON (using WX gateways)

(Read more: https://signaturechain.medium.com/sign-art-update-december-2021-be3c238d8ec3)

![image](https://user-images.githubusercontent.com/50763365/145932875-b2bdda24-762d-4c40-9b58-96807d1390a1.png)
![image](https://user-images.githubusercontent.com/50763365/145932888-a6df3149-58b7-4239-a45b-7a92b5cda718.png)
![image](https://user-images.githubusercontent.com/50763365/145932897-25f6770f-6117-4d2e-b6cd-1c5e14f64df5.png)
![image](https://user-images.githubusercontent.com/50763365/145932904-0e7cd0ec-8e61-4d6b-b63d-e2ccb18bf7d0.png)
![image](https://user-images.githubusercontent.com/50763365/145932944-6dfe57c4-7184-4d50-a42a-8398e8706f4a.png)

All this was implemented with the main focus to ease onboarding of new users, especially artists. 

In our hard work, with the help of our ambassador program, to onboard new artists, especially targeting those with no previous crypto experience, as we believe this is the real adoption key, we faced the well known difficulty to attract non crypto people, which is the initial crypto acquisition.
Sending them to buy in separate places then having to convert / transfer, sometimes several times is driving most non initiated users away.

The main missing element at this point to fully ease the onboarding process is to implement a direct credit/debit Card buy option for SIGN, within our apps.

For this we have been in discussion with Indacoin for a while and finally closed a competitive deal with them for which we would like to request a support of 20 000€ (22 550$). 

This would have a double positive effect as it would also allow to add this SIGN <> FIAT option on sign-web.app for which we recently released 2 white label version with certification feature to 2 certification resellers: 

https://rely.web-wallet.com/
https://cannatracking.web-wallet.com/

![image](https://user-images.githubusercontent.com/50763365/145932847-c9519cd2-3e83-4aff-be21-f8a04ef305bf.png)

SIGN Art is steadily growing his monthly number of active artists in an 100% organic way:

![image](https://user-images.githubusercontent.com/50763365/145932612-35146b8c-26a4-408b-a0d0-d100bf8cc37e.png)

![image](https://user-images.githubusercontent.com/50763365/145932756-a9311e93-6e97-46ca-b725-956750bce735.png)

We reached 440 curated artists last week on the platform.

**Comment by BlackTurtle123** [comment]
> Hi Waves Association team,
> 
> SIGN Art team would like to request a grant extension to partially help us cover the listing of SIGN on Indacoin which would allow us to implement a direct SIGN <> FIAT buy option in both our products, sign-art.app and sign-web.app
> 
> Since our last grant milestones we completed quite some steps already on SIGN Art such as:
> 
> * Complete redesign of our website
> * Redesign of the marketplace
> * Release of our own custom 3D room: https://room.sign-art.app
> * Release of integrated AMM for Waves, Sign, Usdn and ETH in SIGN Art (using swop dapps)
> * Addition of a wallet feature supporting Waves, Sign, Usdn and ETH
> * Addition of crosschain deposit/withdraw from/to the following networks ETH/ BSC/ POLYGON (using WX gateways)
> 
> (Read more: https://signaturechain.medium.com/sign-art-update-december-2021-be3c238d8ec3)
> 
> ![image](https://user-images.githubusercontent.com/50763365/146367147-98f94046-ff4c-4a4e-a3f1-465a8700e8a2.png) ![image](https://user-images.githubusercontent.com/50763365/145932875-b2bdda24-762d-4c40-9b58-96807d1390a1.png) ![image](https://user-images.githubusercontent.com/50763365/145932888-a6df3149-58b7-4239-a45b-7a92b5cda718.png) ![image](https://user-images.githubusercontent.com/50763365/145932897-25f6770f-6117-4d2e-b6cd-1c5e14f64df5.png) ![image](https://user-images.githubusercontent.com/50763365/145932904-0e7cd0ec-8e61-4d6b-b63d-e2ccb18bf7d0.png) ![image](https://user-images.githubusercontent.com/50763365/145932944-6dfe57c4-7184-4d50-a42a-8398e8706f4a.png)
> 
> All this was implemented with the main focus to ease onboarding of new users, especially artists.
> 
> In our hard work, with the help of our ambassador program, to onboard new artists, especially targeting those with no previous crypto experience, as we believe this is the real adoption key, we faced the well known difficulty to attract non crypto people, which is the initial crypto acquisition. Sending them to buy in separate places then having to convert / transfer, sometimes several times is driving most non initiated users away.
> 
> The main missing element at this point to fully ease the onboarding process is to implement a direct credit/debit Card buy option for SIGN, within our apps.
> 
> For this we have been in discussion with Indacoin for a while and finally closed a competitive deal with them for which we would like to request a support of 20 000€ (22 550$).
> 
> This would have a double positive effect as it would also allow to add this SIGN <> FIAT option on sign-web.app for which we recently released 2 white label version with certification feature to 2 certification resellers:
> 
> https://rely.web-wallet.com/ https://cannatracking.web-wallet.com/
> 
> ![image](https://user-images.githubusercontent.com/50763365/145932847-c9519cd2-3e83-4aff-be21-f8a04ef305bf.png)
> 
> SIGN Art is steadily growing his monthly number of active artists in an 100% organic way:
> 
> ![image](https://user-images.githubusercontent.com/50763365/146665632-56db88d2-2386-4cc5-a5dd-35dff527bf46.png)
> 
> ![image](https://user-images.githubusercontent.com/50763365/147350496-d2a32a93-4860-4a9f-b271-6900b336f03b.png)
> 
> We reached 440 curated artists last week on the platform.

Thanks for the status update!

We approved the grant in Funding and Grants.

Now one final approval need to be done by the board.

**Comment by BlackTurtle123** [comment]
Please provide us an address, the approval by the board is done.

**Comment by BlackTurtle123** [comment]
> Please provide us an address, the approval by the board is done.

We paid it:
https://wavesexplorer.com/tx/4ZxN6WzNVJejjU64rkk4Rmws3CYDCtcWjyiD67ELpBYi

**Comment by christopheSeeka** [comment]
Hello, we have been listed on indacoin.io since march:

https://twitter.com/SignatureChain/status/1509529455697403913?t=Cr7WHmeip76cwqR8OGooNQ&s=19

https://buy.sign.indacoin.io/

![Screenshot_20220629-002145_Chrome](https://user-images.githubusercontent.com/50763365/176230941-4d097682-f914-484f-b3bb-cb3800a441a0.jpg)

![Screenshot_20220629-002227_Chrome](https://user-images.githubusercontent.com/50763365/176230982-84a574fe-ee28-48f5-9891-8695969e7c7c.jpg)

This complete the use of funds from the last grant request.

**Comment by BlackTurtle123** [comment]
We are closing this since you completed all the work and was rewarded, so no outstanding stuff from both sides.
