### ISSUE TITLE
Gravity Protocol Grant Submission - [Track 2. Web3.0 Development Grant] 

### ISSUE THREAD

**Issue by sapranidi** [Waves-Association/grants-program#12]
- **Proposer:** Aleksei Pupyshev
- **Contacts:** 
aleksei@venlab.dev
https://t.me/alekseipu 
- **Github username:**
https://github.com/DeFi-Evangelist 
@DeFi-Evangelist

## 👥  Team 

- Are you applying to implement the grant as an individual developer or do you represent a team?
I represent a team
- Are you a startup or an ongoing business? (in case applying as a team or startup)
An ongoing business
- What’s your team or startup name? What is a website? (in case applying as a team or startup)
VentuaryLab
https://venlab.dev 

### Team members  (in case applying as a team or startup)

- Name of team leader
Aleksei Pupyshev
- Names of team members
Shamil Khalilov
Elshan Dzhafarov
Ilya Sapranidi
Regina Chernyavskaya
Pavel Simanov

### Team experience  (in case applying as a team or startup)

- Please describe your (team/startup) development experience and technological stack? 
Languages: GoLang, TS, Python. Ecosystems: Ethereum, Waves, Tron, Binance Smart Chain. Blockchain-specific tech: Tendermint, Solidity, Ride
- Do(es) you(r) (team/startup) have experience in using Waves technologies?
Yes
- Please attach your (team/startup) portfolio (projects you’ve been involved in) 
[Mastering Web 3.0](https://stepik.org/course/54415/promo#toc): a popular MOOC for developers of new decentralized technologies, built in collaboration with Waves DevRel department.
[Neutrino Protocol](http://neutrino.at): an algorithmic price-stable cryptocurrency protocol backed by a platform’s native token. Acquired by waves.exchange.
[Graviton](https://graviton.one/): A decentralised liquidity network for interchain digital assets

- Team website
https://venlab.dev 

### Team Code Repos
https://github.com/ventuary-lab 

## 🔍 Overview

Please describe your solution idea by the following structure:

- Short description of the solution you suggest
Gravity is an oracle and cross-chain communication network. It uses a blockchain-agnostic oracle system that supports communication of blockchains with the outside world, cross-chain communication, and sidechains within a single unified structure. 

- How does it solve the specified problem?
The expansive growth of cutting-edge technology in the blockchain industry outlines the need and opportunity for addressing oracle consensus in a manner both technologically and economically efficient as well as futureproof. Blockchain-agnosticism is inherently limited if proposing a technological solution involves adding one more architectural layer. As such, Gravity protocol is designed to be a truly blockchain-agnostic protocol. By ensuring parity through direct integration and by leveraging the stability and security of the respective interconnected ecosystems, Gravity circumvents the need for a dedicated, public blockchain and a native token. Ultimately, Gravity protocol intends to address scalability challenges by providing a solid infrastructure for the creation of gateways, cross-chain applications, and sidechains.
Typically in oracle systems, a common workflow pattern is used, which contains three global entities: 1. the external world with data sources, 2. the oracle system, and 3. the target blockchain where data should be safely recorded. The scheme of data provision workflow in the Gravity system is called pulsation. Data delivery started at a certain point in time (block or a block interval) should consistently end with the verification of the pulse transaction. If the verification fails for some reason, data delivery for the current time point is not performed.
The entire data provision service of the Gravity network provides all necessary checks within itself to be ultimately trustful to the final user, independent of their requirements. In addition, the user is not required to apply their own methods of data aggregation, as it can be executed automatically within the system, which can provide finalized and ready-to-use numbers or string values from a data feed to user applications (USER-SC).
The security verification of the transferred data is carried out within so-called NEBULA smart contracts deployed in target blockchains. A NEBULA-SC contains parameters and instructions for verification of signatures of the participating data providers, such as: public keys of active providers, threshold signature settings, the reputation threshold for node admission and the leader selection rule, where the leader is an node that collects all signatures and aggregated data from peers and sends them for verification to the NEBULA-SC contract.
The number of potential NEBULA-SC contracts in the Gravity network is unlimited. Each user or node operator can create a contract with custom properties by paying a fee in one of the tokens supported by the hostchain.

- How you will integrate this project into Waves / Gravity / Neutrino.
Gravity will provide support for wrapped USDN and NSBT in Ethereum, BSC, Tron, Polkadot, Cosmos, Fantom & Matic via the SuSy protocol built on top of it.

- Why your team is interested in creating this project.
Creating the unified decentralized oracle is a common global challenge for all of the public blockchain ecosystems to ensure their symbiosis and prosperity. 

- What is the target audience of the final solution?
Developers, blockchain ecosystems, node owners.

- What is the “secret sauce” of it?
The “secret sauce” is the Pulse algorithm - a two-step data delivery procedure that encompasses the core internal mechanics of Gravity as a data service, as well as the external parts of on-chain data verification and delivery within one of the supported target blockchains.

- What is the duration of the whole project?
1 year

- Resources required to implement the grant task
Node deployment and support, server & network infrastructure, marketing support.

### Ecosystem Fit

- Are there any other projects similar to yours? If so, how is your project different?
Although Gravity solves the same global challenge with interchain communication as other projects, the solution that we propose does not entail the creation of a new master blockchain with a new native token which other public blockchain networks are integrated with. The Gravity protocol is blockchain-agnostic in a sense that instead of creating a new tokenomics with a new token, the Gravity network works with the economies of the native tokens of public blockchains integrated into Gravity.
Similarly to the interchain problem, although Gravity solves the same global challenge with oracle data provision, the solution that we propose does not entail the creation of a new oracle network that delivers data provision services in return for a payment in a new token. Paying for Gravity oracles’ services is done in the native liquid tokens of public blockchains integrated with the Gravity network.
Unlike Chainlink oracles, the Gravity network can be viewed as a single self-governing decentralized oracle with free entry for new members, instead of a framework to create centralized oracles or a marketplace with a partnership of oracles without free entry.
Unlike Provable, the Gravity network is decentralized.
The Gravity protocol is a more low-level protocol vs. the protocols that provide token transfers, which means that it can give rise to different asset provision protocols on top of it (such as SuSy), thereby opening larger opportunities for fully automated and decentralized gateway solutions.

## 🔩 Development Roadmap 

This section should break out the development roadmap into a number of milestones. It helps to describe the functionality we should expect, plus how we can check that such functionality exists in the product. Whenever milestones are delivered, we refer to the roadmap to ensure that everything has been delivered as expected.

### Overview

- **Total Estimated Duration:** Duration of the whole project
1 year

- **Total Costs:** Amount of Payment in Waves for the whole project. The total amount of funding needs to not more than 100k Waves.
100k Waves

## Additional Information ➕

Any additional information that you think is relevant to this application that hasn't already been included.

Possible additional information to include:

Documentation: https://docs.gravity.tech 
SuSy alpha: https://susy.gravity.tech 
Explorer alpha: https://explorer.gravity.tech/nodes 
Research:
https://arxiv.org/ftp/arxiv/papers/2008/2008.13515.pdf 
https://arxiv.org/ftp/arxiv/papers/2007/2007.00966.pdf

**Comment by KardanovIR** [comment]
Hey, Waves Association Grants & Funding working group reviewed your application and recommended your project to the Waves Association board.

The board will make the final decision, but the working group also provides the next feedback and recommendations.


**Feedback:**

- One of the most promising projects in the Waves Ecosystem
- Venlab already built lots of projects (DAO, Neutrino, etc.) and proved their tech skills and expertise

**Recommendations:**

- Add expenses breakdown and milestones
- Sometimes it looks like Waves “core” Team is developing Gravity as well and it should be properly articulated that Venlab is a separate team

**Comment by BlackTurtle123** [comment]
Since no new updates, we consider this project to be dead.
If this is not the case, please let us know and post some updates.
