### ISSUE TITLE
Muna Wallet

### ISSUE THREAD

**Issue by gurulhc** [Waves-Association/grants-program#15]
- **Proposer:** Introduce yourself (name, surname)
Lucky Henry
- **Contacts:** Your email or telegram handle
https://t.me/chukwuka021
- **Github username:** Your Github login
gurulhc

## 👥  Team 

- Are you applying to implement the grant as an individual developer or do you represent a team?
I represent a team
- Are you a startup or an ongoing business? (in case applying as a team or startup)
Ongoing
- What’s your team or startup name? What is a website? (in case applying as a team or startup)
Muna Wallet Technology Ltd
https://muna.app
### Team members  (in case applying as a team or startup)

- Name of team leader
Lucky Henry
- Names of team members
Silas Ogar
Ebenezer Don
### Team experience  (in case applying as a team or startup)

- Please describe your (team/startup) development experience and technological stack?
Languages: JavaScript, Rust, Python, Dart. Blockchain Platform: Waves, Bitcoin, Ethereum. Blockchain Language: Ride
- Do(es) you(r) (team/startup) have experience in using Waves technologies?
Yes
- Please attach your (team/startup) portfolio (projects you’ve been involved in) 
[Auctionlance](https://beta.auctionlance.com): First freelancer marketplace built on Waves

[Bolingo dApp](https://bolingo.xyz/): A simple Waves dApp to tip active Waves community members

- Team website
https://qurulab.com

### Team Code Repos

- https://github.com/qurulab (Some developments are private)

## 🔍 Overview

Please describe your solution idea by the following structure:

- Short description of the solution you suggest
Muna is an African-focused mobile crypto app for sending, receiving and investing money easily and safely. Its a gateway to Defi offered by Waves and beyond.
- How does it solve the specified problem?
1. Through our partnership with a local bank, Muna will integrate fiat deposit options like bank transfer, USSD (Allows users deposit money without internet connection), ATM deposit into their Muna account which they can be used to buy Waves, USDN.
2. Users can also sell their Waves and USDN for fiat and are able to withdraw their funds directly to their local bank account. This brings convenience to Africans who are utilizing Waves and its related products like Waves Exchange.
3. Muna leverages on the power of USDN staking to already offer users daily interest on our app.
4. Muna will provide internal API integration that will integrate with Waves.exchange allowing African users starting with Nigerians on waves.exchange deposit and withdraw fiat.
5. Muna currently allows users to swap their Waves to USDN via Neutrino Smart contract within the app, easy ad quick.
- How you will integrate this project into Waves / Gravity / Neutrino.
Muna is already in an advanced stage with a fully working product on mainnet with 100+ testers already.
1. Muna app already generates Waves address for users during account creation. This address can send and receive Waves or any Waves based asset.
2. USDN staking is currently live on Muna with daily payout.
- Why your team is interested in creating this project.
Muna is an idea born out of passion and real demand from Muna team members and the Waves African community. By building this solution, it positions Waves for easy and quick penetration into the African market.
Also, Muna offers a real-life solution that solves problem Africans face like savings devaluation due to inflation, but keeping money in USDN even fixes this. Muna lets Africans earn interest that no bank in Africa currently offers. The solution will let Africans easily and quickly access Defi services offered by Waves.
- What is the target audience of the final solution?
Traders, developers, fund managers, cooperatives, freelancers, students and pensioners.
- What is the “secret sauce” of it?
The easy fiat deposit and withdrawal offered by our partner bank. Also is the developer friendliness of Waves, this brings flexibility and ease of integration during our developments.
- What is the duration of the whole project?
Muna is already in an advanced level of development, app is currently on Google play store open testing with 100+ testers.
The main release with fiat deposit and withdrawal will come early Q1 2020. With works done so far, the project is expected to gain reasonable sustainability and traction in 12 months, several features are planned with long-term vision.
- Resources required to implement the granted task
Received funding will be used to;
1. Create liquidity in the bank account to process withdrawals
2. Maintain liquidity in our Waves and USDN pools for buyers
3. Node, Server and Network infrastructure
4. Heavy marketing support
5. Support team expenses before we reach sustainability

### Ecosystem Fit

Are there any other projects similar to yours? If so, how is your project different?
Yes, there are, mostly built on Ethereum and other POS chains. For ethereum based, the GAS fee is always an issue making it very unattractive to Africans but this is different on Muna as it is built on Waves which fixes the issue of delayed transaction and huge network fees. Also for good platforms that offer staking, their APY is low and unsustainable, but this is different on Muna as our USDN staking yield relies on the core revenue generation on Waves and this makes it sustainable on the long run. Again, staking platforms don't offer the flexibility Muna does with USDN staking, these other platforms force users to lock their funds over a specified time but Muna changes this, it gives users ease of compounding their earnings. Another big thing we are doing differently on Muna compared to other project is user experience, Muna is simplified for non-crypto users to easily get on with.

## 🔩 Development Roadmap 

This section should break out the development roadmap into a number of milestones. It helps to describe the functionality we should expect, plus how we can check that such functionality exists in the product. Whenever milestones are delivered, we refer to the roadmap to ensure that everything has been delivered as expected.
### Features currently available on Muna mobile app
- User management (Sign up, login and reset password)
- Waves and USDN address creation
- Send and receive Waves, USDN
- Users can convert their Waves to USDN at a current market rate within the app
- USDN staking, unstaking and track earnings
- Pin lock (for wallet safety)

### Milestone 1 (16 weeks - $30,000)
Fiat onramp and offramp to <> from bank account solution is a unique selling point that will lets us readily bring Waves and USDN adoption to the African market. Presently, we succeeded to have a partnership with a local bank to enable us process fiat deposits and withdrawals.
- Fiat deposit and withdrawal to user's local bank account
- Buy USDN with Fiat
- Buy Waves with Fiat
- Push notification
- KYC for Muna fiat users
- Target of 5000 active users
- Target of $20,000 USDN purchase
- Support for more stable coins
- Username for Muna users with validity system

### Milestone 2 (16 weeks - $30,000)
- iOS version of Muna as it will bring another class of users to use our product.
- Internal fiat transfer between Muna users
- API integration on waves.exchange to allow Africans (starting with Nigerians) deposit and withdraw fiat from Waves exchange
- Double Q1 active userbase

### Milestone 3 (16 weeks - $60,000)
- Muna web version to enable users access their Muna service off their mobile devices
- Savings option (To allow users lock funds over a period of time)
- Token/coin swap within Muna
- DeFo integration (Allow users cross-swap stable coins within Muna)
- Minimum of Double active users from Milestone 1
- Paper rechargeable USDN recharge card option
- Multi-user savings with credit option
- Crypto-backed loans

### Infrastructure costs (Paid monthly)
- Database hosting
- Email API service
- Node set up
- SMS API service
- Server hosting
- Intercom customer support service

### Overview

- **Total Estimated Duration:** Duration of the whole project
12 months
- **Total Costs:** Amount of Payment in Waves for the whole project. The total amount of funding needs to not more than 100k Waves.
20K Waves
For the implementation of the milestones described above within the specified given time, we would need an equivalent of $120000. It‘s possible to split the grant according to the work size per milestones ($30,000 | $30,000 | $60,000
Rest of funds is reserved to cover our liquidity pools in bank and crypto wallet for purchases in NGN, USDN, Waves, stable coins based on Neutrino and Africans local currencies we support.

### Growing Muna Userbase
Presently, Africa largely already has a huge demand for crypto while several real-life applications and usage. Again, Africa has a huge volume on remittance from overseas as people send money for families. Some of our plans to gain traction are;
- Partnership with Cooperative societies
- Social marketing campaigns
- Referral system for users integrated into Muna app
- Savings bounties and competitions for crypto communities
- Partnership with payment processors that remit payment to Africa (starting with Nigeria)
- Student ambassadorship program
- USDN rechargeable top-up agents

## Additional Information ➕

Any additional information that you think is relevant to this application that hasn't already been included.

### Important Links:
1. [Muna on Google Playstore](https://play.google.com/store/apps/details?id=com.munawallet.muna)
2. [Muna on Apple store](https://apps.apple.com/us/app/muna-africa/id1560415690)
2. [Muna Mainnet Video Preview](https://youtu.be/pKHSmq66wuY)
3. [Project Website](https://muna.africa)
4. [Muna Telegram Community](https://t.me/munacommunity)

**Comment by KardanovIR** [comment]
Hey, Waves Association Grants & Funding working group reviewed your application and recommended your project to the Waves Association board.

The board will make the final decision, but the working group also provides the next feedback and recommendations.


**Feedback:**

- The team already built a couple of applications on top of Waves Protocol and proved their skills
- The team leader is well-known in the community and has a great reputation
- The African market is one of the most promising for FinTech and Muna Wallet can solve many problems of Africans

**Recommendations:**

- Add expenses breakdown and milestones
- It is not clear from the application how Muna Wallet will attract users

**Comment by gurulhc** [comment]
Hello, the application is now updated to provide;
- Expenses breakdown and milestones
- Muna Wallet strategy to attrack users

**Comment by gurulhc** [comment]
Muna Delivery Report January - August 2021

**Q1 2021 Milestone**

**Q1 Deliverables**
Fiat deposit and withdrawal to user's local bank account
Buy USDN with Fiat
Buy Waves with Fiat
Push notification
KYC for Muna fiat users
Target of 5000 active users
Target of $20,000 USDN purchase
Support for more stable coins
Username for Muna users with validity system

**Delivered**
- Muna UI/UX redesign
- Muna android app improvement and optimisations
- Migrated Muna back end to a scalable and more reliable server (AWS)
- Flutterwave integration to process deposit and withdrawals for users directly with bank accounts
- Support Waves and USDN


**Challenges**
Regulatory restrictions which blocked blockchain and crypto related projects from integrating with banks and make it impossible for us to let Muna users use direct bank <> Muna account deposits and withdrawals

**KPI**
800 active users
$12000 usdn purchase
$4000 total 

Due to regulatory restrictions in NIgeria, we paused the usage of bank deposit and withdrawal on Muna.
From our statistics, during Q1, most Muna users were mostly users who Muna to easily onramp and off ramp on waves.exchange and other exchanges where USDN is listed.

**Comment by BlackTurtle123** [comment]
> * Milestone 3 tasks

Hello! Thanks for the great update, you made some nice progress.

We had some questions, if we understand it right you are now requesting milestone 3 for an equivalent from 3k WAVES (80k dollar)?

**Comment by gurulhc** [comment]
Hello, thanks for your feedback. Below is some more clarification for the budget targeted on the referral.

**->> Budget for referral (user reward + liquidity provision to process orders): 2500 Waves**

For the referral campaign, our goal is to grow the Total locked assets on Muna (USDN, Waves, ETH and USDT) thereby growing the Waves ecosystem too. All saved/locked assets on Muna are fresh money from new users.

Our referral campaign is strictly for local Africans like Nigerians who pass our KYC verification and would be buying the USDN and other assets on Muna with fiat. 20k users need to buy USDN with fiat and we need liquidity for it.

Break down of Referral program:
- Cost to pay users for referring family and friends ($0.5 each)
- Cost (in USDN) to provide liquidity (e.g. USDN <> NGN trades) for USDN purchase on the app to reach the targets we estimated for this referral campaign.

_Also, in our last report, our budget skipped some important budget items that come with the Referral campaign that we accounted for:_
1. KYC to verify the user to help us stay compliant and eliminate fraud: $0.22/National ID verification (using appruve.co)
2. Programmable SMS to verify user phone numbers and successful fiat transactions: $0.0075/SMS (using twilio.com)
3. API to add and verify bank account details with existing user data: #50/call
4. Publicity and Marketing

Tried to make the budget a bit clearer and open now and I hope that helps. Let us know if you need any further clarification or details.

**Comment by BlackTurtle123** [comment]
> Hello, thanks for your feedback. Below is some more clarification for the budget targeted on the referral.
> 
> **->> Budget for referral (user reward + liquidity provision to process orders): 2500 Waves**
> 
> For the referral campaign, our goal is to grow the Total locked assets on Muna (USDN, Waves, ETH and USDT) thereby growing the Waves ecosystem too. All saved/locked assets on Muna are fresh money from new users.
> 
> Our referral campaign is strictly for local Africans like Nigerians who pass our KYC verification and would be buying the USDN and other assets on Muna with fiat. 20k users need to buy USDN with fiat and we need liquidity for it.
> 
> Break down of Referral program:
> 
> * Cost to pay users for referring family and friends ($0.5 each)
> * Cost (in USDN) to provide liquidity (e.g. USDN <> NGN trades) for USDN purchase on the app to reach the targets we estimated for this referral campaign.
> 
> _Also, in our last report, our budget skipped some important budget items that come with the Referral campaign that we accounted for:_
> 
> 1. KYC to verify the user to help us stay compliant and eliminate fraud: $0.22/National ID verification (using appruve.co)
> 2. Programmable SMS to verify user phone numbers and successful fiat transactions: $0.0075/SMS (using twilio.com)
> 3. API to add and verify bank account details with existing user data: NGN 50/call
> 4. Publicity and Marketing
> 
> I hope this helps. Let us know if you need any further clarification or details.
> 
> Also, do help me understand how you estimated 3k Waves = $80k, current price doesn't seem to equate that.

Hello, current waves price is depending on the day/moment around 26 dollar, sometimes more.
26 dollar * 3000 waves = 78000$


Thanks for the further explanation, we will discuss it in FG

**Comment by BlackTurtle123** [comment]
Hello, we approved it on both levels and are now requesting the funds to be paid 78k dollar.

**Comment by gurulhc** [comment]
Hello, that works.

Thanks for the update.

**Comment by BlackTurtle123** [comment]
> Please provide us an address

https://wavesexplorer.com/tx/AaoqQx8qiHRh5WRgpYDb8J8KdQrBUQc7sM99K7twLFYL paid

**Comment by gurulhc** [comment]
Hello Waves Association team,
Below is a report of Muna developments for Q1 2022.

RECAP of the last Muna Milestone 2 report:
We delivered

1. iOS device available on [apple store](https://apps.apple.com/us/app/muna-africa/id1560415690)
2. We added support for BTC, ETH, and USDT using waves.exchange gateways.
3. Bitcoin (wBTC) saving plans
4. Integrated swop.fi into Muna with the following swapping pairs;
5. BTC <> USDN
6. ETH <> USDN
7. BTC <> WAVES
8. WAVES <> USDN
9. Receipt feature: This enables money favorable for a few merchants and users who use Muna for payment, they can share receipts with recipients after making payments from the Muna app.
Improved UI and UX of Muna app to make it simpler for native users who are conversant with traditional banking apps.

KPIs
- 18,200+ Muna App installs (at At least 9100 actives in the last 7 days)
- $24,400+ USDN traded against Naira (NGN)
- 16,900 USDN Saved on Plans, expected to hit at least 50K USDN locked November 2021 (Currently, 60% on FIexible plan and 40% are on fixed plans)

** Something we introduced in the last report - #MUNA token
Recently, we launched a governance token called $MUNA, this is expected to serve as a community token for users to vote for assets and projects we intend to support. This lets us market and project USDN to customers and users outside the Waves ecosystem.

**What we promised to come next on Muna (Including Milestone 3 tasks)**

- Referral campaign (Users MUST hold at least 10 USDN to get a referral link)
**Milestone 3 tasks**
- USDT <> USDN swap pair
- List other stable coins like BUSD, cUSD and let users swap and buy them with USDN
- Vires.finance integration (Lending and borrowing BTC, USDT, ETH, and Waves)

**What was done for Milestone 3**
- Added USDN <> USDT swap
- Added USDN <> BNB swap via Puzzleswap.org
- Integrated vires.finance lending and borrowing
- Integrated swop.fi launchpad
- Listed SWOP, EGG, USDC, WX, PUZZLE, VIRES, NSBT, wBNB, RACE on the Muna app.
- Added multiple swap pairs: WAVES <> BTC, USDN <> SWOP, USDN <> WX, USDN <> NSBT.

_During the period, we focused on user retention and educating new users to get familiar with Muna._

**Some pending tasks till Milestone 3**
- Improved fiat deposit and withdrawal to user's local bank account (Milestone 1 task): This will be released 28th April 2022.

- Internal fiat transfer between Muna users(Milestone 1 task): This feature currently doesn't bring Muna and Waves ecosystem value since we are already implementing a better solution for all users.

- API integration on waves.exchange to allow Africans (starting with Nigerians) to deposit and withdraw fiat from Waves exchange (Milestone 2 task): Due to the current structure of waves.exchange, we will not be able to proceed with this feature. Rather, we would introduce a better fiat gateway to allow Nigerians and other Africans to deposit and withdraw fiat from Waves.exchange.

- Muna web version to enable users to access their Muna service off their mobile devices (Milestone 3 task): We decided to focus on building Muna on mobile.

- DeFo integration (Allow users to cross-swap stable coins within Muna) (Milestone 3 task): This will be live in Q2 2022.

- Paper rechargeable USDN recharge card option (Milestone 3 task): This feature is still under consideration but not a priority as we see it currently brings us very little value. Our goal was to use it for fiat onboarding but we have better solutions already.

- Multi-user savings with the credit option (Milestone 3 task): Vires.finance integration already offers more than 70% of the goal we intend to achieve. We won't proceed with this feature.

As Muna continues to develop, we continue to build and improve the app in the way that best drives usability, and brings value to the Waves ecosystem and the crypto industry generally. To further this course, we will complete all pending features and new ones in Q2 2022.

**Update list of pending tasks and release dates**
- Improved fiat deposit and withdrawal to user's local bank account: Starts 28/04/2022
- Referral: Starts 4/05/2022
- USDN crypto credit cards: Starts 6/05/2022
- DeFo integration
- Payment requests and Invoice
- P2P

**Q2 2022 KPIs**
- 1600+ Muna App installs
- 8600 USDN and 2700 USDT sold for Naira (NGN)
- 12,600 USDN Saved on Plans (till now)

On behalf of the Muna team, we are grateful for the help and support from Waves Association.

**Comment by gurulhc** [comment]
Hello, yes we will be sharing a report on June 30th.

**Comment by gurulhc** [comment]
Hello, yes we will be sharing a report on June 30th.

**Comment by gurulhc** [comment]
Hello @BlackTurtle123 

- We have integrated fiat deposits and withdrawals via bank transfer for Nigerian users.
- We created an agent system to process fiat deposits and withdrawals of users on Muna
- Users can now buy and sell USDN with Nigerian naira on Muna
- We added NGNT (Naira stablecoin pegged to Nigerian Naira)
- We added NGNT <> USDN trade pool

We are currently upgrading Muna infrastructure, and adjusting our current system to align with the new structure, once the upgrades and migration are complete (in 2 weeks), we will proceed to release pending features (all works are done and ready):
- Virtual crypto debit cards that support USDN
- Referral

We would be focusing on growth customer retention during Q3 2022.
Thanks.

**Comment by BlackTurtle123** [comment]
We are closing this since you completed all the work and was rewarded, so no outstanding stuff from both sides.

**Comment by gurulhc** [comment]
Thank you for the update @BlackTurtle123 

We are glad that Waves associstion confirms  we developed all they expected to see on Muna. We will continue to advance and improve Muna with features that continually brings good value to Waves platform.

Just to be clear, the 20,000 WAVES that was granted for Muna development wasn't all received.

Will the remaining WAVES balance be paid or we (Muna team) as open to ask for support when there is need?

Thank you.

**Comment by BlackTurtle123** [comment]
> Thank you for the update @BlackTurtle123
> 
> We are glad that Waves associstion confirms we developed all they expected to see on Muna. We will continue to advance and improve Muna with features that continually brings good value to Waves platform.
> 
> Just to be clear, the 20,000 WAVES that was granted for Muna development wasn't all received.
> 
> Will the remaining WAVES balance be paid or we (Muna team) as open to ask for support when there is need?
> 
> Thank you.

Hello!
You are open to ask for support whenever it would be needed and whenever there is good reason for it. Don't hesitate to recontact us for new support!
Goodluck
