### ISSUE TITLE
Wavescap.com - [Track 2. Web3.0 Development Grant] 

### ISSUE THREAD

**Issue by WavescapTorben** [Waves-Association/grants-program#17]
- **Proposer: Lennart Milatz for Wavescap.com
- **Contacts: @EinsZwo
- **Github username: Indie3k

## 👥  Team 
The team behind Wavescap.com was formed at the end of 2018. We then began to develop Wavescap.com as non-profit project. Wavescap.com was released to the public in April 2019 and the launch gained some nice traction. 

 
![image](https://user-images.githubusercontent.com/54720063/101920510-309e9b00-3bcc-11eb-870c-b45ba6e6d6bc.png)

**Torben Rottbrand** (Lead Developer)
Torben is our lead developer. He is programming for over 10 years and is experienced in Javascript and PHP as well as HTML and CSS. An example of his works, beside wavescap.com, is https://www.caravaning-info.de/.

**Ihsan Murat** (Team management, data management)
Ihsan is the initiator of Wavescap. He coordinates the team and maintains our databases (Token list and ICO database). 

**Lennart Milatz** (Communication, community management)
Lennart is responsible for all kind of communication regarding Wavescap. With his experience from being actively involved in the Waves Community for over 3 years he also is managing the community related aspects of Wavescap. 

Since the successful launch in 2019 we continuously added new features to expand Wavescap. Our latest big update was the release of the node overview. With the range of data we offer and the accuracy of it we established Wavescap as an important instance within the Waves Ecosystem.

## 🔍 Overview
Wavescap.com aims to be the central source of information for any person interested in one of the many facets around the Waves Ecosystem. Initially we started to provide an overview of assets issued on Waves. The main differntiator of Wavescap from other sources of Waves related data (e.g. pyWaves) is that Wavescap offers **curated** data. This means that in order to be visible on Wavescap a project needs to pass at least a basic standard of quality. 
To reach the goal of being an all-encompassing platform for data around the Waves Ecosystem it is necessary to constantly adapt new aproaches and developments of the ecosystem. The Waves Ecosystem is constantly growing and so is Wavescap. The grant will enable us to develop and provide a wide range of new quality tools for all people in the Waves Ecosystem. We identified various interesting sectors which we want to approach. 

1.	**Node related data** (6 Weeks – 4000$)
With the recent release of the Wavescap node overview we already have a decent standing when it comes to node related data. Still we see room to improve. One goal is to provide **detail pages** to each node, similar to the asset detail pages we already offer. We plan to implement more in-depth stats, some visualized, like the block generation history, the leasing addresses and their stakes as well as the voting history of the node, to name just a few. 
Furthermore we want to give owners of public nodes the chance of having impact on their node presence on Wavescap. We plan to give them an opportunity to **customize their appearance** to a certain degree, hopefully finding creative ways of attracting new leasers.

2.	**DeFi/DeFo Overview** (18 Weeks – 16.000$)
During the course of 2020 we saw a massive rise of DeFi and DeFo products on Waves. The launch of Neutrino marked the start of a really fast growth of new fintech applications built on Waves. At Wavescap we want to cope with this new development. We plan to build a universal overview for any kind of quality DeFi/DeFo tools. The overview will be organized in four different categories which are **Neutrino Staking** (All stakeable Neutrino currencies; Including metrics like the swap volume in the smart contracts), **Neutrino Pools**, **Leverage** (All kind of stats around the Waves.Exchange leverage product) and **NSBT** (Every important metric regarding NSBT will be added aswell). 
We also plan to include every single smart contract address in order to be able to provide the people of the Waves Ecosystem with a bunch of usefull informations at one place. This will not only increase the usability of the ecosystem itself, it also follows Wavescap‘s educational approach by raising awareness and curiosity about the underlaying technology of the financial products.

3.	**Gravity Data** (18 Weeks – 16.000$)
Another big new sector which emerged in 2020 is Gravity. It might be a bit early to talk about **Gravity Data** but we definitely want to participate in the new upcoming interoperability network. We will participate in both ways: By adding a **Gravity Node** to the spectrum of nodes operated by Wavescap and by expanding our product range to include all kind of Gravity related data. Since some people may insist that Gravity data might be too specific and technical to show on an end user oriented website like Wavescap, we think ist utterly important to do so. By transmitting Gravity related data to our users we also transport awareness about the technical possibilities developers have with Waves. We want to highlight again that for Wavescap the educational approach is always a key factor when it comes to presenting our data. 

4.	**dApp Overview** (18 Weeks – 16.000$)
We already approached the dApp sector on Waves as early as June 2019. Since then we were constantly building a database of Waves dApps. Since these database is without **usage statistics for dApps** for a while now we plan on changing that. But we not only want to provide stats, we also plan to provide an **unique interface for interacting with listed dApps**. This is not only a user oriented approach, we also do this for the sake of decentralization. As many people already know decentralization cant be achieved by using a single tool. Its more like a concept which needs to be implemented on many levels to succeed. We as Wavescap see it as really important to provide users with multiple different and independent interfaces to interact with different dApps. The access to dApps should not be centralized through a single interface and as member of the Waves Community we want to help to implement the fundamental concept of decentrality in the Waves Ecosystem by providing another – universally designed - way to interact with dApps and smart contracts. 

5.	**Block Explorer** (14 Weeks – 12.000$)
With the node overview we did our first steps in network related data. We want to expand in this direction by creating an own block explorer. The block explorer will follow a typical Wavescap design approach, combining user oriented presentation with a clear structure. It will come with a bunch of new and yet unseen features, for example an im- & exportable address book and a balance overview to name two examples. 

6.	**Wavescap internal optimization** (10 Weeks – 8.000$)
We have many great approaches to find and bind more users to Wavescap, but we also have a small list of internal optimizations which need to be implemented. First we need to invest a significant amount of time into our SEO because right now Wavescap struggles to find a good placement on various relevant keywords. Next to this we also want to bring Wavescap fully international by providing more languages. We planned to at least add Russian, Spanish, Chinese, Korean, German and French, but we will continuously expand the range of offered languages. 
The last internal point on the list is a professional design overhaul. We are quite happy with the structure and the general design of Wavesap, but we think there always is room to improve and since we lack the needed high end level UI/UX skills in our team we plan on using a part of the grant to acquire a professional UI/UX team to help us polishing and finetuning the UI of Wavescap.

We plan to implement these features over a course of 18 months. We have defined these 6 big sectors with a lot of time consuming sub-tasks. We are running Wavescap since almost two years now and can give a realistic estimation of the needed time. The key factor for us at Wavescap is time. We need to be able to spend time for developing and positioning Wavescap in the Ecosystem.
In the past we already worked successfully with support of the Waves team. We hope that our educational approach, our reliability in terms of delivering quality tools and finally the impact Wavescap has made on the Ecosystem are enough reason to extend the collaboration. A funding granted by a DAO would make us even more happy since it shows the rise of a truly decentralized environment and this was and still is a core goal of what we want to achieve with Wavescap. 

### Ecosystem Fit
We want to give a short presentation of the alternatives in the upcoming sectors we defined earlier and what the advantage of Wavescap looks like on concrete examples. 
1.	**Node related data** 
In terms of node related data the main alternative is dev.pywaves.org. It provides deep insight on a huge variety of stats. Our goal is to provide all the data pyWaves provides and complete it with non-blockchain but node related data such as social media presence, payout ratio and much more. With a bit smaller range of stats w8io.ru also offers a basic node overview, but both pyWaves and w8io are more developer oriented then end user oriented. Wavescap wants to fix that issue and prepare the data for a less technical audience.
Waves.Exchange follows a more user oriented approach to display node data but is too simplified to provide deep insides into the node network. It also lacks the educational approach Wavescap wants to implement in its node overview. 
2.	**DeFi/DeFo**
Again pyWaves, the Waves.Exchange client and various Telegram Bots are already active in this sector. Right now its necessary to use multiple tools to keep track of all the various DeFi/DeFo products in the ecosystem. Wavescap wants to change that by collecting all important stats in one place. After our first sketch we already identified more then 50 different metrics which we want to show.  
3.	**Gravity Data**
We want to become a pioneer regarding Gravity Data. Currently ist too early to identify similar services.
4.	**dApp Overview**
In terms of dApp overview we need to cope with dappocean.io. They are providing a high quality level of data regarding various dApps, but they are limited in the history of the data. We see a way to improve this by providing similar stats but in a more detailed way so people can take a deep research.
In terms of the dApp interface we only see the listed dApps itself and waves-dapp.com as alternatives. Since we want to expand the range of alternatives the user has, we welcome everyone joining us on our journey of developing new interfaces for decentralized applications.
5.	**Block explorer**
There are various block explorers out there. Wavesexplorer.com, w8io.ru and wavesdesk.com to name just a few. We dont see any major flaws there, the block explorer is more of a needed component on our way to a comprehensive data platform. We plan to use the block explorer as a way to bind users to Wavescap and generate traffic. 

Overall we think that Wavescap has established in a nice way within the Waves Ecosystem. The graph below shows that we were able to build a very steady userbase, averaging at 542 unique visitors every day since our launch. With a steady userbase of over 15.000 users every month the data shows that Wavescap has advanced to one of the Waves users favorite tools. 
 
![image](https://user-images.githubusercontent.com/54720063/101920786-82dfbc00-3bcc-11eb-88c6-47d1a5997350.png)

By providing a wide range of tools we aim to attract even more users to Wavescap. We think that Wavescap is a nice way of redistributing traffic over the ecosystem, simply by educating, causing curiosity and being a reliable source of information. 

## 🔩 Development Roadmap 
We already divided the work to be done into six big milestones and presented them above. Now we want to connect those with realistic ETAs.

 
![image](https://user-images.githubusercontent.com/54720063/101920821-8ecb7e00-3bcc-11eb-90df-de1c234f901f.png)

We want to highlight that the crypto industry is a fast changing industry. In order to be on the top you need to adapt fast and thats why we at Wavescap initially grouped the tasks by topics and not necessarily by date. The dates provided in the figure above are according to the current plan. Since we have identified the milestones and isolated chunks of tasks needed to realize the ideas we have the freedom to switch around certain task groups so we are able to adapt new developments quick and without screwing up already done work. 

### Overview

- **Total Estimated Duration:** We expect that the implementation of the milestones defined above will take approximately 18 months. So all milestones should be implemented by Summer of 2022.
- **Total Costs:** For the implementation of the 6 milestones described above in the given time we would need an equivalent of 72.000$. It‘s possible to split the grant into smaller pieces according to the work size of the milestones (4000$ / 16.000$ / 16.000$ / 16.000$ / 12.000$ / 8.000$).

**Comment by KardanovIR** [comment]
Hey, Waves Association Grants & Funding working group reviewed your application and recommended your project to the Waves Association board.

The board will make the final decision, but the working group also provides the next feedback and recommendations.

Feedback:

- Create a plan to have a unique node list order.
- Let gravity till we know more about it.
- Make a plan from unique features for the neutrino coins, especially with respect to what would be different compared to already existing tools.
- More detailed budget breakup to defend the amount of funds, EG costs, working hours, ... (Because maybe there are hidden costs we fail to see?)
- What is the future after the grants stop? Will wavescap keep exist? Or will they quit? What will be the business plan long-term?
- Please define KPIs for different new features that you create, e.g., how many monthly active users you will have per feature.

**Comment by WavescapTorben** [comment]
### Wavescap Update Q3 2021

**Milestones**
When we started to implement the milestones we realized that the order of our milestones was not perfectly efficient. We realized that if we start with the block explorer we will save a lot of work on the other milestones. This is the reason why we started straight with the block explorer.
Wscan.io – Block explorer for waves
On 30th September 2021 we released wscan.io, a block explorer created by us. There are already plenty of block explorers, but they all follow a very technical approach. With wscan.io we wanted to apply the Wavescap-Concept onto a block explorer. This means that we combine the data we extract from chain with off chain data to serve specifically investors of the Waves Eco System. Because we follow this hybrid approach on data preparation we are able to provide our users with new and unique features not seen on other block explorers before. These are some of the unique features we offer with wscan.io:

**1.  Portfolio Overview**
Almost 5 years ago we celebrated the launch of Waves. Since then Waves grew into a quite complex ecosystem with dozens of different DeFi-Products. Until the release of wscan.io there was not a single tool which provide you with an extensive overview of your portfolio. You had to combine different tracking tools or the DApps you used to check your total balance over every financial Waves product you might use. 
The beauty of blockchain allows us to extract all those data from the chain and provide you with all your funds connected to that address. With our portfolio overview you can now check any addresses and see even hard to track funds, such as staked NSBT and other neutrino assets, swop.fi pool share tokens, waves exchange LP products and much more. So even if your funds left your wallet and are now sitting in a DApp, wscan.io will include those funds in your balance overview. 

**2.  Address book**
Wscan.io comes with an address book feature. This allows you to label and safe any address you are interested in. The default address book comes with over 200 addresses from exchanges, gateways, nodes, DApps and smart contracts. This will make your research a lot easier and increases the readability of address histories a lot. 

**3.  Latest NFTs**
Since NFTs became one of the hottest topics in crypto over the past years we also see a growing importance of NFTs in the waves ecosystem. For this reason we also include a live feed of all recently created NFTs on Waves. This ways you can easily check for fresh minted NFTs or just follow the general activity on the chain.

**4.  Filter address history**
Another very important and unique feature is the possibility to filter any addresses history for specific variables. The idea for this feature is rooted in wavesbi.com, a tool which allows you to request very specific data from the waves blockchain. The problem with wavesbi was that it is very complex. We reduced the functionality a lot but made the remaining functions usable by just clicking on them. Now you can apply different filters to the address history, such as the transaction type, timeframes as well as in- or outgoing transactions. You can even combine some of the filters (for example filter only for outgoing DApp invocations).

**New DApp overview on Wavescap.com**
The next milestone we successfully achieved was the new DApp overview at wavescap.com/dapps. Our old overview was just a list with the basic information + social media links. Now we did a complete overhaul and implemented plenty of new stats. The DApp overview page is using the same filter system like the link database and wscan.io. 
You can filter for categories to decrease the number of shown DApps. On the general overview page you see all DApps sorted by 7D users. A quick overview shows the most important stats such as TVL, Volume past 7 days and users past 7 days. 
If you click on one tile you will enter the detail view which provides you with a number of interesting stats. First of all you see a chart which displays the development of the TVL and Volume. After a short description of the DApp you will find a list of related tokens. Those are issued by or related to the DApp. Only token listed on wavescap.com are considered in this list. After the related tokens list you are provided with a list of all smart contracts related to that DApp. It provides you with a name for the smart contract, the TVL (total TVL and each asset locked on this smart contract address) and volume. 
This really makes it easier for interested people to keep track of what is happening in the waves ecosystem and especially what tokens and addresses are related. It makes on chain research truly easier. 

**Outlook**
After achieving two of our biggest milestones we will take a look and add a bit more depth into both of those. Since Gravity is still under development and not too active we have to postpone the work on the Gravity Data for now. For the next time our focus will be on the implementation of more DeFi oriented features.

**Comment by BlackTurtle123** [comment]
> For the next time our focus will be on the implementation of more DeFi oriented features.

Hello, thanks for the update.

We would like to request you invest the funds received for Gravity Data into a new UI/UX which is more user friendly, because this would make wscan.io more worth it, and easier to adopt.
In return you can drop Gravity Data.
