### ISSUE TITLE
Zoomerok - platform for creators and advertisers

### ISSUE THREAD

**Issue by IgorShadurin** [Waves-Association/grants-program#22]
- **Proposer:** Introduce yourself (name, surname) 
Igor Shadurin
- **Contacts:** Your email or telegram handle
@IgorDvlpr
- **Github username:** Your Github login
IgorShadurin

## 👥  Team 

- Are you applying to implement the grant as an individual developer or do you represent a team?
I represent a team
- Are you a startup or an ongoing business? (in case applying as a team or startup)
Startup
- What’s your team or startup name? What is a website? (in case applying as a team or startup)
Zoomerok

### Team members  (in case applying as a team or startup)

- Name of team leader
Igor Shadurin
- Names of team members
Igor Chernishev
Margarita Shadurina

### Team experience  (in case applying as a team or startup)

- Please describe your (team/startup) development experience and technological stack?
Languages: Swift, JavaScript, React.js, ReactNative, PHP. Platforms: Waves, Ethereum, Nebulas, SWARM, Arweave. Blockchain-specific tech: Solidity, Ride
- Do(es) you(r) (team/startup) have experience in using Waves technologies?
Yes
- Please attach your (team/startup) portfolio (projects you’ve been involved in) 
https://github.com/GetLoginEth/login
https://github.com/GetLoginEth/like-chrome
https://github.com/GetLoginEth/like-dapp
https://github.com/IgorShadurin/waves-merchant
https://github.com/IgorShadurin/waves-identity
https://github.com/IgorShadurin/waves-auction
https://github.com/DappNinjaDev/spin-wheel
https://github.com/igar1991/memez-swarm
https://github.com/igar1991/slovo-miniapp
https://github.com/igar1991/Meme-Generator-Arweave
- Team website
https://github.com/VideoDApp

### Team Code Repos

- https://github.com/VideoDApp/video-editor-swift

## 🔍 Overview

Please describe your solution idea by the following structure:

- Short description of the solution you suggest

Zoomerok - is a platform that connects video content creators with advertisers. Blockchain allows advertisers to buy ads publishing commitments from content creators before creators are too popular

- How does it solve the specified problem?

The chicken and egg problem arises for content creators who find themselves at the beginning of the journey. Until the creator has become popular, he cannot fully support himself financially, immersed in creativity. Conversely, he cannot become popular because he cannot completely immerse himself in creativity.
Through the Zoomerok mobile app and web platform, we will allow content creators to show their creativity in creating video clips to a multitude of people. Anyone who believes in the future success of a content creator can buy a commitment to publish ads in their account, thereby helping to fund future content creation.

Example: a talented person appears on the platform who knows how to create original content. Content creation is quite expensive and he can afford to create no more than 1-2 videos per month. Advertising on such an account will cost $ 1 per publication.

Several platform users saw his videos and were delighted to the core. They were sure that in the future this person would become very popular and that advertising on his profile would cost at least $ 100. They bought a $ 10 publishing commitment from him for a total of $ 5800, which helped him fund content creation and become even more popular not in 2 years, but in 6 months. And then they sold these obligations to other users for $ 100 or more. Some of the new buyers will exchange commitments for advertising, someone will wait for the cost of an advertising publication of $ 1000.

We want to make a solution that will allow a user without experience with cryptocurrencies to start working with a decentralized world (no browser extensions, no keys and seed phrases at the start (optional)). Gradually increasing account protection as its value grows.

Platforms will receive a commission for a transaction with advertising obligations in the amount of 5-20%, which should cover the costs of maintaining and developing the platform.

All blockchain operations will be covered from user payments that they will make through in-app purchases in the mobile application.

- How you will integrate this project into Waves / Gravity / Neutrino.

Advertising commitments will be realized in the form of individual tokens issued on Waves. The content creator will be able to issue their own tokens and receive funding in the form of USDN. To fulfill the obligations, Waves smart contracts will be used that control the movement of tokens.
Token trading will be implemented using DEX.

- Why your team is interested in creating this project.

Our team sees a huge trend in platforms on which you can create short videos, but along with this trend, we see the problem of content monetization, which we know how to solve and our experience allows us to do it.

- What is the target audience of the final solution?

The target audience of our project can be divided into three categories:
1) Content creators who want to monetize their creativity
2) Early investors / agents who can see talented people and want to make money on it
3) Content consumers

- What is the “secret sauce” of it?

The secret sauce lies in the experience of creating viral mobile and web applications that can attract large numbers of users at a low cost.
For example, our team has attracted more than 3 million users in total to our projects on the following platforms: VK, Google Play, TikTok.

- What is the duration of the whole project?

1 year

- Resources required to implement the grant task

Server & network infrastructure

### Ecosystem Fit

Are there any other projects similar to yours? If so, how is your project different?
TikTok - Has a large user base of consumers and creators, but doesn't allow most creators to monetize their creativity.
Peepeth is a decentralized social network that allows you to fund creators of text content, but in which you need to have experience with cryptocurrency and understand how it works.

Our project will allow working with the blockchain without special knowledge, and monetization for content authors will be in the platform's dna.

## 🔩 Development Roadmap 

This section should break out the development roadmap into a number of milestones. It helps to describe the functionality we should expect, plus how we can check that such functionality exists in the product. Whenever milestones are delivered, we refer to the roadmap to ensure that everything has been delivered as expected.

### Milestone 1 (1 month, 10 000 USDN)
Implement features:
-Video recorder from camera for iOS app (storing video on device)
-User registration/authorization for iOS app
-User registration/authorization for website
-Issue users tokens for website

### Milestone 2 (2 months, 20 000 USDN)
-Attract at least 500 users for platform testing
Implement features:
-Uploading videos from app to servers
-Moderators portal for filtering inappropriate videos (according Apple policy)
-Video feed for exploring videos from new users / users which followed by consumer
-API for feed, video uploading
-API for issue, buy, sell tokens

### Milestone 3 (2 months, 20 000 USDN)
-Research popular at this moment video TikTok/Instagram effects
-Attract at least 1000 new consumers/creators
-Attract at least 100 potential agents (who will be interested in buying ads commitments in future)
Implement features:
-New popular video effects for attracting more consumers and creators
-Web portal prototype for agents

### Milestone 4 (2 months, 20 000 USDN)
Implement features:
-Smart contract for agents/creators (testnet)
-Full cycle tokens circulation with web portal for agents/creators (testnet)
-Tokens exchange

### Milestone 5 (2 months, 20 000 USDN)
-Test contracts and full cycle tokens circulation (mainnet)
-Test mobile application
-Fix bugs
-Implement viral web/mobile apps for future promotion
-Attract at least 100 creators and agents, 1000 consumers from apps, ads and direct mailing

### Milestone 6 (3 months, 30 000 USDN)
Release
Promote Zoomerok with  viral apps, advertise through Google Ads, Yandex Direct, VK Ads, TikTok Ads, crypto communities, thematic portals for content creators, mailing information about the project for crypto investors
Attract at least 2000 agents, 5000 creators, 50000 consumers
Profit!

### Overview

- **Total Estimated Duration:** Duration of the whole project
1 year
- **Total Costs:** Amount of Payment in Waves for the whole project. The total amount of funding needs to not more than 100k Waves.
120 000 USDN

## Additional Information ➕

Any additional information that you think is relevant to this application that hasn't already been included.

Possible additional information to include:

[Basic implementation of video editor for iOS](https://apps.apple.com/ru/app/zoomerok/id1537545883)

**Comment by BlackTurtle123** [comment]
Hey guys!
I got some questions:
- https://apps.apple.com/nz/app/zoomerok-warp-photo/id1537545883 is this related to this project?
- As competitiors, you say TikTok but it doesn't allow monetizing, what about OnlyFans, it's mainly used for nude/porn, but it is also used in less amounts for monetizing any kind of contect, don't you guys see this as very big competition? Why?

**Comment by IgorShadurin** [comment]
Hey, thank you for your comment.
1) Yes
2) At the moment, TikTok allows creators to monetize certain types of accounts in some regions. This happens in a completely non-transparent way, which raises many questions from the creators. Our team has relevant experience in attracting such an audience.
OnlyFans has no problems with funds distribution. It is clear and transparent. But this project has a different way of attracting users and a different audience.
Also, the target audience of TikTok, unlike OnlyFans, is much larger and more ethical in terms of morality. So this project is only partially a competitor.

**Comment by KardanovIR** [comment]
Waves Association Grants & Funding working group reviewed your application and unfortunately rejected it for now. You can re-apply by updating this issue as many times as needed.

The working group provided the next feedback to your project:

1. It is not clear how you gonna compete with products like TikTok for the audience. The chicken-egg problem requires some unique functionality with proved demand OR lots of money. 
2. It is hard to tell if this product is needed or not without traction numbers. Please implement an MVP and show some traction as Waves accounts and Waves transaction, The number of installs, How many videos were made, Retention rate
