### ISSUE TITLE
Integrate Waves blockchain in CCTip - [Track 2. Web3.0 Development Grant] 

### ISSUE THREAD

**Issue by Mancy619** [Waves-Association/grants-program#29]
- **Proposer:**
  Mancy
- **Contacts:**
  mancy@cctip.io
- **Github username:**
  Mancy619

<br>

# 👥 Team

The core members of CCTip Team are all from Internet companies such as Tencent. Having engaged in the blockchain for many years, they all have keen insights into the industry. CCTip has received investment from Bitmain.

CCTip is one of our ongoing blockchain projects. We have also developed [ABC Wallet](https://abcwallet.com/), a decentralized cross-platform wallet, and EOSPark, a blockchain explorer.

<br>

# 🔍 Overview 

## Short description

CCTip, a cryptocurrency community tool. Now it supports 8 public chains and 1000+ tokens including ERC20/TRC10/TRC20/SLP, and can be used on global social platforms like Twitter, Telegram, Discord, and Reddit.

We plan to integrate Waves and Wave tokens into CCTip. After the integration, users will be able to use Waves and Wave tokens on all SNS platforms (Twitter, Telegram, Discord, Reddit...) for various functions such as airdrop, tipping, rain, draw, newcomer rewards, conversion, and DAO group settings.

Bot on SNS:

- [Twitter](https://twitter.com/cctip_io)
- [Telegram](https://t.me/cctip_bot)
- [Discord](https://discord.com/invite/gEPamDz)
- [Reddit](https://www.reddit.com/user/cctip_io)

<br>

## How does it solve the specified problem?

Web1.0 led us to search for information in the world of the Internet, Web2.0 connected us, and Web3.0 will present us with a smarter Internet. As the golden key to the door of Web3.0, the blockchain needs to be widely known and applied. Yet how to achieve that goal has remained a major bottleneck. Blockchain project developers are also faced with more problems: how to expand the community size more effectively? How to activate community members in a short period? How to build a high-value community more intelligently? And how to build a more equitable community system?

CCTip can be an effective answer. Without the need to register or download CCTip, users can retweet, comment, and reply on the SNS platform (Twitter, Telegram, Discord, Reddit...) with CCTip in daily life, fully enjoying themselves even without knowing it. Their SNS platform account is their CCTip account.

CCTip boasts a full range of gameplay. The following is a brief description of the popular features. For more gameplay, see [here](https://doc.cctip.io/).

<br>

### Airdrop

Project developers can airdrop on the SNS platforms, not only for a cold start but also for the first seed users; they can also quickly expand the size of the community and attract new members to join; moreover, various events can be organized to establish a close tie with members.
![image](https://user-images.githubusercontent.com/77326850/104891234-a22bef00-59ab-11eb-9c10-18bb56e3d0fa.png)

**How to airdrop?**

Airdrop on the SNS platform only takes two steps. Take the airdrop of Waves on Twitter as an example:

- **Step 1-Deposit**: PM @cctip_io with "**deposit waves**". CCTip will reply to the deposit address you specified, and transfer to this address 100 Waves from your wallet. After confirmation on the chain, the deposit is completed;
- **Step 2-Airdrop**: Post a tweet with "**@cctip_io airdrop 10 Waves 100**", and an airdrop event will be released. The first 100 retweeters will equally share 10 Waves.

**How to receive an airdrop?**

Retweet. The first 100 retweeters will immediately get 10 Waves. 

**More airdrop gameplay**

- [Twitter](https://doc.cctip.io/guide/cctip-twitter/create-an-airdrop)
- [Telegram](https://doc.cctip.io/guide/cctip-telegram/create-an-airdrop)
- [Discord](https://doc.cctip.io/guide/cctip-discord/create-an-airdrop)

<br>

### Check the balance

**Method 1**: PM the bot to check. Just PM the CCTip bot **"balance"** or "**balance token_symbol**" on the very platform.

**Method 2:** Check in [My CCTip](my.cctip.io). CCTip provides a visual interface for operations such as checking balance, deposit, and withdrawal.

<br>

### Tip

To seek valuable content and development opinions, project developers can tip providers of quality content as rewards to push the community to move toward a good direction. At the same time, users can transfer without transaction fees in only 0.1s by replying with commands. Such an operation can cover small payments in everyday scenarios.

**How to tip?**

Airdrop on the SNS platforms only takes two steps. Take the example of tipping 100 Waves to @Tim on Twitter:

- **Step 1-deposit**. The method is the same as above.
- **Step 2-tip**: Post a tweet or write "**@cctip_io tip 100 Waves @Tim**" directly in the reply to a tweet, and @Tim will receive 100 Waves directly.

**How to get the tip reward?**

You need to do nothing. The tokens will be credited directly to the recipient's account. PM  [@cctip_io](https://twitter.com/cctip_io) with "balance waves" to check the balance.

**More Tipping gameplay**

- [Twitter](https://doc.cctip.io/guide/cctip-twitter/tip)
- [Telegram](https://doc.cctip.io/guide/cctip-telegram/create-an-airdrop)
- [Discord](https://doc.cctip.io/guide/cctip-discord/create-an-airdrop)
- [Reddit](https://doc.cctip.io/guide/cctip-discord/tip)

<br>

### My CCTip

[My CCTip](https://my.cctip.io/) , the web version of CCTip, brings together the functions of CCTip and displays them on the page. With an intuitive and clear interface, you can use CCTip more easily. You can log in to My CCTip directly with your SNS platform account.

![image](https://user-images.githubusercontent.com/77326850/104891110-7446aa80-59ab-11eb-963e-4b5ade343078.png)

<br>

### Exchange

CCTip supports **CCTip Convert** (the order-book transaction mode) and **CCTip Swap** (the AMM (automated market maker) mode).

- [CCTip Convert](https://my.cctip.io/token/exchange): You can either post a conversion advertisement, set the exchange rate, and wait for others for conversion; or you can search for the optimal exchange rate in the market for conversion.
- [CCTip Swap](https://my.cctip.io/token/swap): It supports fast, automated swap of tokens/coins, and is consistent with the automated market-making model XY=Z, making the whole process easier and saving the high gas fee on the chain. 
![image](https://user-images.githubusercontent.com/77326850/104891265-ac4ded80-59ab-11eb-8c16-93c705364860.png)
![image](https://user-images.githubusercontent.com/77326850/104891290-b40d9200-59ab-11eb-8edc-268e1524cd89.png)

<br>

### Newcomer Rewards

How to quickly attract new users to the community and have the user base proliferating? Try setting the newcomer rewards. By setting rewards for inviters and newcomers and passwords for claiming rewards, you can see the exponential growth in the number of community members within only one week. The passwords are set to screen zombie users out.

**How to set newcomer rewards** (For the temporary you can set the newcomer rewards in Telegram group and Discord server)

- **Step 1-Generate and copy group setting commands**: Enter information such as the amount of the newcomer rewards in [My CCTip](https://my.cctip.io/telegram/group/settings) to generate a command.
- **Step 2-Paste the command in the group**. The newcomer rewards are set immediately.

<br>

### DAO Group

The DAO group refers to a group, built on Telegram using CCTip, with a threshold of cryptocurrency holding. It is only open to users who hold a certain amount of certain tokens in the on-chain balance or in CCTip balance. Through the DAO group, the community can achieve decentralized governance, identify eligible users, build VIP user groups, and manage community members hierarchically.

**How to set DAO group?**

See [here](https://cctip.medium.com/build-your-dao-group-d45ee3134735).

<br>

## How you will integrate this project into Waves？

CCTip will support Waves and Wave tokens on all platforms as well as in all functions supported by CCTip, both at present and in the future.

<br>

## Why your team is interested in creating this project？

CCTip is committed to leading users from all over the world to enter the blockchain world by offering a smooth experience and a low threshold, as part of its plan to lead the world into the era of Web 3.0 as soon as possible.

<br>

## What is the target audience of the final solution?

The target users are all users on social platforms.

<br>

## What is the “secret sauce” of it?

- How general users enter the blockchain world:

  Get to know the basic knowledge of blockchain -> get to know blockchain products -> buy tokens by various means -> get into the world of blockchain

- How CCTip users enter the blockchain world:

  Obtain tokens -> use blockchain products (unconsciously learn blockchain knowledge during this process) -> successfully enter the blockchain world

The curiosity about the tokens they hold and the eagerness to make the tokens valuable will drive them to approach the blockchain world step by step.

<br>

## What is the duration of the whole project?

- Development duration: 4 months
- Operation duration: Unlimited

<br>

## Resources required to implement the grant task

Development, maintenance, marketing, and design.

<br>

# 🔩 Development Roadmap

**Goal: Integrate Waves and Waves token into CCTip, and ensure they are available and stable on all SNS platforms and in all functions supported by CCTip.**
<br>

## Milestone 1 ：Integrate Waves to CCTip (6 weeks $20,000)

Users will be able to use Waves for the following functions in CCTip:

- Tip
- Airdrop
- Lucky Draw
- Rain
- [CCTip Convert](https://my.cctip.io/token/exchange)
- [CCTip Swap](https://my.cctip.io/token/swap)
- [CCTip Ask](https://doc.cctip.io/cctip-ask)
- [CCTip Payment](https://hackmd.io/msku8MQNQlG_ddPJQA2mxQ)
- [Group Settings (Telegram)](https://my.cctip.io/telegram/group/settings)
- [Server Settings (Discord)](https://my.cctip.io/discord/group/settings)
- Deposit
- WIthdraw
- [My CCTip](https://my.cctip.io)
- [CCTip Box App](https://my.cctip.io/download)

<br>

## Milestone 2 ：Integrate Waves Tokens to CCTip (8 weeks $40,000)

Users will be able to use Waves Tokens for the following functions in CCTip:

- Tip
- Airdrop
- Lucky Draw
- Rain
- [CCTip Convert](https://my.cctip.io/token/exchange)
- [CCTip Swap](https://my.cctip.io/token/swap)
- [CCTip Ask](https://doc.cctip.io/cctip-ask)
- [CCTip Payment](https://hackmd.io/msku8MQNQlG_ddPJQA2mxQ)
- [Group Settings (Telegram)](https://my.cctip.io/telegram/group/settings)
- [Server Settings (Discord)](https://my.cctip.io/discord/group/settings)
- Deposit
- WIthdraw
- [My CCTip](https://my.cctip.io)
- [CCTip Box App](https://my.cctip.io/download)
- [Waves token Self Listing](https://my.cctip.io/token/listing)

<br>

### Infrastructure costs

- Database hosting
- Server hosting
- Email API service
- Node set up and maintenance
- Customer support service

<br>

## Overview

- **Total Estimated Duration:** 4 months

- **Total Costs:** 70k Waves (About $70,000)

<br>

# Additional Information ➕

<br>

### Important websites:

Website: https://cctip.io/

My CCTip: https://my.cctip.io/

Twitter: https://twitter.com/cctip_io

Telegram: https://t.me/cctip_bot

Telegram News Channel: https://t.me/cctipnews

Discord Server: https://discord.com/invite/3HtqFvx

Reddit: https://www.reddit.com/user/cctip_io

<br>

## Part of CCTip products:

CCTip Box App：https://my.cctip.io/download

CCTip Convert：https://my.cctip.io/token/exchange

CCTip Swap：https://my.cctip.io/token/swap

CCTip Event Point：https://my.cctip.io/activity

CCTip Ask：https://doc.cctip.io/cctip-ask

**Comment by BlackTurtle123** [comment]
Hello!
Do you guys have some usage metrics how much the bot is used?

**Comment by Mancy619** [comment]
> Hello!
> Do you guys have some usage metrics how much the bot is used?
> Also is the budget 70k $WAVES or 70k $

Thank you for your question. CCTip now has over 8 million users and 20,000+ groups using it. And the budget is 70k $

**Comment by KardanovIR** [comment]
Waves Association Grants & Funding working group reviewed your application and unfortunately rejected it for now. You can re-apply by updating this issue as many times as needed.

The working group provided the next feedback to your project:

1. Could you prove provided stats, because we see only 200 Reddit members in your subreddit. Twitter account is suspended.

**Comment by BlackTurtle123** [comment]
Closed/Denied due to inactive
