### ISSUE TITLE
Cypherock Wallet

### ISSUE THREAD

**Issue by rohanagarwal94** [Waves-Association/grants-program#30]
- **Proposer:** Introduce yourself (name, surname) 
 Rohan Agarwal
- **Contacts:** Your email or telegram handle
  rohan@cypherock.com
- **Github username:** Your Github login
  rohanagarwal94

## 👥  Team 

- Are you applying to implement the grant as an individual developer or do you represent a team?
  I represent a team
- Are you a startup or an ongoing business? (in case applying as a team or startup)
  We are a startup
- What’s your team or startup name? What is a website? (in case applying as a team or startup)
  Cypherock (Faucet Labs Private Limited)
  https://cypherock.com

### Team members  (in case applying as a team or startup)

- Name of team leader
  Rohan Agarwal
- Names of team members
  Suraj Tiwari
  Irshad Ansari
  Aditya Pandey
  Ujjwal Kumar
  Vipul Saini

### Team experience  (in case applying as a team or startup)

- Please describe your (team/startup) development experience and technological stack? 
  Languages: JavaScript, Embedded C, Python, Java. Blockchain Platform: Waves, Bitcoin, Ethereum

  Cypherock was founded in 2018 by Rohan Agarwal & Vipul Saini, who are currently the directors of the company. It currently 
  consists of 6 engineers both in the hardware & software development roles.

  Cypherock is currently backed by Consensys Labs. The founders and engineers have previously worked at/with companies like 
  FOSSASIA (Google Summer of Code), Blockgeeks, Apollo Munich, Nymble Labs, Lockheed Martin, GreyOrange, ARM to 
  name a few. The hardware currently is in private beta.

- Do(es) you(r) (team/startup) have experience in using Waves technologies?
  Yes! However we have not deployed any product on waves mainnet.

- Please attach your (team/startup) portfolio (projects you’ve been involved in)

1. Supporting Eth and ERC20 tokens on Cypherock wallet - https://www.youtube.com/watch?v=YPKGh3y8s7o
2. Seed phrase security without a single point of failure - https://www.youtube.com/watch?v=eD3CZMPumCk
3. Blockchain Address Manager Chrome Extension - https://chrome.google.com/webstore/detail/blockchain-public-address/faaggjfmapepjnccjbgafmeadcdgffnk?hl=en
4. Smart contract security for EOS blockchain - https://blockgeeks.com/guides/eos-smart-contract-security/

- Team website
  https://cypherock.com

### Team Code Repos

- https://github.com/Cypherock
- https://gitlab.com/cypherock-tech

(Most of the codebase is private till launch)

## 🔍 Overview

Please describe your solution idea by the following structure:

- Short description of the solution you suggest
  Cypherock is a new kind of Software + Hardware Hybrid solution that allows Cryptocurrency users to store, transact, backup, and inherit digital assets like Waves without a single point of failure. [Here](https://www.youtube.com/watch?v=YPKGh3y8s7o) & [Here](https://www.youtube.com/watch?v=eD3CZMPumCk) is the latest progress video.

- How does it solve the specified problem?

1. The wallet stands strong against any kind of physical attacks [as was recently demonstrated on Trezor by Kraken Labs.](https://blog.kraken.com/post/3662/kraken-identifies-critical-flaw-in-trezor-hardware-wallets/) The wallet generates 4 shares of your private keys each of which gets stored in a cyCard, of which only 2 cyCards are required for signing a transaction. So even if your wallet gets stolen, no one can access your funds.

2. Current hardware wallets secure the crypto but the unencrypted seed phrase on the paper becomes a single point of attack. If you don’t want to use it as a hardware wallet, it can be used to secure the seed phrases without a single point of failure. This device provides similar security as that of Multi-sig but for your seed phrase.

3. Current gen hardware wallets do not have any way to transfer funds to your loved ones without trusting an entity. Using the Cypherock X1 wallet enables the user to this without compromising with privacy and control of the assets. We are also coming up with an inheritance service very soon.

We believe Waves community will benefit tremendously from the support of Waves tokens on the hardware platform that will allow the community to securely backup, inherit & transact the USDN, NSBT, and other Waves tokens without the risk of loss & theft.

- How you will integrate this project into Waves / Gravity / Neutrino.

1. Just like the support for Bitcoin, Ethereum and ERC20 tokens, USDN and NSBT and other Waves tokens will be integrated into the cySync Desktop app and the X1 wallet. On initialisation of the wallet, it will generate Waves address for users during account creation. This address can send and receive Waves or any Waves based asset.
2. Staking will also be supported on the Desktop app of USDN.

- Why your team is interested in creating this project.
  We believe in order for Blockchains like Waves to go mainstream, it is very important that the risks around token loss and theft is solved. We believe in the future of open financial system and want to bring about the same peace of mind in holding your crypto like someone has around traditional finance. Also, digital asset inheritance is still an unsolved problem and it is critical for it to be solved so that the Crypto is securely passed from generations to generations.

- What is the target audience of the final solution?
  Traders, Crypto investors, Fund managers

- What is the “secret sauce” of it?
  Using tamper proof hardware and Cryptographic threshold schemes has made this possible. The unique architecture allows us to never store the complete private key in a single place permanently which protects it from loss & theft.

- What is the duration of the whole project?
  Cypherock has started with the private beta of the product. The final launch of the product is expected in Q2 2021. With works done so far, the project is expected to gain reasonable sustainability and traction in 8 months, several features are planned with long-term vision.

- Resources required to implement the grant task
  Received funds will be used to build the following -
1. Develop the React library for constructing a transaction for Waves, USDN, NSBT and other Waves tokens.
2. Create a one-click deployment with NodeJS and AWS for the node infrastructure.
3. Transaction signing library in C for the token with the Embedded Hardware support.
4. Support for Backup & Inheritance of the token.

### Ecosystem Fit

Are there any other projects similar to yours? If so, how is your project different?
There is currently no project that is providing transaction, hodling, recovery and inheritance features to the investors. There are hardware wallets doing some of it but they face single point of failure because they store the private keys in a single place which becomes hackable. There is a software base solution called Vault12 but people dont trust it because you have to input your private keys on an internet connected device. There are software wallets that provide support for USDN and NSBT and other Waves tokens but transaction and staking through a hardware wallet is not provided by any hardware wallet currently.

## 🔩 Development Roadmap 

This section should break out the development roadmap into a number of milestones. It helps to describe the functionality we should expect, plus how we can check that such functionality exists in the product. Whenever milestones are delivered, we refer to the roadmap to ensure that everything has been delivered as expected.

### Features currently available on Cypherock wallet

- BTC, BTC forks, ETH, ERC20 tokens support on the OS agnostic desktop app
- Securing seed phrase without a single point of failure
- Transaction of Crypto without a single point of failure
- Pin lock (for wallet safety)

### Milestone 1 (8 weeks - $30,000)
We have completed the final prototype of the hardware. Supporting USDN, NSBT and other Waves tokens on the cySync app, Cypherock X1 wallet and the cyCards will not be a problem.

- Develop the React library for constructing a transaction for USDN, NSBT and other Waves tokens.
- Create a one-click deployment with NodeJS and AWS for the node infrastructure.

### Milestone 2 (8 weeks - $30,000)

- Transaction signing library in C for the token with the Embedded Hardware support.
- Reach a count of 1000 units of hardware sold.

### Milestone 3 (8 weeks - $30,000)

- Porting X1 wallet features into Android & IOS SDK. Because the cyCards are NFC based cards, existing Waves software wallets like Muna.app can integrate cyCards to backup seed phrases without a single point of failure. Prototype - https://www.youtube.com/watch?v=k0MuyWUi2PY
- Support for Backup & Inheritance of the token.

### Milestone 4 (8 weeks - $30,000)

- Add support for Exchange and Staking
- Double Q1 active userbase

### Infrastructure costs (Paid monthly)

- Database hosting
- Email API service
- Node set up
- Server hosting
- Customer support service
- Hardware inventory

### Overview

- **Total Estimated Duration:** Duration of the whole project
- 8 months

- **Total Costs:** Amount of Payment in Waves for the whole project. The total amount of funding needs to not more than 100k Waves.
- 20K Waves
For the implementation of the milestones described above within the specified given time, we would need an equivalent of $120000. It‘s possible to split the grant according to the work size per milestones.

### How do we intend to grow Cypherock customer base?

- Targeting Blockchain & personal finance education courses for partnership
- Social media marketing around being the safest wallet available due to our unique architecture
- Marketing the product through Crypto Influencers
- Engagement in Crypto communities about the product - Reddit/Twitter
- Developing growth tools like https://quiz.cypherock.com
- Partner with Distributors/Resellers of Existing Hardware Wallets & Metal Backups
- Partner with Exchanges/OTC desks/Custodians

## Additional Information ➕

Any additional information that you think is relevant to this application that hasn't already been included.

Possible additional information to include:

Current Desktop app Mockups -
https://www.figma.com/file/71VdWCz238xAj9mIK3lXFD/Desktop-Applol?node-id=0%3A1

Tech Doc -
https://drive.google.com/file/d/13cFD0O2Ss5oypvdNWUnA-lY_bmkfa9M4/view?usp=sharing

Telegram Community - 
https://t.me/cypherock

Features on the roadmap
- Digital asset inheritance without loss of privacy and control of the assets
- Exchange integration on the Desktop app
- Arbitrary data storage on the hardware without a single point of failure.
- Staking through the Desktop app

**Comment by BlackTurtle123** [comment]
Are there any reasons not to integrate all waves tokens?
It should be easy after usdn and nsbt

**Comment by Hoshingen** [comment]
This grant is split into only two (big) milestones. Could you please specify smallers milestones and grants?

**Comment by rohanagarwal94** [comment]
> Are there any reasons not to integrate all waves tokens?
> It should be easy after usdn and nsbt

What all tokens are you referring here? Would be grateful if you can specify them for us to judge implementation timelines.

**Comment by rohanagarwal94** [comment]
> This grant is split into only two (big) milestones. Could you please specify smallers milestones and grants?

@Hoshingen I have split into smaller milestones.

**Comment by rohanagarwal94** [comment]
> > Are there any reasons not to integrate all waves tokens?
> > It should be easy after usdn and nsbt
> 
> @BlackTurtle123 What all tokens are you referring here? Would be grateful if you can specify them for us to judge implementation timelines.

**Comment by BlackTurtle123** [comment]
> > > Are there any reasons not to integrate all waves tokens?
> > > It should be easy after usdn and nsbt
> > 
> > 
> > @BlackTurtle123 What all tokens are you referring here? Would be grateful if you can specify them for us to judge implementation timelines.

Literally all waves tokens from wct to eurn to sign to TN,... Why would anyone use your hardware wallet if ledger supports all the assets default and you don't?

**Comment by rohanagarwal94** [comment]
> > > > Are there any reasons not to integrate all waves tokens?
> > > > It should be easy after usdn and nsbt
> > > 
> > > 
> > > @BlackTurtle123 What all tokens are you referring here? Would be grateful if you can specify them for us to judge implementation timelines.
> 
> Literally all waves tokens from wct to eurn to sign to TN,... Why would anyone use your hardware wallet if ledger supports all the assets default and you don't?

@BlackTurtle123 updated the same on the proposal. I misjudged it for something else.

**Comment by KardanovIR** [comment]
Waves Association Grants & Funding working group reviewed your application and unfortunately rejected it for now. You can re-apply by updating this issue as many times as needed.

The working group provided the next feedback to your project:

1. It is not clear how the Waves Ecosystem will benefit from the integration because there is no such demand in the community.

**Comment by rohanagarwal94** [comment]
@KardanovIR we believe security is relevant for every project. And the current hardware wallets like Trezor fall short around it. Because the wallets store the private keys in a single place, every current generation Crypto wallet is hackable. This was evident when Trezor wallet got hacked and now all of the Trezor wallets are vulnerable since it has an unfixable bug (https://cointelegraph.com/news/trezor-wallets-can-be-hacked-kraken-reveals).

Let me know what we can add to improve the proposal. We already have support of Btc, Eth and other projects are also in the process to get supported on the hardware.
