### ISSUE TITLE
Daofin - [Track 2. Web3.0 Development Grant] 

### ISSUE THREAD

**Issue by amovah** [Waves-Association/grants-program#32]
![Daofin-proposal banner](https://user-images.githubusercontent.com/6108180/106054997-06645680-6102-11eb-9675-6d9297874993.png)

- **Proposer:** Vladimir Kholodenko
- **Contacts:** vladimir19kholodenko@gmail.com
- **Github username:** amovah

## 👥  Team 

- Are you applying to implement the grant as an individual developer or do you represent a team?
Team.
- Are you a startup or an ongoing business? (in case applying as a team or startup)
Ongoing business
- What’s your team or startup name? What is a website? (in case applying as a team or startup)
Daofin Team

### Team members  (in case applying as a team or startup)

- Name of team leader
Vladimir Kholodenko
- Names of team members
Vladimir Kholodenko: Back-end developer, Solidity, and Ride engineer.
[Mehdi](https://github.com/mtt6300): DevOps engineer.
[Mersede Rahbar](https://github.com/MersedeRahbar): Front-end developer.
[Mojtaba Mousavi](https://dribbble.com/MojtabaMousavi): UI and UX designer.
Ritesh Ranjan: Product manager.

### Team experience  (in case applying as a team or startup)

- Please describe your (team/startup) development experience and technological stack? 
UI/UX, JS, React, Golang, Python, Solidity, Ride, NodeJS, DevOps, Kubernetes, Postresql, Blockchain Knowledge
- Do(es) you(r) (team/startup) have experience in using Waves technologies?
This was our first experience in the Waves network and we were able to learn the structure of the network and the syntax of Ride and publish the first version of the product.
- Please attach your (team/startup) portfolio (projects you’ve been involved in) 
[Zilon](https://zilon.io): A payment service for the Zilliqa network.
[Lumenswap](https://app.lumenswap.io): A swap interface for the Stellar network.
- Team website
We do not have Team Website.

### Team Code Repos

- [https://github.com/daofin](https://github.com/daofin)
- [https://gitlab.com/lumenswap.io ](https://gitlab.com/lumenswap.io )

## 🔍 Overview

Please describe your solution idea by the following structure:

- Short description of the solution you suggest
[Daofin](http://daofin.io) is an integrated platform that allows all Waves blockchain assets to build their DAO on Waves.
- How does it solve the specified problem?
We wrote a smart contract or so-called layer on the Waves network and implemented a unique method and structure with fixed rules for giving power and vote weight to all governance members.
We also tried to make Daofin understandable to all users by focusing on UI/UX and simplifying governance components that will increase network members' participation.
For more details on the Doafin structure, please refer to its [document](https://docs.daofin.io/structure/vote-weight).
- How you will integrate this project into Waves / Gravity / Neutrino.
Daofin is already integrated into Waves. We wrote a smart contract with Ride language and deployed it in Waves Blockchain. We also used Waves keeper for easy and secure communication with clients and sign transactions.
- Why your team is interested in creating this project.
We have been working on the idea of building a DAO platform with a fair model for a long time.
And when we saw the Waves association announcement, we decided to do it in the Waves blockchain.
Also, Waves Blockchain is light and decentralized, which was in line with DAO nature.
The Waves ecosystem has much potential for development, and we decided to work in this ecosystem and help develop this ecosystem.
- What is the target audience of the final solution?
Asset creators, project owners, and the whole Waves community.
- What is the “secret sauce” of it?
  1. Unique and anti-whale architecture.
  2. Beautiful UI/UX and Implementation comprehensibility components for users that migrated from Web 2 to Web 3.
  3. A platform for all assets.
- What is the duration of the whole project?
We have already released the demo version in the custom network. This version only supports WAVES Asset governance.
We need almost ~1 year to reach the ideal point of this product that supports all assets made on the Waves network.
- Resources required to implement the grant task
Node, Server & network infrastructure, marketing, Support team expenses 

### Ecosystem Fit

Are there any other projects similar to yours? If so, how is your project different?
We have not seen a DAO platform on this scale on the Waves blockchain, but I think Aragon in the Ethereum network can be an excellent example of a DAO platform.
The structure and concept of Daofin and the implementation of user-friendly components of the product are different from other platforms.

## 🔩 Development Roadmap 

This section should break out the development roadmap into a number of milestones. It helps to describe the functionality we should expect, plus how we can check that such functionality exists in the product. Whenever milestones are delivered, we refer to the roadmap to ensure that everything has been delivered as expected.

**Milestone 1** 
Info: Ideation and concept.
Duration: 8 weeks
Amount: 8,000 WAVES
Status: Done

**Milestone 2**
Info: Design the pages.
Duration: 3 weeks
Amount: 5,000 WAVES
Status: Done

**Milestone 3**
Info: Static implementation of the pages.
Duration: 4 weeks
Amount: 5,000 WAVES
Status: Done

**Milestone 4** 
Info: Server-side implementation, writing the smart contract for the WAVES asset DAO and deploying it on a custom network. 
Duration: 5 weeks
Amount: 10,000 WAVES
Status: Done

**Milestone 5** 
Info: Getting user feedback to improve the smart contract and governance rules, deploying in the main-net, and improving UI.
Audit smart contract code by helping the Waves development team.
Duration: 6 weeks
Amount: 2,000 WAVES
Status: Not started.

**Milestone 6** 
Info: Server-side implementation, writing the smart contract for supporting all assets created on Waves.
Audit smart contract code by helping the Waves development team.
Duration: 16 weeks
Amount: 35,000 WAVES
Status: Not started.

**Milestone 7** 
Info: Development and maintenance.
Duration: Forever
Amount: 5,000 WAVES
Status: Started.

### Overview

- **Total Estimated Duration:** Duration of the whole project
42 Weeks
- **Total Costs:** Amount of Payment in Waves for the whole project. The total amount of funding needs to not more than 100k Waves.
70,000 WAVES

## Additional Information ➕

Any additional information that you think is relevant to this application that hasn't already been included.

We published Daofin's demo version on the custom network. Right now, It only supports the WAVES asset DAO.

To test the demo, follow the below steps:
1. Install [Waves keeper](https://chrome.google.com/webstore/detail/waves-keeper/lpilbniiabackdjcionkobglmddfbcjo?hl=en#:~:text=Waves%20Keeper%20is%20an%20extension,securely%20from%20your%20Chrome%20browser.).
2. Set it to the Custom network then enter the following node address [https://demo-node.daofin.io](https://demo-node.daofin.io)
3. Create an account in the Custom network.
4. Go to [https://faucet.daofin.io](https://faucet.daofin.io)  enter your address and get the test WAVES.
5. Go to [https://demo.daofin.io/waves/overview](https://demo.daofin.io/waves/overview)  and connect your wallet. 

Now, you can view and work with different parts of the platform such as staking, creating proposals, claiming, and participating in votes.

We also launch a version of Wavesexplorer on our custom node to make it possible to search the transactions and view their details. 

[https://demo-explorer.daofin.io/custom](https://demo-explorer.daofin.io/custom)

To get the most out of Daofin, read all documents and governance rules and let us know your suggestions for future improvements.

### FAQ

**What is Daofin?**
Daofin is an integrated platform to build your DAO on the top of the Waves blockchain.

**I'm an asset issuer how can I build my governance on the Daofin?**
By default, Daofin supports the governance of all assets created on the Waves blockchain. As an asset issuer, you only need to recognize Daofin and introduce it to your community.

**How does Daofin help the Waves blockchain?**
Daofin allows all assets created on the Waves blockchain to have their own governance, which will drive the blockchain toward a democratic, community-based ecosystem.

**What is vote weight?**
Vote weight is a measure of a person's impact on the community.

**How can I earn vote weight?**
You can earn vote weight by staking your assets for a duration of your choosing.

**Are governance rules the same across DAOs in Dafoin?**
Yes. After researching how projects distribute assets, we have created a set of consistent anti-whale rules to benefit the majority.

**Where do the staked amounts go?**
All staked assets are managed by the Daofin smart contract, which is open source and you can check its source code on [Daofin's Github](https://github.com/daofin/daofin-smart-contract).

#### Links
**Website**: [https://daofin.io/](https://daofin.io/) 
**Document**: [https://docs.daofin.io/ ](https://docs.daofin.io/ )
**Github**: [https://github.com/daofin](https://github.com/daofin)
**Faucet**: [http://faucet.daofin.io/](http://faucet.daofin.io/) 
**Explorer**: [https://demo-explorer.daofin.io/custom/](https://demo-explorer.daofin.io/custom/) 
**Node**: [https://demo-node.daofin.io](https://demo-node.daofin.io)
**Demo**: [https://demo.daofin.io/](https://demo.daofin.io/)

**Comment by amovah** [comment]
Due to the increase in WAVES tokens' price, we have decided to reduce our requested grant to 50,000 WAVES.
We do not want to consume and take more than what we need and hope by doing this, more projects will have a chance to get a grant, which helps the WAVES ecosystem grow better and faster.
The amount of grant per milestone decreases relative to the total amount reduced.

Best regards
Vladimir

**Comment by BlackTurtle123** [comment]
I see a lot of milestones are already done, for what will the grant be used for the milestones? To pay for the working hours in these tasks?
If so do you have a cost/working hour breakdown or how did you estimate these amounts?

**Comment by amovah** [comment]
Hi, We have implemented the initial version of our product to show our team's technical skills, and our idea is not just a white paper now.
Yes, the milestones grant is the cost of the team members' task and the advance payment to start developing this product. Our biggest milestone is the support of all Waves blockchain assets governance that has yet to be done, which we think will take a period of four months to implement.

How this amount is obtained is a matter of details, We calculated this amount based on the value of our project (idea, implementation, maintenance) and the team members' cost.

**Comment by amovah** [comment]
Who is gonna use this project? Who is your target audience? 
The Daofin platform allows asset creators on the WAVES platform to create their own governance system at no extra cost. Our audience includes anyone that holds such assets, in other words, the whole WAVES community.

Did you make any customer development/research and what is the problem you're solving?

Daofin is simple, understandable, and Whale-free governance for all assets in the WAVES network. Our solution means that instead of each platform having its own DAO, they can use Daofin’s governance to streamline and unify the DAO structure of WAVES.

What their anti-whale rules?
Our Anti-Whale model incorporates vote weighing and the use of a time variable to create friction, to avoid ruling of Whales in the network. This model is explained thoroughly in the Vote Weight section.
https://docs.daofin.io/structure/vote-weight
https://medium.com/daofin/the-evolution-of-a-revolution-1a89760ebe9a

We need more details on your expenses and a more detailed milestones list
Overview
Initially, as we were writing our proposal, we set our budget based on the fiat price of WAVES which was $4 at the time to reach $280,000, however, as is the nature of cryptocurrencies, the price has changed since and with the current value of WAVES, the grant is more than we require for our budget. To simplify things and for the sake of transparency, we will use the stable currency for budget (USD).

Milestone 1
Info: Ideation and concept.
Description: As has been explained before in our article, we have been working on the DAO model and researching for the past three months about the pros and cons of different DAO platforms, trying to design a new architecture that would solve the issues that we see with other platforms. 
Duration: 8 weeks
Amount: $30,000 
Status: Done

Milestone 2
Info: Design the pages.
Description: Our designer has been working on the appearance of Daofin.io for about three weeks. While the current application is an MVP, it constitutes about 70% of our application's 
Core.
Duration: 3 weeks
Amount: $10,000 

Milestone 3
Info: Static implementation of the pages.
Description: At this step, our front-end engineers implemented our application using React, although without an actual connection to the smart contract and our backend service as of yet.
Duration: 4 weeks
Amount: $20,000
Status: Done


Milestone 4
Info: Server-side implementation, writing the smart contract for the WAVES asset DAO and deploying it on a custom network.
Description:
- Development of our back-end, supporting a single asset at this point.
- Setting up a custom node to allow users to test easily
- Implement the smart contract, supporting only WAVES token
- A process for syncing the custom node with the application's database, to allow users to work with the smart contract and see the results on the website
Duration: 5 weeks
Amount: $30,000
Status: Done


Milestone 5
Info: Getting user feedback to improve the smart contract and governance rules, deploying in the main-net, and improving UI.
Description: This is the step we are currently at, where we need to collaborate with WAVES and its community. That is, we want to gather feedback to develop the project further and extend our features with the ones deemed most important through the feedback. Furthermore, we will prepare the smart contract for deployment on the mainnet network, although we are aware that this requires a review and approval of the smart contract.
Audit smart contract code by helping the Waves development team.
Duration: 6 weeks
Amount: $20,000
Status: Not started.

Milestone 6
Info: Server-side implementation, writing the smart contract for supporting all assets created on Waves.
Description:
This is the most important and toughest milestone in our milestones. As a result, We will provide a platform where all asset creators on the waves platform can have their own governance. This step consists of creating the infrastructure for fetching all assets data, developing the backend and the smart contract to support all assets. Also, it requires another audit from the waves team.
Audit smart contract code by helping the Waves development team.
Duration: 16 weeks
Amount: $140,000
Status: Not started.


Milestone 7
Info: Development and maintenance.
Description: The cost of our servers, maintenance of our codebase through fixing bugs as they may arise, our CI/CD infrastructure and monitoring solution (DataDog), and more.
Duration: Forever
Amount: $30,000
Status: Started.

Total Costs: $280,000
Total duration: 40 weeks

The ideal grant we require for the application is around $280,000, but we can work with a minimum of $200,000. Also the grant can be paid in instalments for each milestone.

**Comment by KardanovIR** [comment]
Waves Association Grants & Funding working group reviewed your application and unfortunately rejected it for now. You can re-apply by updating this issue as many times as needed.

The working group provided the next feedback to your project:

1. It is not clear who are users of DAOs. It would be great to see users/customers (companies or individuals) who gonna use the product now or in the future.
2. We didn't get what are your anti-whale rules and they really needed.
3. Expenses look very-very large and not reasonable for an MVP.

We'd be happy to see product improvements and progress and to re-evaluate your application in the next couple of months.
