### ISSUE TITLE
waves.loans | Borrowing and Lending (Loan) platform

### ISSUE THREAD

**Issue by amovah** [Waves-Association/grants-program#41]
## NOTE

After receiving feedback about my recent proposal, [Daofin](https://github.com/Waves-Association/grants-program/issues/32), I’ve figured out Daofin is too soon for Waves platform yet. I’ve used feedback and worked on another project which can be useful for all WAVES users and it grows the Waves ecosystem. Also, According to feedback I’ve reduced my team size for creating prototype.

Application currently is prototype.

---

- **Proposer:** Vladimir Kholodenko
- **Contacts:** vladimir19kholodenko@gmail.com
- **Github username:** amovah

## 👥  Team 

- Are you applying to implement the grant as an individual developer or do you represent a team? Team
- Are you a startup or an ongoing business? Ongoing Business
- What’s your team or startup name? What is a website? -

### Team members  (in case applying as a team or startup)

- Vladimir Kholodenko
web Full-Stack Engineer, Solidity, and Ride engineer.
- [Mehdi](https://github.com/mtt6300): DevOps engineer.

### Team experience  (in case applying as a team or startup)

- Please describe your (team/startup) development experience and technological stack? 
UI/UX, JS, React, Golang, Python, Solidity, Ride, NodeJS, DevOps, Kubernetes, Postresql, Blockchain Knowledge
- Do(es) you(r) (team/startup) have experience in using Waves technologies?
Yes. Daofin was our first official experience in using Waves Technologies and writing ride smart contract and integrate with web application.
- Please attach your (team/startup) portfolio (projects you’ve been involved in) 
[Zilon](https://zilon.io/): A payment service for the Zilliqa network.
[Lumenswap](https://app.lumenswap.io/): A swap interface for the Stellar network.
- Team website: -

### Team Code Repos

- https://github.com/waves-loans
- https://gitlab.com/lumenswap.io 

## 🔍 Overview

Please describe your solution idea by the following structure:

When we look at current dApp in the blockchain world, DeFi dApp has first place, lending and borrowing has second place. For instance, applications like Compound and Maker in Ethereum have the most usage  and volume after swapping platforms like Uniswap. Waves.loans is a platform for lending and borrowing assets on Waves. Users can simply lend assets to earn profit or borrow assets.

**I highly suggest after reading, you should read [guide](https://github.com/waves-loans/frontend/blob/master/GUIDE.md) to understand waves.loans platform better.**

- Short description of the solution you suggest
When we look at current dApp in the blockchain world, DeFi dApp has first place, lending and borrowing has second place. For instance, applications like Compound and Maker in Ethereum have the most usage  and volume after swapping platforms like Uniswap. Waves.loans is a platform for lending and borrowing assets on Waves. Users can simply lend assets to earn profit or borrow assets.

- How does it solve the specified problem?
Lending and Borrowing is one of the basic needs in the real world, which with waves.loans I'm trying to bring this feature as open-source and decentralized financial for earning interest to the Waves platform.

- How you will integrate this project into Waves / Gravity / Neutrino.
dApp core is written in RIDE language, so users can use the smart contract directly. but for convenience of users, I’ve built a web application for users to integrate better with the platform.

- Why your team is interested in creating this project.
I’m always interested in the DeFi system and I think something like waves.loans is missing in dApp list of Waves platform.

- What is the target audience of the final solution?
All users can use this application to earn definite profit or borrowing to keep original assets. also it can be use with other waves dapp application.

- What is the “secret sauce” of it?
1. Users can simply lend their assets and without any fear of losing their asset and ear profit in a decentralized way without interfering in profit.
2. The Application generates revenue with a small portion of borrowing interest as application itself profit.

- What is the duration of the whole project?
4-5 month after receiving grant, for deploying stage one of application into mainnet and official launch (lending and borrowing USDN/WAVES).
Other stages depend on how much users are using the platform, and their feedback about the platform. Then we can prepare a plan for the next version to support more assets and bring more features and improvements to the application.

- Resources required to implement the grant task
I need some USDN for initial funding USDN pool which users can borrow USDN.
Also I need some UDSN to fund workers which it's part of the application.
both of above resources can be done directly by Waves association members, so they can extract their assets whenever they want.

### Ecosystem Fit

Are there any other projects similar to yours? If so, how is your project different?

Compound and Maker in ethereum blockchain. Waves.loans are very similar to Compound but we handle users collateral and their debts in different ways. we also use neutrino for price feed.

## 🔩 Development Roadmap 

This section should break out the development roadmap into a number of milestones. It helps to describe the functionality we should expect, plus how we can check that such functionality exists in the product. Whenever milestones are delivered, we refer to the roadmap to ensure that everything has been delivered as expected.

**Step #1**:  Implement prototype to show waves association members my technical skills and help them to understand my platform concept. (Done)

**Step #2**: Implement main version of the application (Not Started)

- Expand team, Hire front developer, UI/UX designer and product manager
- Fix potential bugs
- Audit Smart contract by waves team
- Changes according to waves association members feedback.
- Prepare a complete doc for the application
- Running workers in several servers.
- Initial funding the main pool of application.

**Step #3**:  Plan for the next version and maintenance

after receiving feedback from users how much and how users are using the platform, we can plan for the next version which included supporting more assets and improvements.

Within this application we are requesting **Step #1** and **Step #2** in total of 35K$ and pool and workers funding which it can be done directly by waves members.

### Overview

- **Total Estimated Duration:** 4-5 Months after receiving grant.
- **Total Costs:** 35k$ (ideal grant for me is 45K so I can fund the pool and workers better, but 35K is very great)

## Additional Information ➕

Any additional information that you think is relevant to this application that hasn't already been included.

Possible additional information to include:

[App](https://waves.loans) It's only prototype. it's not final version.
[Video](https://drive.google.com/file/d/1MJE-h_z0hE_9zWmd1TZpeQsf2R_fRVnN/view?usp=sharing) how to use application
**I highly suggest after reading, you should read [guide](https://github.com/waves-loans/frontend/blob/master/GUIDE.md) to understand waves.loans platform better.**

**Comment by BlackTurtle123** [comment]
Please look to projects like sign-art and include budget/milestones/smaller pieces/kpi's/..

Currently you put 1 big money request, please split this up according to milestones.

Grants are given in parts milestone based and decided KPI based.

**Comment by amovah** [comment]
**Step #1**: Implement a prototype to show waves association members my technical skills and help them to understand my platform concept. (Done)

**Step #2**: Application Concept & Design: (1 month, ~$8k)
Work on application UX to provide better user experience and change application concept according to waves association members feedback (if needed). hire a designer and design application pages.

**Step #3**: Frontend (Statically Step): (1 month, $4k)
Hire Frontend Engineer, Implement front-end pages statically according to designs.

**Step #4**: Smart Contract: (1 month, $5k, can be done simultaneously)
Implement and re-write dApp smart contract for waves mainnet. Audit smart contract by waves team and fix potential bugs and deploying into mainnet.

**Step #6**: Backend: (1 month, $6k, can be done simultaneously)
Implement a backend application to provide some analytics data for users.
Optimize workers script, provide dockerfile quick start docs for other users to participate in the program, and buy 2-3 small servers and run workers on them.

**Step #7**: Integration & Deploy (2 weeks, it also included server costs for ~6 month [workers and main application servers] , $5k)
Integrate frontend with backend and smart contract. fix bugs and minor improvements.
Deploy application (frontend & backend) on our infrastructure.

**Step #8**: Fund Pool ($10k, or $0 - Optional)
Fund supplier pool. It can be done directly by waves members, so they can withdraw assets whenever they want, or waves members can fund my waves address, so I can fund the supplier pool. $10K for the initial supplier pool is great.

Fund supplier pool is optional and it can be done by waves members. Otherwise I should supply the pool in another way.

**Step #9**: Maintenance ($5k)
Maintenance application , bug fixes and minor improvement.

I have also planned for supporting more assets on the platform, more features, but I cannot decide right now. I need metrics, user feedback. I've researched similar applications (like compound and maker in ethereum), but I need to decide the application roadmap based on WAVES users and their needs.

**Comment by jansenmarc** [comment]
How does this relate to vires?

**Comment by BlackTurtle123** [comment]
Hello @amovah you say you got a prototype working, but it shows us a lot of funds, is it just mock data?

Regards

**Comment by amovah** [comment]
@BlackTurtle123 it's on testnet, not mainnet
