### ISSUE TITLE
Untitled Tech

### ISSUE THREAD

**Issue by daler-als** [Waves-Association/grants-program#42]
**Proposer: Introduce yourself (name, surname)**
- Daler Aliyorov  
      
**Contacts: Your email or telegram handle**
- [daler@aliyorov.com](mailto:daler@aliyorov.com)
    
**Github username: Your Github login**
- [https://github.com/daler-als](https://github.com/daler-als)
    

## 👥 Team 

**Are you applying to implement the grant as an individual developer or do you represent a team?** 
- Untld Tech Team
         
**Are you a startup or an ongoing business? (in case applying as a team or startup)**
- Startup  

**What’s your team or startup name? What is a website? (in case applying as a team or startup)**
- [https://untld.pro/en/](https://untld.pro/en/) 

### Team members (in case applying as a team or startup)
- Maxim Mishin 
- Albert Iblyaminov 
- Ivan Vashchenko 
- Sergey Zondrikov   
- Daler Aliyorov    

### Team experience (in case applying as a team or startup)

**Please describe your (team/startup) development experience and technological stack?**
    
- Project stack:  
  - Frontend — TypeScript, Angular, CSS3, HTML5, Bootstrap 5.  
  - Backend — Graphql, Strapi, MongoDB, NodeJS.  
  - Infrastructure — Kubernates, Docker, AWS, Github CI/CD  
  - Smart Contracts — Waves 
- Key team experience:
  - Banking websites, online store, internet catalogs, small and medium landing pages, calculators for deposits, credits, savings accounts, big support portals, medical services and other mvp projects. Took part in development of Tatneft, Raiffeisen, MKB, Alfabank, Yandex, Gazprom, TPS, Rambler, ОСК  

- We work in commercial project with:
  - Postgres, MySQL, MongoDB, TypeORM. Sequelize ORM.  
  - Gitlab CI/CD, Github CI/CD, Google cloud platform, AWS, Kubernetes, Docker, Webpack, Gulp, Grunt, Git, SVN.      
  - TypeScript, JS, Angular, React, NodeJS, PHP, Python, Parser.  
  - Jira, Basecamp, Asana, Notion, Trello, Github Issue, Gitlab Issue, Google Docs   
  - Figma, Photoshop, Illustrator, InDesign, Premier Pro, After Effects. Sketch    

      
**Do(es) you(r) (team/startup) have experience in using Waves technologies?**
- Yes. We’ve been developing:
  - First versions of the browser plugin for Ergo Platform
  - Carbon footprint calculators based on the Ethereum blockchain carbon registry
  - Participated and won prizes in two blockchain hackathons: 
      - [Waves Hackathon](https://habr.com/ru/company/binarydistrict/blog/432050/) (24 dec 2017)
      - [Odyssey Hackathon 2020](https://medium.com/wavesprotocol/hacking-with-waves-4fc255e950e6)
  - Created a [project]([https://blockchain.carbonfootprintitaly.it/](https://blockchain.carbonfootprintitaly.it/)) to register the carbon footprint of companies and products in Italy based on Ethereum
- Due to this experience, we decided that the optimal blockchain for our project would be Waves  
   
**Please attach your (team/startup) portfolio (projects you’ve been involved in)**

- Projects:  
  - [Maxim Mishin](https://www.artlebedev.ru/maxm/),
  - [Albert Iblyaminov](https://www.artlebedev.ru/rie/)
  - [Ivan Vashchenko](https://www.artlebedev.ru/vanya/), 
  - [Daler Aliyorov](http://aliyorov.com/en).  
- Team website  
  - [https://untld.pro](https://untld.pro/en)     

### Team Code Repos
- Utld.pro: [https://github.com/untld-tech](https://github.com/untld-tech)  
- Project's final code is being kept non-public
    
## 🔍 Overview
**Short description of the solution you suggest**

- Untitled is an extremely simple and convenient service for creating technical specifications for developers. It simplifies and speeds up the launch of web projects, facilitating communication between business and developers at the initial stage. The team is working to make Untitled a tool that will lower the entry threshold into development for businesses of all sizes.

**How does it solve the specified problem?**
   
- The creation of any website or app consists of blocks of tasks. So we propose to standardize and formalize them — this speeds up the process and simplifies the evaluation of work. We have presets — standard terms of reference (TOR) for common cases. We also offer ready-made blocks and pages which you can easily assemble into your own TOR. You can share a link to your project or download it in PDF. The interface of the service is intuitive and does not require special knowledge.  
  
- A basic version of a document can be made in five minutes. It will be enough to give just a couple of words about the project and add the necessary pages and elements from the list of prepared blocks. At the end you will get a simple and beautifully designed document, which you can download as PDF or get a link to.

**How you will integrate this project into Waves / Gravity / Neutrino.**

- Why we want to use Waves:
  - We know its features, strengths and specifics 
  - Waves can be used without browser plugins. Transactions can be performed with the browser itself and even on mobile devices. This is a very important feature for us:
    - We can not force users to understand how blockchain works. Working with blockchain must be transparently built into the process without any additional steps.
    - What we need from blockchain are ready to use mechanisms (contracts) for user interaction in different scenarios.            
    - We need to provide a choice of suitable scenarios for different projects, and in the future allow to create new scenarios — contracts are great for this.
    - This mechanism was tested at the Odyssey hackathon. And now we have several hypotheses on how to combine authorization in the project with a wallet in the blockchain and minimize risks of compromising user secrets.
  - We don't want to write from scratch the functionality of users interaction and support additional servers or develop our own blockchain.            
  - Fixed commissions. In cryptocurrencies with turing full languages, the risks are hidden not only in the fluctuations of the exchange rate, but also in the fluctuations of the value of transactions depending on their number. And the total fluctuations in value become unpredictable.
  - The advantages of a fixed commission:
    - Allows to estimate the total cost of automatic transactions           
    - Estimate the cost of scaling the system            
    - Offer different mechanics of reciprocal payments            
    - Low fixed commission in relation to the value of the cryptocurrency 
  - Sufficient supply of Waves will ensure the stability of work, regardless of the rate of the cryptocurrency. 
  - Changes would only be required for very large and strong correlations, which are quite rare.
  - Since our sub-projects are solutions at the intersection of different existing tools (task managers, documents, freelance markets) we need an effective data bus for the results between them and a certain independence of each sub-product.           
  - We need to record interactions between users. Waves will give us a simple and transparent signature mechanism.      
  - Many different roles exist to collaborate on projects. Decentralised autonomous organisations (DAO) are really suitable for this. We also will be able to bring different interaction schemes into blockchain where they will be more transparent. It will be possible to choose the interaction model for each project.            

**Why your team is interested in creating this project.**
    
- Every member of our motley crew has experienced a start of a new project with a new customer. It usually takes ages just to formalize the scope and finally begin to work. Someone had to put an end to it. And here we are — applying for a grant.

**What is the target audience of the final solution?**
    
- Small and medium businesses, and contractors: freelancers, developers, designers, etc.

**What is the “secret sauce” of it?**
    
- Secret sauce of Untitled is definitely in our diverse background. And what is more important — we’d like to create not just another service. We want to create an expert system and put the knowledge and experience we gained into it.

**What is the duration of the whole project?**

- The project was started in Jan 2021. So far we have a basic version of the creation of the terms of reference. We’ll need a mechanism for collaborative work on the terms of reference, the possibility of sharing between the participants. To do this, we need the integration of visual editors in the description, the development of a system of roles, logging and a system of accepting changes. 
- It will take us about 12 months to get to the working product. 
- But we want not only to generate tasks but also allow users to close deals for executing tasks. A deal is a record in the blockchain of the state of the ToR, which can be accepted as an actual ToR for the contract. We need to create a template for a typical contract where the ToR is fixed and the budget is agreed. Blockchain guarantees the immutability of information, so any changes in the ToR will require a change in the blockchain as well. The main goal is to replace numerous sheets of ToR with a single paragraph containing a link to the site where the file can always be downloaded. 
- We are going to spend 12 months on integrating with Waves.

**Resources required to implement the grant task**

- Team:      
  - 2 fullstack developers,     
  - 1 designer,     
  - 1 manager,     
  - 1 tester,         
  - Additional server powers for all services and tools    
  - Marketing for audience engagement and hypothesis testing 
- Base flow: as part of the grant, we will create the first part of our project, which should reach a payback on monthly development costs.
- Investment flow: find and test points of growth, to attract investments.

### Ecosystem Fit

The main advantage for Waves is that the ecosystem attracts people who are not familiar with cryptocurrency:
- They start using the technology without getting into the maze of blockchain, using it as a tool for interaction. Instead they gradually build up their knowledge of cryptocurrency and blockchain.
- The project can show blockchain from a technology perspective and demonstrate practical applications in everyday project work.
- Demonstrate opportunities of reducing the labor costs of implementing an interaction system between participants.
- We believe that blockchain is the future for all legal documents. Our project is already taking a step toward automating the process of storing the original and all changes to a technical document using blockchain technology.   

**Are there any other projects similar to yours? If so, how is your project different?**

- Task managers (Jet Brains Space, Gitlab Issue, Github Issue, Work zen, e.t.c.).

- Document generators and technical task templates (Smart Document Drafting, Nintex, GeneraTOR).

- Code autodocumentation tools (Swagger, StoryBook, React DocGen, Compodoc, Angular Doc).

- Difference and value:
  - We do not create task manager, document generators or code autodocumentation tool. We create additional tools for more relevant task managers and owner.  
  - We create expert system, with our experience inside. Other tools are more general. We propose flow that will help to cut the time for development.  
  - Our flow propose steps steps for project formulation, creation, search for performers, fixing the arrangements of documentation with the significant reduction of time spent on communication.
- There is a gray zone between the existing tools. And this zone is difficult for newcomers to understand, and where time and money are lost. The less experience you have, the more the expectations diverge from the result. We want to give the tools to work effectively in this zone.

- We are well aware of the problems of time constraints.
  - When we see the features of other products:    
    - "you can create and prioritize tasks",    
    - "you can group and divide tasks",
    - "you can create reports",
    - "you can mark time".
    
  - And immediately we ask questions:
    - "Who's going to do it?"
    - "Does it really bring results or is it just to meet deadlines?"
    - "Why does the time in tasks depend on the mood of the developer?"
    - "Why can't you get a report if you haven't kept a task?",
    - "Why can't you check the development plan if you haven't marked the time?"
    
We have accumulated enough experience and have something to offer in solving many issues that are at the intersection of existing tools.

  

## 🔩 Development Roadmap

- We calculated the process in sprints. Where one week roughly equals one sprint. 

- The team that will be hired to implement the project
  - 2 Developers (fullstack) = $17 per hour × 40 hour a week  × 2 person = $1360 per sprint
  - 1 Designer = $17 per hour × 20 hour a week = $340 per sprint
  - 1 Manager = $8.5 per hour × 40 hour a week = $340 per sprint
  - 1 QA = $8.5 per hour × 15 hour a week = $340 per sprint
- Estimated development cost per sprint: $2167.50. 

  
### Q3 / 2021 / $34,993

**Milestone 1. Prepare documents, estimated project and find developers**

#### 3 sprints / $6502.5

Estimates presets for blocks. These are blanks in order to be able to calculate the approximate duration and cost of the project at the stage of preparing the ToR. Estimate the complexity and the required size of the team.

#### 5 sprints / $10,837.5

ToR estimation tool before sending to potential performers. Visualization of data about the project cost, timing, complexity based on the aggregated data. Allows you to adjust expectations and clarify the completeness of the ToR before sending it to performers. Allows you to quickly calculate the approximate business plan and economics of the project.

#### 3 sprints / $6502.5  

Mechanism for viewing and editing commercial proposals to potential performers based on the generated ToR and Excel export. A toolkit that will allow performers to quickly set estimates, their cost of work and describe the experience that will contribute to the quality of the order.

#### 3 sprints / $6502.5  
  
Management of commercial proposals (consideration of estimates and cost of works in the project). Tools for comparing proposals, selection, evaluation. Automation of the use of proposed data for the further creation of the project and accounting of proposed data in the contracts.

Marketing / $3948 per quarter

Servers / $700 per quarter

  

### Q4 / 2021 / $27,594.5

**Milestone 2. Integrate with blockchain**

#### 8 sprints / $17,340

Configuration and creation of project workflow. Toolkit and backend for generating the information-expert core of the project:

-   Developing 2 core strategies. Writing strategy contracts. Interface for strategy selection (flow).
    
-   Management of workflow users
    
-   Defining workflow roles
    

#### 3 sprints / $6502.5

User Profiles. Mechanisms for binding a user to the blockchain. Authorization with seed generation and issuance of small portions of asserts on transactions in the blockchain.

Marketing / $3102 per quarter

Servers / $650 per quarter  
  

### Q1 / 2022 / $27,594.5

**Milestone 3. Work over blockchain**

#### 5 sprints / $10,837.5

Information versioning in Workflow. Collaborative versioning of documents with consent confirmations via blockchain. Ensuring that all parties agree in accordance with flow to manipulate documentation and project data.  
  

#### 2 sprints / $4335

Confirming agreements via blockchain.

#### 4 sprints / $8670

Generating model contracts for verified states.

Marketing / $3102 per quarter

Servers / $650 per quarter

  

### Q2 / 2022 / $13,493.5

**Milestone 4. Expansion**

#### 3 sprints / $6502.5

Configurable export of tasks according to the selected flow to the version control system.

  

#### 5 sprints / $4335

Synchronizer of changes between ToR and the version control system.

Marketing / $2256 per quarter

Servers / $400 per quarter

## Overview

-   Total Estimated Duration: 12 months (ETA: 2022-05-30)
    
-   Total Costs: 103,675 USDT for extensive steps to use Waves on service
    
-   Our sprint based process allows to split grant into parts.

**Comment by BlackTurtle123** [comment]
Hello; the application is denied for following reason:
We don't see the use-case for the blockchain, or any benefit in using the blockchain.
