### ISSUE TITLE
[Track 2. Web3.0 Development Grant] 

### ISSUE THREAD

**Issue by PascalParvex** [Waves-Association/grants-program#43]
- Pascal Parvex
- pascal@parvex.org
- PascalParvex

## 👥  Team 

- Are you applying to implement the grant as an individual developer or do you represent a team?
Team. Me and a coder, who is no longer available, as he no longer wants to work on the Waves Blockchain. But the project is done and can be administrated by me.
- Are you a startup or an ongoing business? (in case applying as a team or startup)
Ongoing business
- What’s your team or startup name? What is a website? (in case applying as a team or startup)
You can see the finished project on https://WavesPlay.com

### Team members  (in case applying as a team or startup)

- Pascal Parvex
- Damian Ravi (no longer available for Waves projects, if you know somebody who is willing to work for Waves payment, I am listening, as It would be nice to add more games)

### Team experience  (in case applying as a team or startup)

- I myself gave precise instructions to Damian on how the website has to work.
- I have created several Waves tokens (https://eFranken.org, https://eKaulitz.org, https://KHADD.org (German), https://BitcoinSpeed.org); For Damian, it was his first project on the Waves blockchain.
- For me, see above, for Damian see https://www.freelancer.com/u/DRSankara
- https://WavesPlay.com, https://Parvex.org

### Team Code Repos

Code is closed source, but I have access to the source files. I own the rights to the project and source files. I am not experienced in Github, you may have to instruct me.

## 🔍 Overview

Please describe your solution idea by the following structure:

- Gamble with an extendable selection of Waves token.
- How does it solve the specified problem?
Fast on-chain betting, adding new tokens takes about two minutes if all the information is provided
- How you will integrate this project into Waves / Gravity / Neutrino.
Waves and Neutrino token are supported
- Why your team is interested in creating this project.
As mentioned above, the project is complete; depending on size of possible grant, and an experienced coder, the assortment of games could be expanded, for example with a roulette.
- What is the target audience of the final solution?
Gamblers for customers, token creators for clients.
- What is the “secret sauce” of it?
On chain gambling with Waves Keeper, no listing fee, and I don't assume ownership of bankroll provided by token creator
- What is the duration of the whole project?
Already live.
- Resources required to implement the grant task
Main: Waves funds to stock the bankroll of Waves and the well known tokens. I plan to stake a good part of the Waves grant, so that the Waves bankroll is auto-refilling.
Optional: Provide a coder to extend the game selection

### Ecosystem Fit

Are there any other projects similar to yours? If so, how is your project different?
- There are very few gambling sites who even offer Waves, and almost none who offer more than just Waves. The Waves token selection of WavesPlay.com is unprecedented. And don't forget, the site works on chain, so it is not possible to win without getting paid.

## 🔩 Development Roadmap 

This section should break out the development roadmap into a number of milestones. It helps to describe the functionality we should expect, plus how we can check that such functionality exists in the product. Whenever milestones are delivered, we refer to the roadmap to ensure that everything has been delivered as expected.

**Step #1**: Funds for Bankroll to attract players

- 1K Waves for staking to produce Waves stock -> needed to play and pay the fee for win payment transactions
- 1K Waves to stock WBTC, WETH, Monero an so on

**Step #2**: Funds for running expenses:

Monthly cost of around $30

**Step #3**:  [Optional] Funds to pay for a (provided by you?) developer

Rates vary vastly, I paid around $2K for the site in its current state.

### Overview

- **Total Estimated Duration:** Duration of the whole project

Around one hour to stake the Waves and to stock the other tokens

- **Total Costs:** Amount of Payment in Waves for the whole project. The total amount of funding needs to not more than 100k Waves.

2'000 Waves.

## Additional Information ➕

Any additional information that you think is relevant to this application that hasn't already been included.

WavesPlay has been the top Waves gambling App for quite some time on DappRadar: https://dappradar.com/rankings/protocol/waves

Right now there are not many players, as most of the stock of the "valuable" tokens has been won by players. Site takes a 4% cut on winnings only, losses go to bankroll. Site itself has a link to an extensive FAQ.

Possible additional information to include:

Site Logo attached
![wplogo](https://user-images.githubusercontent.com/31865329/122659245-5bb70800-d176-11eb-8180-ab52cbf20200.png)

Link to project: https://wavesplay.com

**Comment by BlackTurtle123** [comment]
Please look to projects like sign-art and include budget/milestones/smaller pieces/kpi's/..

Currently It seems more like 3 costs, but not milestones and timelines
