### ISSUE TITLE
Open Block - EI on WAVES

### ISSUE THREAD

**Issue by BlockStarLogic** [Waves-Association/grants-program#49]
- **Proposer:** Block Star Logic 
-**Project Lead & Contact.** Tau Ushe
- **Contacts:** tau@blockstarlogic.com 
- **Github username:** BlockStarLogic
- **Reward:**  2372 Waves

## 👥  Team 

- Are you applying to implement the grant as an individual developer or do you represent a team?
 **Team** 

- Are you a startup or an ongoing business? (in case applying as a team or startup)
 **On going business** 

- What’s your team or startup name? What is a website? (in case applying as a team or startup)
 **[Open Block - Enterprise Initiative (Open Block - EI)](https://www.blockstarlogic.com/obei)** 
delivered by [Block Star Logic (BSL)](https://www.blockstarlogic.com) 

### Team members  (in case applying as a team or startup)

 **[Tau Ushe (Project Leader)](https://www.github.com/cryptotwilight)** 

The team roles for this grant delivery would initially be:

For this project a new  team will be recruited to execute the delivery. The initial* role structure will be the following 

|Role 			      | 
|----------------------------------|
|Project Lead                    |
|Project Manager 	      |
|Core Dev                         |
|Core Test 		      |
|Documentation Manager |

*subject to change

### Team experience  (in case applying as a team or startup)

My experience stems from over 20 years in Management consulting and Digital transformation. I have worked across a range of industries including banking, finance, global settlements, and government. I have also been an award winning hackathon participant, with wins on Ethereum, Filecoin, and NEAR blockchains at events such as EthCC and Browsers3000. 

 A new team unfamiliar with the WAVES blockchain will be recruited, trained and managed for this project delivery, and led by the Project Lead.

### Team Code Repos

The following is the central repository for the team:
- https://github.com/Block-Star-Logic/

## 🔍 Overview

The  **[Open Block - Enterprise Initiative (Open Block - EI)](https://www.blockstarlogic.com/obei)** has been created to address the transformation of **Centralized Business Enterprise** into something that operates on open, decentralized, permissionless and trustless “public blockchain”. This being the opposite of closed  "private blockchain". 

Centralized Business Enterprise has been tectonically disrupted by Web3 well beyond the disruption of the internet or Digital (Web 2.0). However the action being taken in the blockchain Enterprise space is often skeuomorphic, seeking to retain Digital models of Web 2.0, which often don't work so well or need to be rethought as part of Web 3.0. 

Unfortunately Web 3.0 and blockchain industries are still in the very early stages whilst already faced with institutional and hence Enterprise class interest, demand and associated regulation (see [‘Matrix Resurrections’ NFT Website Crashes After Overwhelming Demand](https://variety.com/2021/film/news/matrix-resurrections-nft-website-crashes-1235122953/amp/) ). 

### The Problem
The problem is that with the break neck speed of innovation in Web 3.0 little is being done to understand and let alone build Web 3.0 and public blockchain infrastructure (smart contracts, oracles etc) that can enable new Web 3.0 innovations to rapidly and/or automatically scale to service Enterprise communities and demand. 

### The Solution
The solution to this problem is the **[Open Block - Enterprise Initiative (Open Block - EI)](https://www.blockstarlogic.com/obei)**. The aim of the programme is to jump start this new Web 3 Enterprise innovation that runs counter to the Walled Garden Enterprise of the late 20th century, with a [**"community commons"**](https://en.wikipedia.org/wiki/Commons) based method of design and build of “public blockchain” components that confer Enterprise class capabilities to new and existing Web 3.0 and blockchain projects

The inspiration for this approach came from how the [Apache Server](https://httpd.apache.org/) built by the [Apache Group](https://httpd.apache.org/ABOUT_APACHE.html) led to the solid foundations of the internet as it is today. 

### The Commons
Advancing on the [Open Commons](https://httpd.apache.org/ABOUT_APACHE.html#:~:text=Why%20Apache%20Software%20is%20Free%C2%B6) ethos, **Open Block EI** has been designed to work across blockchains as Enterprise interoperability but now blockchain interoperability and service availability are a big challenge area to Business Enterprise. The manifestation of this challenge in Web 3.0 is how several projects like [Curve](https://curve.fi/) and [Sushi Swap](https://sushi.com/) have opted to deploy on multiple Ethereum L2 solutions as opposed to relying on Ethereum Ecosystem bridge technology to service cross chain needs.  

### Building on Waves / Gravity / Neutrino 
The WAVES blockchain is currently not supported by **Open Block EI**. The purpose of this Grant application is to fund the **Open Block EI on WAVES** programme. The goal of the programme is  to design and implement the current vanguard **Open Block EI** projects natively on the WAVES blockchain. This would enable new and existing WAVES Ecosystem projects to adopt the new functionality easily whilst enabling the **Open Block EI** projects to avail themselves of the differentiating design enablers of the WAVES blockchain. 

The vanguard projects of **Open Block EI** are **[Open Roles](http://www.blockstarlogic.com/obei/pages/open_roles.html)** which focuses on decentralized role management and **[Open Bank](http://www.blockstarlogic.com/obei/pages/open_bank.html)** which focuses on decentralized non-custodial banking. Whilst **Open Roles** would have a natural affinity to leveraging the Gravity Protocol on Waves, **Open Bank** would have a natural affinity for the Neutrino protocol. 

The objective of the **Open Block EI on WAVES** grant funding is to enable the build of a team new to the WAVES Ecosystem, with the mission to create Ride native implementations of both **Open Block EI** vanguard projects for the WAVES blockchain. 

### Why This Programme?
The Block Star Logic interest in this work is simple, Web 3.0 Enterprise is the backbone of the new World Economy. Web 3 Enterprise will determine whether [climate change](https://digital-strategy.ec.europa.eu/en/policies/blockchain-climate-action), [privacy control](https://publications.jrc.ec.europa.eu/repository/handle/JRC111879), [Pandemic Response](https://www.thelancet.com/journals/landig/article/PIIS2589-7500(21)00210-7/fulltext), [United Nations Sustainable Development goals](https://www.weforum.org/agenda/2021/10/why-blockchain-is-the-key-to-meeting-the-sdgs/) and more will be achieved to the benefit of all peoples and communities. With worldwide regulatory uncertainty and phenomenal community enhancing developments in Web 3.0, the BSL view is that the Web 3.0 Enterprise Commons across all blockchains needs to be defined now with some urgency so as to preserve the global freedoms that are emerging with the technology. 

### Who is this Programme for?
The initial audience of the deliverables emergent from the programme would be the WAVES Ecosystem BUIDLR community, with downstream beneficiaries being WAVES dApp user communities. The programme would bring open source commons based **Decentralized Role Management** which would facilitate a more complicated Enterprise oriented role (as opposed to wallet) based smart contract interaction model. The programme would also bring the real disruption of **Non-Custodial Banking** to dApps enabling organisations to innovate new and more beneficial methods of “on chain” funding, financing and treasury management. 

### The Secret Sauce?
The secret sauce of this **community commons** based programme is the [inversion of control](https://dzone.com/articles/inversion-of-control-explained-non-technically) and [liberation of new freedoms](https://www.npr.org/2021/11/21/1056988346/web3-internet-jargon-or-future-vision?t=1638497706776) for communities, business and DAOs on the WAVES blockchain. 

To illustrate, a dApp that sells NFTs today would have to write it's own payment management and treasury code, the worst case being funds are left exposed in the operational contract. Tomorrow in a post **Open Block EI on WAVES** world the same dApp upgraded with a few lines of code to leverage **[Open Bank](http://www.blockstarlogic.com/obei/pages/open_bank.html)** would now be able to easily integrate WAVES DeFi projects without sacrificing dApp focus. 

### Programme Duration?
The grant funded duration of the programme would be 4 plus 6 weeks.

The initial 4 week onboarding period would cover:

- Training Course development - This course would be designed to cover training in project management, development and testing with a focus on the WAVES Ecosystem
- Team Recruitment - The new team resource pool would be recruited from grassroots communities
- Team Training  - The team would be trained in project management, development and testing on WAVES
- Team Orientation - The team would be oriented on BSL delivery standards and process

The 6 week delivery period would cover for Open Bank and Open Roles respectively:

- Project Design - this would cover code and test design 
- Project Development (Coding) - this would cover code, and test development
- Project Testing - this would cover deliverable testing
- Project Documentation - this would cover project documentation and reviews 

### Resource Requirements for this Grant
The resource requirements for this grant would be the following:
| Project Task |  Allocation* | 
|-------|----------------|
|Community Recruitment | 11.36%|
|Community Workshop Series Design & Build |15.91%|
|Community Training Delivery | 15.91%|
|Project Design & Development | 27.27% |
|Project Testing | 20.45% |
|Project Documentation | 9.09%|

Total Resource Requirement 2372 WAVES

#### WAVES Official Support
To support the development the programme would request access to a dedicated WAVES Foundation assigned development support resource, to assist with technical queries as they arise..

### Ecosystem Fit

In terms of “Enterprise” alternatives at present these are predominantly in the “permissioned” and “private blockchain” space. In terms of “Commons” development the [Filecoin Ecosystem](https://fundingthecommons.io/) is currently making assertive efforts in this area, however these would be complementary to our endeavours. In terms of the Open Block EI vanguard projects there are several banking projects such as [sol bank](https://solbank.app/) however this is focused on a **shared wallet model** as opposed to a **non-custodial banking model**. 

## 🔩 Development Roadmap 
The table below describes the development road map for the **Open Block EI on WAVES** programme. 

**NOTE** no work has been commenced.

### V0.1 Development 

|Milestone | Project Task to Be Achieved |
|-------------|----------------------------------------|
| A | Project Agreements in place | 
| B | Open Block EI on WAVES Recruitment Drive |
| C | Open Block EI on WAVES Workshop Preparation |
| D | Open Block EI on WAVES Workshop Series Delivery | 
| E | Block Star Logic Team Orientation |
| F.1 | Open Bank on Waves Project  Design |
| F.2 | Open Roles on Waves Project  Design |
| G.1 | Open Bank on Waves Project  Development |
| G.2 | Open Roles on Waves Project  Development |
| H.1 | Open Bank on Waves Project  Testing |
| H.2 | Open Roles on Waves Project  Testing |
| I.1 | Open Bank on Waves Project  Documentation | 
| I.2 | Open Roles on Waves Project Documentation | 

The timelines associated with this roadmap will be dependent on funding agreements. 

## Additional Information ➕
The following additional information will give some insights into the Open Block EI project 
[Open Block EI](https://www.blockstarlogic.com/obei/)
[Open Bank](https://www.blockstarlogic.com/obei/pages/open_bank.html) 
[Open Roles](https://www.blockstarlogic.com/obei/pages/open_roles.html)

**Comment by BlackTurtle123** [comment]
Hello we recently had a FG meeting and wondered some things:
- You mark everything with completed, is everything already done?
- If so who is the team?
- There is no website linked
- Very short unclear application, checkout sign-art for example
- We need more details why the money is needed

**Comment by BlockStarLogic** [comment]
_Hello_, 

_Please see our response below and advise_ 

Hello we recently had a FG meeting and wondered some things:

You mark everything with completed, is everything already done? 
**No work has been commenced. We are still in the proposal stage. Milestones have been provided as requested for illustrative purposes.** 

If so who is the team?
 **As mentioned the team for this proposal the team will be recruited and therefore new. A side objective is to help grow the WAVES community by introducing new contributors.**

There is no website linked - 
**https://www.blockstarlogic.com/obei** 

Very short unclear application, checkout sign-art for example 

We need more details why the money is needed  - 
**we can host a call to discuss the project and any specific proposal amendments required.**

**Comment by BlackTurtle123** [comment]
> _Hello_,
> 
> _Please see our response below and advise_
> 
> Hello we recently had a FG meeting and wondered some things:
> 
> You mark everything with completed, is everything already done? **No work has been commenced. We are still in the proposal stage. Milestones have been provided as requested for illustrative purposes.**
> 
> If so who is the team? **As mentioned the team for this proposal the team will be recruited and therefore new. A side objective is to help grow the WAVES community by introducing new contributors.**
> 
> There is no website linked - **https://www.blockstarlogic.com/obei**
> 
> Very short unclear application, checkout sign-art for example
> 
> We need more details why the money is needed - **we can host a call to discuss the project and any specific proposal amendments required.**

Please, checkout the sign-art application and make adaptations like them.
The WA decides grants in a decentralized matter, so we only work with updates psoted here.
Milestones are unclear and marked with completed, no clear explanation why the money is needed,.. without adapting your application we can't evaluate it.
Thanks in advance.

Regards

**Comment by BlackTurtle123** [comment]
@BlockStarLogic Please rework your application.
If not reworked we will deny and close in 1 month.

**Comment by BlockStarLogic** [comment]
Application has been updated

**Comment by BlackTurtle123** [comment]
Hello!
We discussed the application and we still don't understand what you are trying to do.
Also for businesses WEST is more fit.

As consequence we will close the request.
