### ISSUE TITLE
SettleClick.com - The Paypal Button for the Waves Blockchain [Track 2. Web3.0 Development Grant] 

### ISSUE THREAD

**Issue by PascalParvex** [Waves-Association/grants-program#52]
Proposer: Introduce yourself (name, surname)
Hi, my name is Pascal Parvex, I have been working with the Waves Ecosystem since 2017, first got active on the Blockchain in 2013.

Contacts: Your email or telegram handle
Email: parvex@parvex.org, Telegram: @PascalParvex
Github username: Your Github login
PascalParvex

## 👥  Team 

Are you applying to implement the grant as an individual developer or do you represent a team?
I represent a Team. Me, the project lead, and ESP Softtech Pvt Ltd
Are you a startup or an ongoing business? (in case applying as a team or startup)
Startup

What’s your team or startup name? What is a website? (in case applying as a team or startup)
The main website is Parvex.org, the project website will be found here: SettleClick.com

Team members (in case applying as a team or startup)
Name of team leader
Pascal Parvex
Names of team members
ESP Softtech Pvt Ltd

Team experience (in case applying as a team or startup)
Please describe your (team/startup) development experience and technological stack?
I for myself have had some programming experience since the mid-1990ies have launched four Tokens on the Waves blockchain, which all sold out. ESP Softtech Pvt Ltd, which will be responsible for the code, has six years of experience in the Blockchain space.

Do(es) you(r) (team/startup) have experience in using Waves technologies?
I have run and administrated WavesPlay.com, a Waves blockchain game site for several years and have four years of experience working with the Waves blockchain. ESP Softtech Pvt Ltd is not specialized in Waves tech, but my developer beforehand also wasn't but was able to adapt fast, as Blockchain experience was already there.

Please attach your (team/startup) portfolio (projects you’ve been involved in)
Tokens eFranken, eKaulitz, KHADD and Bitcoin Speed.

Team website
https://Parvex.org

Team Code Repos
Code is closed source but can be made open source if necessary.

## 🔍 Overview

Please describe your solution idea by the following structure:

- Short description of the solution you suggest
Customers come to the site to create a payment button/link for Waves tokens

- How does it solve the specified problem?
If someone wants to offer payment for any item on their website/store in any of the Waves tokens, they don't have an easy way to create a payment button/link.

- How you will integrate this project into Waves / Gravity / Neutrino.
The customers paying with a click on a button/link created on SettleClick.com will use the Waves blockchain, through Waves Keeper and/or Waves Signer.

- Why your team is interested in creating this project.
I would like to support Waves, as it is my favorite blockchain. Also, I would use the website myself for my merchandise.

- What is the target audience of the final solution?
Shop owners, sellers of digital or physical items online.

- What is the “secret sauce” of it?
To create a payment button/link, there is no need to log in or pay a fee. Just fill a form and copy the generated link.

- What is the duration of the whole project?
2 months
- Resources required to implement the grant task
I already got everything, including hosting and domain.

### Ecosystem Fit

Are there any other projects similar to yours? If so, how is your project different?
I am not aware of a similar project.

## 🔩 Development Roadmap 

**Step #1**: Getting hosting and domain name

- SettleClick.com is already registered
- Hosting for the finished website is ready

**Step #2**:  Design of the website

- Layout design
- Logo design
- Button design

**Step #3**:  Coding

- Create the code for the easy to use button/link generator
- Testing of the site
- Deployment

**Step #4**:  Promotion

- Create a promotion plan
- Run promotion for two weeks

Within this application we are requesting funding with a total cost of 3000 WAVES:

- Creation of SettleClick.com website, including layout, logo, buttons and salaries: 1750 Waves
- Running expenses for five years: 750 Waves
- Promotion: 500 Waves

KPIs:
- A few dozen link creations per month as soon as the marketing campaign concludes.
- A few hundred views per month

### Overview

- **Total Estimated Duration:** Duration of the whole project
Two months
- **Total Costs:** Amount of Payment in Waves for the whole project. The total amount of funding needs to be not more than 100k Waves.
3000 Waves

## Additional Information ➕

There is always a need to be able to easily create a payment button/link if you want to sell something, and/or broaden your customer base.

Breakdown of how the website would work if someone surfs to it to create a payment button/link:

1. Enter the Waves address, where the payment should go.
2. Choose a token in which the payment should be in a search field that accepts token ID.
3. Enter amount.
4. Choose one of three button designs, or, as a fourth option, "Link only".
5. Click "Create".

**Comment by PascalParvex** [comment]
Added a breakdown of how the form would work under "Additional Information".

**Comment by BlackTurtle123** [comment]
Hello @PascalParvex 
1) We miss a detailed break-down for each step.
2) Your website doesn't work
3) We don't see the added benefit compared to the examples already available by the waves developers. https://docs.waves.tech/en/building-apps/how-to/assets/payment

**Comment by PascalParvex** [comment]
The website does not work, because I registered it only to reserve it. Somehow I am not ready anymore to invest around 20K Waves out of my own pocket to just get no support for it whatsoever...

**Comment by w0utje** [comment]
what's the issue? please clarify?

**Comment by PascalParvex** [comment]
This is the amount I invested to get WavesPlay off the ground.

**Comment by BlackTurtle123** [comment]
We gonna close the issue since there is no interest atm.
Also the amount of funds is to high, check our earlier feedback
