### ISSUE TITLE
Decentralized OTC and multichain multisig wallet

### ISSUE THREAD

**Issue by kot-begemot** [Waves-Association/grants-program#65]
- **Proposer:** Max Zab
- **Contacts:** max.zab@whalesheaven.com
- **Github username:** kot-begemot

## 👥  Team 

- Are you applying to implement the grant as an individual developer or do you represent a team?
  We are applying as a team of 4 professionals. 3 developers and 1 designer.
- Are you a startup or an ongoing business? (in case applying as a team or startup)
  We are a startup
- What’s your team or startup name? What is a website? (in case applying as a team or startup) 
  WhalesHeaven - is a non-custodial cross chain swaps / decentralised OTC (atomic swap model)
  WH Cypher - multichain multisig wallet
  https://whalesheaven.com
  https://whalesheaven.com/whcypher

### Team members  (in case applying as a team or startup)

- Name of team leader
  Max Zab

- Names of team members
Max Zab
Alex Pereverzev
Leonid Tkachenko
Andrew P.

### Team experience  (in case applying as a team or startup)

- Please describe your (team/startup) development experience and technological stack? 
Max - Full stack developer, 10 years of commercial experience. Max holds comprehensive knowledge of various blockchain protocols and a good understanding of various cryptography algorithms. 
Alex - Backend/mobile developer, 6 years of commercial experience. 
Leonid - Frontend/React developer, with 4 years of commercial experience.
Andrew - Designer/Frontend developer, with 2 years of commercial experience. 

- Do(es) you(r) (team/startup) have experience in using Waves technologies?
We don't hold a deep knowledge of Waves protocol. We very deeply understand Bitcoin and Ethereum and have a good understanding of some other blockchain protocols. We have a good understanding of EdDSA cryptography.
- Please attach your (team/startup) portfolio (projects you’ve been involved in) 
Cross chain swaps/Decentralized OTC - https://whalesheaven.com
Multichain multisig wallet - https://whalesheaven.com/whcypher
Citowise Wallet (project is inactive, Max was CTO) - https://www.circle.com/blog/usdc-ecosystem-spotlight-usdc-crosses-300-million-in-market-cap-and-has-support-from-nearly-100-companies
Technical advisory for Guarda wallet - https://news.bitcoin.com/guarda-wallet-launches-multisignature-functionality-for-bitcoin/
- Team website
https://whalesheaven.com

### Team Code Repos

- https://github.com/kot-begemot
- https://github.com/PereverzevAlex
- https://github.com/Leonid-18
- https://github.com/CloudberrySoup

## 🔍 Overview

If this application is in response to a public task then please indicate this on the first line of this section.

Please describe your solution idea by the following structure:

- Short description of the solution you suggest
We launched a non-custodial crosschain swap/decentralized OTC - WhalesHeaven. Currently we support Bitcoin, Litecoin, Dogecoin, Bitcoin Cash, Ethereum + ERC20 tokens and  Binance Smart Chain + BEP20. We plan to add more blockchains. This will let Waves users buy/sell Waves coin and Waves based tokens directly with Bitcoin and other coins/tokens, without registration and get their funds right on the chain.
WH Cypher is the first wallet that provides multisigs for Bitcoin, Ethereum, Litecoin, Binance Smart Chain and other blockchains in a single wallet. We rely on latest cryptography to provide simple and smooth user experience. Multisig schema that we are using does not require any chain specific setup and can be used for any kind of transactions.

- How does it solve the specified problem?
Our DEX will let Waves users buy/sell Waves coin and tokens directly with Bitcoin and other coins/tokens, without registration and get their funds right on the chain.
Our wallet will let Waves users/projects to hold a group control over Waves coins and tokens.

- How you will integrate this project into Waves / Neutrino.
We will first add a Waves adapter into our multichain multisig wallet. This will Waves users to control various waves assets - coin and tokens. Then we will add Waves adapter to our decentralized OTC platform. In the future users will be able to control NFTs and even to group sign any arbitrary transactions, including web3 support.

- Why your team is interested in creating this project.
We want to support as many blockchain ecosystems as possible. We can see that Waves association does a great job in spreading awareness of Waves technology and we believe this is a great chance for us to prove a fit for our solutions. 
We also want our multichain multisig wallet to be seen as a goto solution for organisation of control over crypto funds among blockchain projects and institutional players. 

- What is the target audience of the final solution?
Cross chain swaps/Decentralized OTC: 1st user group - tokens community members that want to buy/sell Waves coin/tokens for BTC, LTC, BCH, ETH, stable coins on other blockchains and so on; 2nd user group - token/project founders and institutional players who wants to buy/sell tokens at specific volumes for BTC, ETH, etc. There are some other use cases where our DEX solves user's pain points.
Multichain multisig wallet: 1st user group - joint control over funds (institutional players, blockchain related companies, token treasuries), 2nd - buyers/seller on WhalesHeaven DEX. There are some other use cases that we plan to cover in the future version of wallet like web3 support - a multisig equivalent of Metamask, that will let users to jointly execute arbitrary transaction like control of DAO smart contracts, transfer of NFTs and so on.

- What is the “secret sauce” of it?
Our DEX is based on multisignature wallets and does not rely on 3rd party blockchain. It is currently the closest solution to atomic swaps.
Our multisigs are based on Threshold signature scheme and look like a single user transaction on blockchain. Here is an example of transaction signed jointly by 2 users on Binance Smart Chain
https://bscscan.com/tx/0xa27757a9be02c18666900ff019de404ceeffe56d424d54701700ba1c5a619e01

- What is the duration of the whole project?
We will add Waves support in 1.5-2 months time and in >= 1 months to our DEX.

- Resources required to implement the grant task
We have all required expertise within our team. One thing that will be very helpful is a security audit from an external company. These are additional expenses that are good for security. We will appreciate any help from the Waves Association or Waves community.

### Ecosystem Fit

Are there any other projects similar to yours? If so, how is your project different?

WhalesHeaven has numerous advantages over existing competitors. Firstly - we let people trade p2p. This lets us provide our DEX as a trading platform for any coin/token community, regardless whether they have a small or large turnover. Secondly - every token/coin project at some point is asked for OTC trades and currently there is no place where such trades can be made in a decentralized way. Thirdly - we provide a multichain multisig wallet, which we believe will be a very popular tool for storing corporate funds in financial organisations dealing with crypto.

Our DEX will let Waves users to buy and sell Waves coins/tokens for Bitcoin, Litecoin and other currencies. But a bigger advantage for Waves ecosystem will be a decentralized cross chain swap through which Waves tokens/DeFi projects will be able to attract liquidity from other blockchain ecosystems.

Additionally, Waves assets (coin, tokens, NFTs) could be controlled in a corporate manner with our multichain multisig wallet. We plan to add web3 support. This will allow a joint control over DeFi operations natively, without a complex chain specific setup. 

## 🔩 Development Roadmap 

This section should break out the development roadmap into a number of milestones. It helps to describe the functionality we should expect, plus how we can check that such functionality exists in the product. Whenever milestones are delivered, we refer to the roadmap to ensure that everything has been delivered as expected.

- We will add a Waves adapter to out multichain multisig wallet - 1.5 month
- We will test the integration - 2 weeks
- We will request a security audit (optionally, external company) - 2 weeks (this is additional expenses, may be omitted, but good for security)
- At this moment users will be able to group create Waves addresses, store Waves based assets and transfer them. Transaction will look like a single user transaction.
- We will add Waves coin and tokens to our DEX and test the integration - 1 month
- We will be monitoring Waves ecosystem for newly created coins and will be offering them a free listing - 6+ months

### Overview

- **Total Estimated Duration:** Duration of the whole project
Development: ~2.5 month
- **Total Costs:** Amount of Payment in Waves for the whole project. The total amount of funding needs to be not more than 100k Waves.
Integration into wallet: 25 000 USD
Integration into DEX + listing Waves tokens: 25 000 USD

## Additional Information ➕

Any additional information that you think is relevant to this application that hasn't already been included.

Our multichain multisig wallet is available as Google chrome extension without code obfuscation. This is where the whole magic happens.

Additional information:

- Documentation of core components, protocols, architecture etc. to be deployed
[FROST: Flexible Round-Optimized Schnorr Threshold Signatures](https://eprint.iacr.org/2020/852.pdf)

**Comment by BlackTurtle123** [comment]
Hello, we have got some questions:
- How are you going to do the multisig?
- Can you give a breakdown for milestones and more detailed funding details, for what are the funds used?
- Can you provide user statistics from the wallet?
- What are the centralized parts, and what are decentralized parts?

**Comment by kot-begemot** [comment]
Hello,

**How are you going to do the multisig?**
Waves is based on EdDSA and ed25519 curve. We will implement [FROST TSS schema ](https://eprint.iacr.org/2020/852.pdf) within our wallet.

In very simple words it works the following way: all participants generate their own private keys, then they derive their respective public keys and share with others. The group public key is literally a sum of participants public keys. When they need to sign a transaction they calculate their individual share of r and s values of a signature. This way they literally can just sum up their signature shares and get a group signature.

The advantage of it is that group does not expose their wallet participants to the world and transaction cost is the same as if that was signed by a normal private key. So, it looks like a single user transaction in blockchain explorer.  This way a group of signers can sign literally any kind of transaction.

**Can you give a breakdown for milestones and more detailed funding details, for what are the funds used?**

- We will implement EdDSA for ed25519 - 2 developers + 1 cryptographer (external) - 1 month of work
- We will implement Waves adapter for our wallet - 2 developers - 2 weeks of work
- We will test the integration. Will make sure that Waves coin and tokens can be received and sent - 1 developer/tester - 2 weeks of work
- We will request a security audit - 1 developer - 2 weeks. If there will be any suggestion from security auditors, we will implement them.
- We will release an updated wallet version with Waves for public use. Will be collecting feedback and bug reports - 2 people - continuous process
- We will add Waves support to our DEX - 2 developers - 2 weeks
- We will test Waves integration - 1 developer/tester - 2 weeks
- We will be monitoring Waves ecosystem for newly created coins and will be offering them a free listing - 1 non-technical + 1 developer - continuous process

Along the whole development process we will also be collection feedback and will be updating our UX/UI of both wallet and DEX. Any feedback or feature requests coming from Waves Association of Waves community will be prioritized.

Requested funding will mostly cover development time and token listing.

**Can you provide user statistics from the wallet?**
We don't have that many users up to date, since we launched recently and we covering only 1 platform, however we are actively spading the word among crypto users and our organic traffic is growing.
<img src="https://user-images.githubusercontent.com/780077/160849365-28e90fbc-9963-4e25-9d47-ae75ea251af5.png" width=30% height=30%><img src="https://user-images.githubusercontent.com/780077/160849442-c5cf8c8f-60f2-4574-94ec-1d5d0decbbfe.png" width=30% height=30%>
~~~text
Organic website users             Organic web store users
~~~

**What are the centralized parts, and what are decentralized parts?**
Wallet decentralized parts:

- Key share generation - generated on user side
- Key share storage - Stored on user side
- Signature share generation - generated on user side
- Wallet backups - by default this is submitted to our server in encrypted format, only seed owner can't encrypt it. Can be disabled in settings. Wallet backups can be exported/imported manually. 
- Wallet recent activities/spending history - Same as above

Wallet centralized parts:
- Wallet generation session server - wallet users need some environment to exchange session messages. This messages do not expose any information to 3rd party. Session server is just a temporary message exchange media. It has a very simple API and we will open source in shortly. 
- Signature generation session server - Same as above
- We DO NOT collect user analytics in our wallet

DEX decentralized parts: 
- Login - User sign in via wallet. User signs a message that contains current time stamp and domain name.
- Top up wallet generation - User generates a 2-of-2 multisig with platform. Platform acts as a second user in this process,  with some UX sugar. 

DEX centralized parts: 
- Website domain and UI
- Hosted wallet - It stores key shares on our side. 

In the future we want to move to decentralized verifier setup, where we won't be storing key shares at all.

**Comment by BlackTurtle123** [comment]
Hello!
The project is currently to small compared to the asked budget.
For now we have to deny it, you can always reapply with an updated application when the time is there.
