### ISSUE TITLE
Waves Malaysia Club DeFi Party 2022 [Track 2. Web3.0 Development Grant] 

### ISSUE THREAD

**Issue by drihsanmy** [Waves-Association/grants-program#68]
- **Proposer:** Introduce yourself (name, surname) 
Muhammad Ihsan Bin Khalib Jaafar (KingCrypto)
My Name Service https://kingcrypto.bit.cc/

- **Contacts:** Your email or telegram handle
saudagar.my[at]gmail[dot]com

- **Github username:** Your Github login
drihsanmy

## 👥  Team 

- Are you applying to implement the grant as an individual developer or do you represent a team?
Sekolah Kripto on behalf Waves Club Malaysia

- Are you a startup or an ongoing business? (in case applying as a team or startup)
On Going Business (Sekolah Kripto) to bootstrap Waves Club Malaysia

- What’s your team or startup name? What is a website? (in case applying as a team or startup)
Sekolah Kripto 
https://linktr.ee/mysekolahkripto

### Team members  (in case applying as a team or startup)

- Name of team leader
Muhammad Ihsan Bin Khalib Jaafar

- Names of team members
Azim Zahari
Abi Syazwan

### Team experience  (in case applying as a team or startup)

- Please describe your (team/startup) development experience and technological stack? 
Sekolah Kripto is an organisation aims at educating the Malaysian community about Blockchain & Crypto Asset technology since 2017 using the Malay language. For practical reasons, Sekolah Kripto is co-operated as a business entity called Saudagar Training Enterprise (SSM No. : 003007367-X).

- Do(es) you(r) (team/startup) have experience in using Waves technologies?
Yes.

We have been involved in community empowerment program via youtube channels, telegram, twitter space and book publication.

- Please attach your (team/startup) portfolio (projects you’ve been involved in) 
Youtube videos :
a)Neutrino tutorial : https://www.youtube.com/watch?v=x5J14RVNWGs
b)Swop.fi tutorial : https://www.youtube.com/watch?v=F4uBPWgG82E
c)Wx Pool	: https://www.youtube.com/watch?v=J_bvZrutjIM 
d)Book Publication : WAGMI (ISBN no. : ISBN: 9789671977613
e)Physical course at International Islamic University Malaysia on 20th February 2022

- Team website
https://linktr.ee/mysekolahkripto

### Team Code Repos

a)Neutrino tutorial : https://www.youtube.com/watch?v=x5J14RVNWGs
b)Swop.fi tutorial : https://www.youtube.com/watch?v=F4uBPWgG82E
c)Wx Pool	: https://www.youtube.com/watch?v=J_bvZrutjIM 

## 🔍 Overview

Please describe your solution idea by the following structure:

- Short description of the solution you suggest
This proposal paper is prepared to request for event budget from Waves Association Grant to conduct a Waves promotional program entitled “Waves Malaysia Club DeFi Party 2022”.

- How does it solve the specified problem?
Blockchain & DeFi technology adoption is increasing in Malaysia. However, the exposure of Malaysian community towards Waves DeFi & Blockchain is very minimal. A physical face-to-face Waves DeFi course for key participants as well as public members of Malaysia blockchain community from other projects will:

1.To increase exposure and thus, cash inflow towards Waves, Waves.exchange & Wx Pool by the Malaysian community.
2.To provide target audience with practical hands-on on how to use Waves Keeper, Waves.exchange web wallet, Wx Invest mobile wallet & Waves.exchange mobile wallet.
3.To educate on benefits of staking as well as to instill decentralization spirit in the heart of the target audience.

- How you will integrate this project into Waves / Neutrino.
By providing hands on and follow up session to the community about Waves technology, we could provide bidirectional end user feedback on Waves product & services

- Why your team is interested in creating this project.
Severe lack of Malay language education tools on Waves Technology

- What is the target audience of the final solution?
a)Existing Waves user who lacks knowledge on Waves DeFi technology
b)NFT community in Malaysia since they make money from flipping NFT but lack experience to diversify the income in Waves income
c)Malaysian regulated exchange like Mx Global , Luno & Tokenize to increase legal adoption of Waves in Malaysia
d)Other members of blockchain community in Malaysia such as the Ethereum & BNB community.

- What is the “secret sauce” of it?
Sekolah Kripto is among the best source of referral for Malaysian community when it comes to Blockchain tech. We also have done a similar paid project in 20th February 2022 with huge sucess.

- What is the duration of the whole project?
1 day, 8 hours in total.

- Resources required to implement the grant task
a)An auditorium for the course.
b)58 Waves for participant to learn how to use waves (116 participant)
c)14 Waves for contest & competition
d)2 security personnel
e)10 facilitator
f)10 general assistant
g)2 trainer
h)1 Website
i)1 designer for logo , promotional vidoes
j)25 T-shirts for community members
k)Stationary costs
l)3 meals for 116 participants

### Ecosystem Fit

Are there any other projects similar to yours? If so, how is your project different?
No. We would be the first in the Malaysian sphere to conduct a physical party/ course on Waves.

## 🔩 Development Roadmap 

This section should break out the development roadmap into a number of milestones. It helps to describe the functionality we should expect, plus how we can check that such functionality exists in the product. Whenever milestones are delivered, we refer to the roadmap to ensure that everything has been delivered as expected.

**Step #1**: 
- Establishment of Waveslubmalaysia.[domain] website

**Step #2**:  
- Identification of trainers & facilitators

**Step #3**:  
- Identification of third party event management company to handle non training related ground activities

**Step #4**:  
- Distribution of invitation to key participant (like representatives of 
local exchanges in Malaysia: Mx global, Luno, 
Other blockchain community : eth.kl, etherscan, coingecko
NFT community : Pentas.io
Tech companies : amanz.my )

**Step #5**:  
- Identification of participant via lucky draw & quizzes

**Step #6**:  
- Advertisement via social media & local media companies

**Step #7**:  
- Booking the place for event

**Step #8**:  
- Running the course.
8.00 a.m. – 9.00 a.m.		Registration & Breakfast
9.00 a.m. – 10.00 a.m.		Module 1 : Introduction to Blockchain & Waves Coin
10.00 a.m. – 11.30 a.m.	Module 2 : Buying Waves with Fiat & Trading on Centralized Exchange
11.30 a.m. -12.30 p.m.		Module 3 : Activating Waves Wallet
12.30 p.m. - 1.00 p.m.	Module 4: Introduction to Waves Gateway
1.00 p.m. - 2.00 p.m.	Lunch
2.00 - 3.00 p.m.	Module 4: Waves, Neutrino & LP staking.
3.00 p.m. - 4.30 p.m.	Module 5: Wx Pools & Waves DEX
4.30 p.m. - 5.00 p.m.	
Wrapping up & AMA session
5.00 p.m.	Tea & End of Session

**Step #9**:  
- Post mortem

### Overview

- **Total Estimated Duration:** Duration of the whole project
4 Months

- **Total Costs:**
Malaysian Ringgit 40,000 or 325.20 Waves

## Additional Information ➕
Estimated Attendees:
30 key participant from strategic organization such as Pentas.io, Etherscan & Coingecko.
70 public participant to be selected on a first apply first reserved basis.
10 facilitators.
3 representatives from International Islamic University Malaysia.
2 event organiser.
1 Trainer.

Possible additional information to include:

We are more than happy to present our idea in the form of Ask Me Anything. We are committed to expand the community understanding about Waves Blockchain technology

**Comment by BlackTurtle123** [comment]
Hello!
We are missing the detailed costs breakdown, for each step/milestone we would like to have this budget, why you need this money, what are your costs etc.

**Comment by drihsanmy** [comment]
Dear sir, we have a bit of difficulty to present our proposal on github using the provided template.

Allow us to present our proposal in a pdf format as below : [https://drive.google.com/file/d/1noxeY6BH3Dtoxh6R1OI8qJzDfZPdSurp/view?usp=sharing](url)

We have revised the proposal in accordance to community feedback and latest Waves rate. Thank you.

**Comment by BlackTurtle123** [comment]
Hello!
We are willing to grant it.
If we got the summary correct you need 228 waves? 
We would need a summary at the end, and some evidence and pictures.
@Hoshingen would also like to request 5 bonus t-shirts.

**Comment by drihsanmy** [comment]
Dear sir.

At the time of application, 228 waves equals to MYR44,000  (10,000 USD). At current rate, 228 Waves equals to MYR14,800. Hence, there is a significant budget run if we run the program with the said budget.

We would like to request a budget equivalent to the said fiat value. 

Otherwise, can we run the program with 228 Waves? Yes but it will be a very stripped down project.

Yes, without doubt we will provide a post event report.with pictorial evidence.

Yes we can accomodate the t-shirt.

Your kind consideration of the above matter is highly appreciated

**Comment by drihsanmy** [comment]
Update 30 April 2022

We spoken to our good friend from WX Booster.
They have agreed to contribute additional:
500USDN, 7500 WXB & 1 Waves.

As part of the discussion, we will consider WXBooster , along side Waves Association Grant Program as the sponsor for the program. We will also distribute WXB and Waves to the participants.

With the 228 Waves coming from Waves Association Grant Program, it would be enough for us to run a proper program for 50 people, with adequate funding for marketing as well.

Thank you and looking forward!

**Comment by drihsanmy** [comment]
With reference to current exchange rate, the cost would be **USD 10, 196.09**

**Comment by drihsanmy** [comment]
REPORT ON WXBOOSTER BEST DEFI IN WAVES ECOSYSTEM COURSE

PDF version accessible : https://bit.ly/reportwxbcourse

Introduction
WXBooster : Best DeFi in Waves Ecosystem Course Multipurpose Room, IIUM Academy, International Islamic University Malaysia, Gombak, Malaysia on 6th August 2022. It is a physical course which was also streamed live on multiple platforms such as Youtube and Twitter. The event started at 8.00 a.m. and concluded at 5.00 p.m. (GMT +8). The objective of the event is to increase awareness on Waves Blockchain technology, particularly on Wxbooster among the Malaysian community.

Organizer
The event was organized by Waves Degen Malaysia. It was supported by Sekolah Kripto, Wxbooster and individuals such as KingCrypto, Hanyluz, Princess Waves 8085.eth, & Rasamoto. No event management company hired. Saudagar Training Enterprise was the proxy company used to handle payments and purchases on behalf of Waves Degen Malaysia. 

The course was delivered by Dr. Muhammad Ihsan Bin Khalib Jaafar & Hanyluz. Technicalities was handled by Abi Syazwan while marketing and development was managed by Azim Zahari. 

Participation
32 person & 4 facilitators have registered to attend the course. Unfortunately, the actual participation is 25 participants & 3 trainers. Demographically, participants come from various academic and occupational background, with age ranging from 19 to 55 years old. All participants are Malaysians, with the furthest participant coming from Kedah, Malaysia, which is about 424 KM from the training centre. A large portion of the participants have been involved in Crypto Asset related activities such as Non Fungible Tokens (NFT) and other Blockchains such as BNB chain. In addition, several Faculty of Information Technology university students from Politeknik & Tenaga National University have also attended the course.

157 viewers watched the event online. A copy of the livestream can be accessed via
9 AM - https://youtu.be/r7BthSrMeqI
11 AM - https://youtu.be/kstTnhSPFsY
2 PM - https://youtu.be/LeZPbdHRMZ4
3 PM - https://youtu.be/IvpW9YJTx6w (Livestream error)

Event Flow 
The actual event flow is as follows :
Registration : 8.00 am
Introduction to Blockchain : 9.00 am
Introduction to Cosmos Waves Chain : 10.00 a.m.
Waves on Centralized Exchange : 11.00a.m.
Lunch Break: 12.30 p.m.
Waves Wallet : 2.00 p.m.
Wx Liquidity Provider Pools : 3.00p.m.
Wxbooster : 4.00 p.m.
End of course : 5.00 p.m.

Financial & Non Financial Implications
Waves Degen Malaysia DO NOT receive any formal grant from any organisation. However, individuals have contributed to the success of the event, with an estimated 1500 USDN was collected / used. The contribution is as follows:
Wxbooster : Food , venue, emolument for trainers
Sekolah Kripto : Goodie bags, WAGMI Books
Princess Waves : T-shirts for participants
Terza monsterhunt.org : NFT certificate for participants
King Crypto : Quiz prizes and consultation, WAGMI Books
Hanyluz : Technical experties, consultation, WAGMI Books
8085.eth : WAGMI Books
Cryptobilis : Quiz prize (T-shirt for quiz)
Rasamoto : Consultation

The final financial implication in Malaysian Ringgit is estimated to be about MYR65000. 

Objective Achievement
Participants was assessed on their understanding of the content of the syllabus via verbal and visual assessment. 8 participants were randomly but individually assessed on their understanding of various aspects of Waves Blockchain such as transaction fee, swapping coin, LP pools, Wallets as well as Wxbooster process. They were incentivised to focus during the session by providing gifts for correct answers, such as Limited Edition Waves Degen Malaysia Mug, Cryptobilis T-shirt and Waves coin. Based on our assessment, participants were able to answer more than 90% of the question asked correctly.

Pitfalls
Despite the organiser’s best effort, the program fails to get 100% attendance. Besides, the participations from university students were also lower than anticipated. However, community participation was better than expected. A number of registered participants also did not turn up for the event.

Conclusion
Wxbooster : Best DeFi in Waves Ecosystem Course was successful Thus it is hope that similar event could be conducted in the future. Pictorial report is attached to this document as Appendix A.
