### ISSUE TITLE
Project Food Forest Sardegna - Food Forest Token - Resource Based Economy

### ISSUE THREAD

**Issue by robertomarini** [Waves-Association/grants-program#7]
- **Proposer:** roberto marini
- **Contacts:** info@pec.foodforestsardegna.com Telegram username DeuSeuDeu
- **Github username:** robertomarini

## 👥  Team 

- I am applying individually on the behalf of the team members of the project that, as well as me, doesnt have direct developing knowledge wide enough to create the tech needed for the expansion of the project inside the blockchain ambient, and so we have the need to receive cooperation from expert developers of  Waves. 
-  The project created an founded individually from myself, using my Living Trust Roberto Marini throught my own legal entity business Bac Revolution, is an on going activity based on the first model of "economy based on resources" i have developed , and is actively manifested in Sardegna, with a dedicated e-commerce prototype for online activities for example. Everything is already working on a voluntary base, as in here, physically, we didnt needed to use technologies to make all the project work, however, right now, we feel the urge to share all with the world, and improve our own structure and activity for making easier to achieve mass adoption.
-  The team is simply called the Food Forest Sardegna Team, the dedicated websites are : www.foodforestsardegna.com ; www.foodforesttoken.site ; https://foodforestsardegna.gitbook.io/ ; 

### Team members  

- roberto marini team leader
- team members right now are deciding to keep their participation private in order to be protected from the team leader

### Team experience  

-  I have been involved into dedicated activities online since from 2014, mostly business related, to acquire the needed experience and knowledge to express my talents and inner wisdom. The blockchain technology became one of my major points of interest in 2015, after becoming a merchant accepting Bitcoin as payment method for my own products and services, that escaleted quickly into a deep connection with the blockchain tech as a whole. Since than i have been actively using cryptos and by now the Waves platform provided me the most warmth and easy way to help others using the tech and tools offered from it. 
-  I do have experience of the Waves technologies from 2018, experience that grown overtime in 2019, and in 2020 became a daily habit for me to use Waves based techs, especially with tokenomics and the powerfull tools offered within the platform for communities etc. 
-  Im not a believer of old patterns repeating themselves if they arent useful, and so all my own personal experiences, accumulated over time, created the Wisdom i needed to become fully aware of how to implement my knowledge of everyday life activities into potential technological sharing, to make anyone benefit from the awareness i have obtained in my journey. My core and main activity , called Bac Revolution, is the foundation of everything, an educational system to allow anyone who wish to get concious about human potential as a whole, on how to use methods of reality manifestation, using  the most higher technology available in the universe, conciousness. "The Revolution Is Within You!" is the ebook i have created to allow anyone interested in knowing what the Bac Revolution really is, and can already be acquired from [the dedicated e-commerce store](https://secure.equacoin.cash/italy/store/bacrevolution/), created inside the Equastore Italia, or inside the **_full shop_** of my activities at [https://bac-revolution.sumup.link/](https://bac-revolution.sumup.link/) . Connected to it, i have created TrafficServicePro, a social media marketing agency and online services provider, decentralized on blockchain, that has its own token issued inside the Waves Platform (that unluckely got bashed down in the token rating site, because few envy users made fake weight volume with votes, just because of my association with the [Equacoin Project](https://equacoin.store/), another Waves based project that is fully operative) , and the online e-commerce shop can be found as well inside the Equastore Italia, [at its dedicated link](https://secure.equacoin.cash/italy/store/trafficserviceproequastore/) , and inside the full shop some services are available as well. Both websites of Bac Revolution and TrafficServicePro are now unavailable due to major changes i have decided to make since the old service provider in which i've built them is no longer serving my purposes, and i would like to make the websites become dApps, but since they were just merely home pages for target the traffic to the e-commerce shops, there isnt any sort of issue about it, as all the traffic is now getting generated directly to the shops. Right now the most attentions and focus , is all concentrated on [Food Forest Sardegna](https://foodforestsardegna.gitbook.io/) the project i want to really become well know to the Waves team, as it is something that will drastically increase the relevance of the whole Waves Ecosystem. The [Food Forest Token](https://foodforesttoken.site/) created inside Waves.Exchange, is already up and running, and it will become a driving force in our resource based economy , more and more each day, as the whole ecosystem, has been designed, created and manifested since from 2012, and nowadays thanks to the blockchain tech we are able to expand the concept and benefits of what a resource based economy is to the whole world. The actual capitalistic economy is over, is done, dead, not able anymore to survive into a universe where only real things are accepted. Money must serves humans, and not the opposite. Food Forest Sardegna , based on Sardegna, is a real life example of what self sufficiency means, and how to implement it with daily life activities. The online e-commerce is already up and running, and [can be found here](https://secure.equacoin.cash/italy/store/foodforestsardegna/) inside the Equastore Italia, and the products can be also found inside the full shop. The Food Forest Sardegna project is just a starting point, as the indipendence of the Nation of Sardegna will be announced worldwide before the end of the year, as full Native indigenous people, we have the right to self govern ourselves. 
- https://foodforestsardegna.gitbook.io/ , https://foodforestsardegna.com/ , https://foodforesttoken.site/ 

### Team Code Repos

- There are no repositories as for now. I am more focused on practical actions and activities needed to make the real project work properly and without limitations of any sort. Aside from that, there will surely be the need of a dedicated team member that has its occupation onto this topics (repositories and such). 

## 🔍 Overview

Food Forest Sardegna Project
Introduction to the sustainable approach to nutrition, using permaculture and food forest gardening models for self sufficient fruits and vegetables production. FoodForestToken EcoSystem: The 1st blockchain food forest development project, ruled by community values and ethics.

With the tokenization of a real life need, nutrition, putting into the equation the most productive, sustainable, healthier and fun way to permanently cultivate the soil with permaculture and food forest gardening principles, using the real economy based on that particular daily life habit, we are able to achieve easy and fast crypto mass adoption behaviours from the human population since eating is a basic need that can't be avoided of being taken care of, and so, becoming the most easier and faster way to help to spread crypto awareness and at the same time practicality of use.

• The core focus of the project is eradicate hunger, by creating a fully duplicable system, accessible worldwide with no limitations of sort, to learn and apply the techniques and how to use the tools needed for creating and enhancing a permanently productive food forest and permaculture gardening model;

• Making a fully decentralized dApp, for allow anyone worldwide able to see live streaming permaculture and food forest real life activities, to learn in the best way how to apply the knowledge shared inside the dApp tools, making also dedicated membership areas, full of detailed video tutorials on "how to" for everything that is needed to know before to start a journey into food forest gardening and permaculture activities and so much more;

• Having the possibility to receive financial support from worldwide human beings, focused into high purposes projects, that want to help the core team to acquire new lands and also revitalize abandoned gardens and natural lands;

• Making healthy and ethical foods being delivered directly to the people that need them the most, and also for the people that have the desire and need of buying them for eating in the most natural and ecological way possible, making also the growers able to create a sustainable flow of currency to enhance even later on the whole system;

• Using a dedicated token to receive resources created within the ecosystem, create local economy closed loop cycles for self sufficiency, obtain direct ownership of the produced resources from lands acquired from Food Forest Sardegna, with the ability to have instant payments made using the token, and also an effective currency to be traded on the market to benefit from tons of other crypto projects;

The project is already integrated with Waves (as the token itself is issued inside of the ecosystem) and Neutrino (main source of reference for acquiring the token and support the project) as clearly explained inside its [white paper](https://foodforestsardegna.gitbook.io/educational-library/2/white-paper) . It is benefitting already from the powerful protocol of Neutrino, creating an immediate interest for all the new comers that are getting to discover the Food Forest Sardegna project, as the Food Forest Token has been connected with Neutrino USDN and EURN since from the early stages of the process, and the whole concept behind the protocol gets explained to all the new food forest sardegna partecipants (yes, free advertising, and of the best quality, real human interaction). 

Waiting for a more developed Gravity protocol, able to connect with the Stellar blockchain, the exchange of food forest tokens will start to take place with a fully developed Indonesian community, Diruna (DRA token), that has been able to create a very similar methodology inside their local economy , as i am directly connected, on a personal level, with the Diruna community. The Food Forest Token aims to become a meaning of understanding, to all those who really have understood the power of Tokenization, and why it is important to become aware that centralized issued money (such as fiat money privately created ex nihilo from banks) are not able to solve ANY real human life need. Only when fiat legal tender is issued directly by the people, becomes useful, and banks get back to their jobs, intermediaris! The topic is vast and it wouldn't be possible to discuss about it in here. I want and wish that from the Waves association there will be enough dedication related to this topics, as they are crucial for our time, as this point of our history, in its cycle, is clearly showing what major shifts are needed worldwide. 

The target audience of the final solution is at first the whole population of Natives of Sardegna, next to be the whole Italian citizens, and next, the whole world, simplifying the expansion based on continents. For this reason, it should be kept in mind that the main 2 languages to be used, are English and Italian at least in the beginning. Following next, as much languages will be available, the better and faster results will be gotten. 

The secret sauce of the whole project is connected to the induced value of the ecosystem, using a new concept of understanding, that makes resource based economies practical and manifested, as they are the only solution to this distopy going on about neoliberism and capitalistic societies, that are just destined to go exstint like dinosaurs. Resource based economies are real, truthful, and most of all, they are alive. They aint dead numbers on a screen, and they cant be controlled by centralized entities or political perversions. 

The whole project is going to be a permanent activity, that will grow over time, making space to new ways of living, with or without external support, as the Natives of Sardegna will lead change with example. 

What is needed the most, are dedicated developers, that truly feel the urge within, to create a better world and make sure that the future generation will have the possibility to live! Right now we are at a turning point, very straight forward, in which ones chooses to either live or die. Food Forest Sardegna is Life. The perfect solution would be a dedicated blockchain, with nodes able to run directly from the smartphones of the users that will just need to hold a certain amount of Food Forest Tokens to keep the form of a "master node" like, creating a very easier and accessible way to partecipate in the highest decentralization seen on the planet, and all those acting as such, will receive the amount of tokens directly with an airdrop, after have passed a dedicated verification in order to prevent frauds of any sort, or even better, creating a dedicate smart contract for making possible to lock a certain amount of tokens at least into a specific number of wallets, to never make that liquidity being moved . All should be mobile friendly, with applications able to run on all devices, and especially as explained above, with a particular attention to make everything accessible world wide, without barriers or limitations of any kind. A dedicated wallet would become the most easiest way to increase the speed of adoption, as making it fully mobile friendly with easy and basic functionalities will allow anyone to have in hand all that is needed to receive, send, exchange and store the Food Forest Token. A vital tool needed will be the Electronic Time Stamp feature to allow all the partecipants to validate documents for direct contracts occurred between the parts, in relationship with the acquisition of new lands etc, as the Food Forest Token will have a multiple series of functionalities as soon as its network starts to increase. And this is something that will need to be very carefully taked care of. The Food Forest Token can serve multiple purposes, as its a polyhedric currency. 

### Ecosystem Fit

From what i know, there arent any kind of projects with the same structure, and there are not even similar ones. What is similar, and this is becoming a trend as you all know, are the e-commerce shops online and the tokenization itself. So what makes my project differentiate itself from everything else, is the whole concept integrally, and the fact that is already realized, in real life. It just need the dedicated IT infrastructure within the blockchain techs. With or without it, we, the Natives of Sardegna, are and will be doing it anyway! :) Cooperation is Life and the evolution, competition is death and involution. Cant be explained any clearer than that. Precluding this opportunity would just increment karmic debt for those who denied it, while we kept going for realize it bigger, better, and stronger, directly in real life, and not just "digitally". 

## 🔩 Development Roadmap 

1) Having a dedicated developers team that is able to create: all the infrastructure needed to make the dApps as explained inside the white paper; the dedicated wallet in all its versions(web, desktop, mobile etc); a dedicated blockchain (as its considered the most powerfull way to create immediate trust for the community of Natives) able to run if possible directly on mobile phones, if not with a more "traditional" way, forking for example the waves blockchain. 
The costs for this type of work, cant be quantified by myself as each dev should be first of all able to connect with me, and understand if it is qualified or not for the tasks, and how much income is needed for each of them to work on it, and complete all in a already choosed time frame;
2) Having the ability to acquire the lands and different resources needed to speed up the whole perma cultivation process and food forest gardening expansion on the whole island territory thanks to the grant received as per white paper;
3) Creating a direct strong connection within the Neutrino and Gravity Protocol to expand the whole ecosystem to its maximum levels;
4) Creating liquidity pairs for Food Forest Token, using Swop.fi for example, and also making market makers programs inside Waves.Exchange;
5) Making real life activities to expand the conciousness of the whole project worldwide , thanks to all the possible tools available and developed over time, to increase interconnectivity; 

Every part of the process will be showed inside the [https://foodforestsardegna.gitbook.io/educational-library](https://foodforestsardegna.gitbook.io/educational-library) , and at every major step achieved, official social media announcements will be made, making possible for everyone to know it. 
For this reason, is needed a full dedicated brainstorming activity, with developers, so that i can be able to provide all the dedicated informations that they will ask to receive, for developing all the tools and tech that Food Forest Sardegna deserves.

### Overview

- **Total Estimated Duration:** The project will be permanently active, and the faster we get all in place for its tools and tech needed, the faster the devs will be able to end their jobs, needing to simply check from time to time if everything is working ok.  
- **Total Costs:** To create all the value needed for covering developing costs, and also keep achieving the whole white paper steps, with the actual waves price on the market (being 6€ approx. per token), would be 50'000,00 Waves (for the white paper steps), while the amount needed to pay the devs is yet to be calculated, as already explained above, however knowing a maximum of 100k waves grant, there would be another 50'000,00 Waves available to be used for that specific reason. 

## Additional Information ➕

For any information needed, is possible to connect directly with myself in telegram, username @DeuSeuDeu (roberto marini) , via email at info@pec.foodforestsardegna.com , and check the dedicated official telegram channel of the project at [https://t.me/FoodForestSardegna](https://t.me/FoodForestSardegna) . 

The initial amount of fiat currency that was needed to activate the whole process, was consisting in 500'000,00€ , that i have personally created ex nihilo, benefitting from the unilateral contract of the GST Virtual Bank, active in the Italian territory, that has been used to acquire the house and garden (as explained in the white paper) to become my first house and the core location for the daily life activities of the core team members. This has been possible thanks to the Waves tech, using the Electronic Time Stamp function contained inside the Equacoin wallet, that allowed me to validate the banking affidavit of value transferred , making the whole purchase process legally binding for the parts involved, and that is still getting completed, as the whole pubblic institution organizations were needed to be fully informed on how to properly save all the datas, documents etc, and how the intermediary banks had to act for account the sum transfered created ex nihilo, which is still in the process to be completed due to their long timings of activity and bureaucratic. 

The whole project is based on a the Universal Declaration of Human Rights and the United Nation Declaration of The Indigenous People Rights, and the Island of Sardegna will soon be declared again as Nation, worldwide, from the ONU, as it is meant to be. As for that, we , the Natives, will be fully able to benefit from the GstVirtualBank (more details can be found at [https://gstvirtualbank.com/](https://gstvirtualbank.com/) activity, making fiat legal tender creation a common practice world wide. 

Thanks a lot for your time! Hoping in a faster cooperation, to make the whole process start smoothly and quickly, i wish you all the very best from Life, and for this Human experience, we are all together part of! 

A si biri! roberto marini

**Comment by KardanovIR** [comment]
Hey, Waves Association Grants & Funding working group reviewed your application and did not recommend your project to the Waves Association board.

Here are feedback and recommendations on what you can do before the working group will re-evaluate your application:

Feedback:

- The application does not disclose project team members and makes it impossible to evaluate tech skills and knowledg
- Lack of details on expenses and expected results
- Lack of tech details to evaluate. There is only a website with no implementation detail
- Vague and too broad scope

Recommendations:

- Add expenses breakdown
- Describe smaller milestones with smaller scopes
- Share team details and contacts
- Add more technical details on how the project will actually work

**Comment by robertomarini** [comment]
Team members arent in any way tech people, they are those who create and enrich the resource based economy we have in place here, working already without any tech implementation aside from the basics techs given (waves exchange wallet, equacoin wallet etc), the knowledge they all have is real life experience on self sufficiency and sustainability, it has nothing to do with techs or IT knowledge, reason why it was clearly explained that a dedicated team of Devs has the duty to create the techs needed for speed up the mass adoption of the token connected to the activity. Their details to be shared would be their general informations, such as full name , date of birth etc and it isnt something that has anything to do with the techs to be developed. This may even happen, if they consent to share those details, however right now they arent in any way a need for your side as the legal entity having full responsability of the project is myself, Roberto Marini. 

All the costs to be covered are explained inside the white paper, linked inside the proposal, explaining for what those cost has to be covered, while the devs payments is impossible to be determined by myself as already stated since the techs to be developed arent of the area of competence i have to be operating with, thus meaning the total amount was to be self determinated responsably from the devs themselves. The expenses can be disclosed more in details with a dedicated business plan for example, showing all the cost resources related, and why they are already showed inside the whitepaper, something that wont be surely showed inside a Github section. It is something that can be shared and discussed when seriously the Waves Association head quarters realize what is their duty in here. 

The tech needed has been easily explained as it is needed a forked proprietary blockchain, from  the waves one, a dedicated dApp for integrate a live streaming and membership area webspace, to give full sharing of the whole activity and methods, a dedicated mobile/web/desktop wallet for sending receiving exchanging staking the foodforesttoken and and ETS tool for documents certification. Thus allowing the integration with Gravity, and making Neutrino a tool for all waves community to benefit from real life resource based economies that will create real collaterals for the protocol, since the native has the ability to issue EUR fiat ex nihilo , and also with the national new currency going to be disclosed in the coming months after the whole banking infrastructure will be fully operative as well as the print house for the legal tender national cash. 

There is not only a website, there is also a library, going to be filled with more contents over time and in multilanguages, a dedicated e-commerce shop fully integrated with the equacoin project and an entrepreneurial active interrelationship between the Bac Revolution business as well as the TrafficServicePro service provider, there is also a whole nation with its natives, inside the island territory, cooperations already in place and active between multiple local associations, making all the project being alive and fully operative within its territorial space, and much more, as already showed (food forest token website, dedicated telegram channel and so on), so i feel useless to point out again what is already being presented and available.

The implementation is nothing hard to get, a decentralized resource based economy working firstly internally to the nation within its island territory, to next be exported as way of economics everywhere else in the world. The scope is clear and set, not vague or too broad, inside the white paper it is the core foundamental information given : "The core focus of the project is eradicate hunger, by creating a fully duplicable system, accessible worldwide with no limitations of sort, to learn and apply the techniques and how to use the tools needed for creating and enhancing a permanently productive food forest and permaculture gardening model;" if thats something that cant be handled from devs holistically, is another thing. We are doing it already by eradicating it locally at first, reaching the whole island nation. And we wont stop here. Italy and Europe are the next step, and we will go beyond that with direct cooperation with the United Nations. 

The milestones are connected simply to the techs to be developed, as the real life activities presently being achieving what is allowing the whole natives of the nation to fully manifest to the world their sovereignty , both popular sovereignty and territorial sovereignty, are already ongoing and are unstoppable already from 2012, and especially with a culmination of self-determination the 3/12/2020 , day in which the Statute of Sardegna has been proclaimed and notified , consigned and accepted, from the indigenous forum of the United Nations, the Italian prime minister Conte, and the President Mattarella, and also to the presidency of the Sardegna ex region, obtaining its own protocol number and dedicated set of informations being sent to the dedicated government departements. 

So as said, the only milestones to be achieved are the proprietary blockchain, the dApp, the wallet etc, all things tech related. We are real people in a real world, doing daily activities for enriching the whole ecosystem, and making real manifestation of a decent way of living, we dont spend our time in front of a computer as much as it is needed for develop techs, we really cannot right now, as there are real life activities to be made outside. People eat foods, not codes. May sound mean, however is straight truth. We want a decentralize system to share all with the world, and allow everyone else to benefit from the same level of existence we achieved and that is evolving overtime ascensionally. Generously. 

The project is already working, and is based on what can be seen from the contents given already, and with a direct visit within the lands. More contents will be delivered soon , unfortunatly still having to use old ways of sharing, because until the dApp isnt built, as we have to keep accessing actual social media tools for doing it, meaning a lot of informations cant be shared, we value our privacy and we refuse to keep using those tools given from the system as they arent meritocratic and respectful.
