### ISSUE TITLE
WavesIncome.org - A global income for every human - [Track 2. Web3.0 Development Grant] 

### ISSUE THREAD

**Issue by PascalParvex** [Waves-Association/grants-program#71]
Proposer: Introduce yourself (name, surname)
Hi, my name is Pascal Parvex, I have been working with the Waves ecosystem since 2017, first got active on the Blockchain in 2013.

Contacts: Your email or telegram handle
Email: [parvex@parvex.org](mailto:parvex@parvex.org), Telegram: @PascalParvex
Github username: Your Github login
PascalParvex

## 👥  Team 

- I mostly just propose the concept of a Universal Basic Income. As I am no coder or designer, appropriate developers need still to be assigned. But I can help with organization.
- This would be a startup
- My proposed domain for the project is WavesIncome.org, registered by me for this cause. Empty right now.

### Team members  (in case applying as a team or startup)

- Name of team leader
Pascal Parvex
- Names of team members
To be found

### Team experience  (in case applying as a team or startup)

- Please describe your (team/startup) development experience and technological stack? 
I for myself have had some programming experience since the mid-1990ies and have launched four tokens on the Waves blockchain, which all sold out.
- Do(es) you(r) (team/startup) have experience in using Waves technologies?
I have run and administrated WavesPlay.com, a Waves blockchain game site for several years and have four years of experience working with the Waves blockchain.
- Please attach your (team/startup) portfolio (projects you’ve been involved in)
Tokens eFranken, eKaulitz, KHADD and Bitcoin Speed. And WavesPlay, which is offline, but a thread with information and screenshots can be found here: https://bitcointalk.org/index.php?topic=5201877.0
- Team website
My website is Parvex.org (in overhaul).

### Team Code Repos

No code exists yet.

## 🔍 Overview

Please describe your solution idea by the following structure:

- Short description of the solution you suggest
A decentral Waves stake to fund a universal income, so every human on earth can get a source of income.
- How does it solve the specified problem?
By staking an initial fund of Waves, which will grow through donations and unspent UBIs
- How you will integrate this project into Waves / Neutrino.
With a smart contract.
- Why your team is interested in creating this project.
The concept of a universal basic income has fascinated me for years.
- What is the target audience of the final solution?
Every human on earth.
- What is its “secret sauce” of it?
The advantages of the Waves blockchain, like speed, low cost, and also for the environment. And data oracles to determine the world population once every month, so the project's fund income can be divided through it; unclaimed UBIs for the month get reinvested in the fund. Donations will be welcome to grow the staking fund; For this, the smart contract should automatically convert incoming funds with a value into Waves. Humans who have verified their identity can opt in and out of the monthly Waves payments. The website would display the amount of the last UBI paid on the first of the month, like "$0.0254 UBI for May 2023". You have to start somewhere. Good viral marketing would make it attractive for big money to donate to the fund to better the world, greatly benefitting the adoption of the Waves blockchain.
- What is the duration of the whole project?
I would say half a year.
- Resources required to implement the grant task
This is twofold: Funds to develop the project and initial funding of the stake.

### Ecosystem Fit

- Are there any other projects similar to yours? If so, how is your project different?
There are other UBI projects on other blockchains, but those are more complicated to handle and do not profit from the advantages of the Waves blockchain.

## 🔩 Development Roadmap 

As mentioned above, I provide the concept, but can't provide the development of the project. But I can help with organsation.

### Overview

- **Total Estimated Duration:** 6 Months
- **Total Costs:** 20 000 Waves.

**Comment by BlackTurtle123** [comment]
Please stop the money grab and token printing. You are wasting our time. Please checkout decent projects #14 for correct project setup. 20K Waves is crazy money.

**Comment by PascalParvex** [comment]
Hi Bram,

No, this is not a money grab. And no, I was not talking about "token
printing", but if you had read my proposal, you would know this. And if in
your opinion an unconditional income is wasting your precious, precious
time, this tells more about you than me.

Pascal

Am Fr., 29. Apr. 2022 um 14:36 Uhr schrieb Bram N. ***@***.***

**Comment by BlackTurtle123** [comment]
Hello Pascal,
This is the FG opinion.
Have a nice day.
Regards

**Comment by PascalParvex** [comment]
Hi Bram,No hard feelings,PascalAm 11.10.2022 um 10:25 schrieb Bram N. ***@***.***>:﻿
Hello Pascal,
This is the FG opinion.
Have a nice day.
Regards
