### ISSUE TITLE
CRUZO - The first NFT greeting card & crypto gifts multi-chain Web3 platform.

### ISSUE THREAD

**Issue by modus77** [Waves-Association/grants-program#74]
- **Proposer:** Introduce yourself (name, surname) 
   Denis Stepanov
- **Contacts:** Your email or telegram handle
   contact@cruzo.io 
- **Github username:** Your Github login
   https://github.com/modus77

## 👥  Team 

- **Are you applying to implement the grant as an individual developer or do you represent a team?**
  Cruzo team

- **Are you a startup or an ongoing business? (in case applying as a team or startup)**
  Startup

- **What’s your team or startup name? What is a website? (in case applying as a team or startup)**
  Cruzo Cards
  https://cruzo.io
  https://cruzo.cards

### Team members  (in case applying as a team or startup)

- **Name of team leader**
  Denis Stepanov

- **Names of team members**
  Roman Bobrik
  Nikita Korshunov
  Jane Makey

For development, at least two more contributors will be involved to work on the product.

### Team experience  (in case applying as a team or startup)

- **Please describe your (team/startup) development experience and technological stack?** 
JavaScript, HTML, CSS, Git Python, TypeScript, Node.js, Docker, React, Go, Nginx, Figma, Web3, PostgreSQL, Redis, Vue, React
ethers.js, Web3-react, Solidity

- **Do(es) you(r) (team/startup) have experience in using Waves technologies?**
   Not yet

- **Please attach your (team/startup) portfolio (projects you’ve been involved in)** 
**Web3:**
https://alium.finance/ - development [web3, react, styled-components, thegraph, node.js], 
https://redpanda.game/ - frontend development [web3, react, emotion], 
https://dashboard.fragma.net/ - backend development [nest.js, postgres, gcp storage], 
https://app.orica.io/ clone - backend development [nest.js, postgres, redis, ipfs, ethers.js]

- **Mobile apps:**
App and server-side: iOS: https://apps.apple.com/us/app/dab-pumps-app/id1465714463 
Android: https://play.google.com/store/apps/details?id=com.dabpumps 

- **Web and server-side:** https://vipgroup.ru/ 

- **Mobile apps:** 
iOS: https://apps.apple.com/us/app/aicar/id1446068511 
Android: [https://play.google.com/store/apps/details?id=ge.aicar.app&hl=en_US&gl=U](https://play.google.com/store/apps/details?id=ge.aicar.app&hl=en_US&gl=US)

- **Team website**
   https://cruzo.io/

### Team Code Repos

- https://github.com/cruzocards
The project's final code is being kept non-public (except smart contracts)

## 🔍 Overview

Please describe your solution idea by the following structure:

- **Short description of the solution you suggest**
The first NFT greeting card & crypto gifts multi-chain Web3 platform. Bringing a billion-dollar industry to Blockchain. Our mission is to advance the mass adaptation of NFTs through a revolutionary greeting cards and gifts marketplace. Cruzo will combine the benefits of owning a niche platform in the NFT space for creators while serving a billion-dollar market requiring millions of on-chain transactions.

- **How does it solve the specified problem?**
Ownership of digital content (greeting/postcard) - NFT as solution
Utility for digital greeting cards - Collectable, Secondary Market
New hype on greetings (new format) - NFT Greeting stories for a young audience (mobile-first)
Reduce time on searching a selection - AI smart event-manager
Onboarding for Crypto/NFT newbies - gift greetings without a wallet
Cryptocurrency as a gift - gift a bitcoin in an original way
NFT gifts for Metaverse - Marketplace for party goods in Meta
Engagement - providing gamification in the greetings industry (gift2earn)
Ecology - we move greetings and postcards to Web3

- **How you will integrate this project into Waves / Neutrino.**
Cruzo is using Waves Protocol and its tools (API, Keeper, Signer, Explorer) as a service for decentralized data storage and secure encrypting tooling.

   We will use Gravity Protocol as a bridge to other networks, such as Ethereum and BSC, to connect different credentials from external providers.

   Neutrino with its stablecoins can be used by clients to provide payments in $USDN.

- **Why your team is interested in creating this project.**
People have already moved many things to Blockchain. We want to move greetings/postcards We believe it's the right time to start a movement in this industry because NFT, Cryptocurrency, and Metaverse are booming. And the trend continues, not looking at "crypto winter"

- **What is the target audience of the final solution?**
We are targeting: 1) Users (seekers) - who are hiring greetings cards to express emotions or feelings with the recipient.  2) Creators  - who are looking for sustainable income on a daily basis. They are hiring a platform to sell more artworks realized as greeting cards.  3) Business owners or Marketers - who are looking for ways to increase customer loyalty or sell more gift cards.  4) NFT collectors - who are looking for something different (understandable) instead of crypto punks or apes.

- **What is the “secret sauce” of it?**
Uniqueness. We are first NFT marketplace for greetings, crypto gifts, and digital party goods in history. We also the first Web3 project with Gift2Earn rewards program   

- **What is the duration of the whole project?**
8-12 month

- **Resources required to implement the grant task**
Granting for product development and brand marketing. Advisory support from Waves Node and DevRel teams. Marketing support. PR support.

### Ecosystem Fit

**Are there any other projects similar to yours? If so, how is your project different?**

Web2: American Greetings, Hallmark, Moonpig, Evite, Paperlesspost. American Greetings have a very strong position on the market, but they do not provide NFT for their customers.

Web3: OpenSea, Rarible, Airnfts. OpenSea is a leading marketplace for NFT, but they are for all types of content.

We are building a niche marketplace for NFT cards, crypto gifts, and party goods for Metaverse. Positioning together with Blockchain technology will give us an undeniable advantage. Greetings cards can be collectible NFTs, gifts can be crypto gifts, and digital NFT party goods can be used in Metaverse.

## 🔩 Development Roadmap 

|  | Milestone 1 | Milestone 2 | Total |
| - | - |- | - |
| Estimated Duration | 60 d | 45 d | 105 d |
| Full-time equivalent (FTE) | 4 | 3 | 7 |
| Cost | $ 16,000 | $ 12,000 | $ 28,000|

#### Milestone 1 — MVP of the Product

| Number | Deliverable | Specification |
|-|-|-|
| 0 | Smart Contracts | We will develop the following smart contracts: ERC1155 token which represents a greeting card collectible, Marketplace contract to enable users with opening and closing trades, ERC1155 token factory to allow users to create their own collections. |
| 1 | Indexers | We will launch indexers to propagate information from our smart contracts to the other services, e.g. backend app. |
| 2 | Backend | We will create a backend service that will provide API to handle frontend requests and will be integrated with our indexers to retreive information from our smart contracts. |
| 3 | Frontend | We will bring up a frontend part of the product that will provide basic NFT marketplace functionality: user account, minting process, catalog, item page, buying and gifting processes. |

#### Milestone 2  —  Marketplace features extension
| Number | Deliverable | Specification |
|-|-|-|
| 0 | Smart Contracts | We will add Timed Auction feature to our smart contracts. |
| 1 | Indexers | We will update indexers to provide more information to other services (backend app), including new Timed Auction specific events. |
| 2 | Backend | We will update our backend service to support Timed Auctions and new catalog (filtering, sorting options) and greeting card (metadata extension, categorization, multiple view options) details page functionality. |
| 3 | Frontend | We will add Timed Auction feature as well as implement new catalog (filtering, sorting options) and greeting card (metadata extension, categorization, multiple view options) details page functionality. The design will be updated in order to improve user experience. |

Within this application, we are requesting MVP development funding with a total cost of $28,000.00 

### Overview

- **Total Estimated Duration:** 3 month
- **Total Costs:** Amount of Payment in Waves for the whole project. The total amount of funding needs to not be more than 100k Waves.

   5500 WAVES

## Additional Information ➕

- Pitch Desk - https://cruzo.io/docs/CRUZO-Startup-Pitch-Deck.pdf
- Product development roadmap with key features and milestones - https://docs.google.com/spreadsheets/d/1OMTDHNIXpK58EkI-i-rYw1jMq7sWNobTZluxumfij70/edit?usp=sharing
- UX/UI product design - https://www.figma.com/proto/882kzjuN5y4Up5X9kGu2n7/cruzo-%E2%80%94-marketplace-(design)?page-id=95%3A33&node-id=686%3A10016&viewport=54%2C509%2C0.02&scaling=min-zoom
- Project website - https://cruzo.io/
- Band book - https://cruzo.io/docs/CRUZO-Brandbook-ENG.pdf
- Staging environment - https://front.alpha.cruzo.cards/
- Twitter - https://twitter.com/CruzoCards

### We are winners of 2 Hackathons
- Moonriver Hackathon (2nd place) - https://twitter.com/CruzoCards/status/1541336115424428032?s=20&t=WHEbF91ypu1IAs8giMWT_A
- Cronos Hackathon (2nd place) - https://twitter.com/NewsCronos/status/1483710839857336323?s=20&t=WHEbF91ypu1IAs8giMWT_A

**Comment by BlackTurtle123** [comment]
Hello @modus77 
Please check out #14 for a good example

**Comment by modus77** [comment]
@BlackTurtle123 Hello, thanks for the example and suggestion. We will update our application, but could you please comment. Do accept such projects like ours? Is our project/idea suitable for the waves grant program. If yes, we will update our application within next few days. Thank you!

**Comment by modus77** [comment]
@BlackTurtle123 Hello. We have updated our application. Please review. If you will have additional questions, please, feel free to ask. Thank you in advance

**Comment by BlackTurtle123** [comment]
> Total

Hello modus,
You are going to build a marketplace and count that people will integrate into it? Or you are going to build a metaverse yourself?

What makes your different from sign-art or https://puzzlemarket.org/?

We seen that you already have a token, on what chain is it? Is it already circulating?

We seen that your application runs on many blockchains, won't waves be lost between them all?

**Comment by modus77** [comment]
> > Total
> 
> Hello modus, You are going to build a marketplace and count that people will integrate into it? Or you are going to build a metaverse yourself?

Yes, we are building Marketplace. We don't have any plans to build own metaverse at this moment

> 
> What makes your different from sign-art or https://puzzlemarket.org/?
Our niche Marketplace is only for greetings, postcards, gift,s and party goods for Metaverse. 
 
> We seen that you already have a token, on what chain is it? Is it already circulating?

No, we don't have it yet. But we plan to create it before IDO

> 
> We seen that your application runs on many blockchains, won't waves be lost between them all?
We think the waves will take equal l place among other chains. Anyway we can always promote wawes by doing some collabs, partner marketing, drops and promotions.

**Comment by modus77** [comment]
Hi @BlackTurtle123 do you need something more from us?

**Comment by BlackTurtle123** [comment]
What metaverse will you be using since you will integrate waves, but not build your own metaverse?
We wonder what added value this niche marketplace will have without a metaverse
You are also talking about developing a ERC1155  token, but this is not even abailable on waves, so how can the marketplace be on waves without the nft on waves?

**Comment by modus77** [comment]
Hey, @BlackTurtle123 just forget. I agree with you, waves are not fit for cruzo.cards
