### ISSUE TITLE
HolyVerse and Waves Partnership for Disruptive Tech Grant

### ISSUE THREAD

**Issue by melfarra** [Waves-Association/grants-program#75]
Sam Elfarra
Sam@holynft.io 
melfarra
100,000-300,000 Waves (the max amount of what is shown on the WAVEs website)

## 👥  Team 

As a team for our Web3/Metaverse Startup: HolyVerse
We are an ongoing business with a ton of traction and users on our platform already. 
HolyVerse and our website it: https://holynft.io/

Team members  (in case applying as a team or startup)

Sam Elfarra (Co-Chief Executive Officer/Executive Chairman)
	Sam has a background in private equity, blockchain consulting and finance. Sam has worked on a number of NFT projects, all with humanitarian objectives. When Sam isn’t playing basketball, he’s sharpening his developer skills and helping people feel more comfortable in their community.

SONNY (Co-Chief Executive Officer/Operations Officer)
Sonny is an entrepreneur, influencer and content creator having started @realtalkstocks and a number of other objectives. Aside from his professional pursuits, Sonny’s passion lies with helping others become financially literate, with a focus on teens in marginalized communities.

Dixon (Chief Marketing Officer)
Content Creator/Entrepreneur based out of Rhode Island, currently studying Digital Media Production and Finance at New England Institute of Technology. Works primarily in Social Media Marketing, running a network of accounts amassing over 400k followers. 

MONTY (Chief Technology Officer)
	A seasoned mobile game, AR/VR/XR developer who has worked with Google, Disney, Samsung and others. Monty is passionate about creating amazing interactive experiences. His goal is to create incredible play to earn products that are just plain fun that keep you coming back for more.

BRITO (Chief Design Officer)
	A skilled 3D artist focused on hard surface modeling and texture painting. He has done work for a number of notable NFT projects. Marcos’s hobbies include cooking, jiu jitsu and playing video games. Having a comfortable life and ordering Japanese food everyday are his top priorities.

### Team experience  (in case applying as a team or startup)

All of that is stated above but we are very well versed on blockchain development, website building, game dev, and more. 
Our team does have experience using WAVEs. 
All of the previous projects we have worked on our here: 
Here is our team website: https://holynft.io/

Team Code Repos

(https://github.com/holyverse/holyverse)
It will be updated as we are developing out new projects during the bear market.

## 🔍 Overview

HolyVerse is a new web3 company focused on improving the lack of financial literacy that's exacerbated wealth and income inequality around the globe for decades. The Company is developing the first ever play-to-earn AND learn ecosystem that gives users a fun and lucrative way to interact in Web3, while also giving them the resources they need to use the biggest historical shift in wealth distribution to their advantage. 

The co-founders Sam Elfarra and Sonny Fazio, who have amassed almost 1m followers between their different financial education focused social accounts, have leveraged their early success to grow a vibrant HolyVerse community (230k+ Discord Members) that rivals the biggest Web3 projects on the market and sell out three separate HolyVerse character drops in a matter of minutes. HolyVerse has generated almost $4m in revenue in the last six months through these three NFT character drops, all of which are characters that will be used in their play-to-earn game that is currently under development. The game is being developed by the Team's lead engineer, Monty Guilhaus, a seasoned AR/VR/XR developer who has held roles at Google, Disney, Samsung, and others.  

The Company is also in the process of building out their learn-to-earn app, which allows users to earn tokens for completing educational courses on the new and confusing defi landscape. The Team believes that the best future is an equitable future, where resources and opportunities are available to everyone, irrespective of their upbringing, education level or network. HolyVerse is here to make this vision a reality. 

We intend on integrating the project exclusively with WAVEs if the partnership benefits us with funding and PR support. We will work to being the Decentraland or Sandbox of the WAVEs ecosystem. Our competitive advantage against every other Metaverse startup is the following: 

Utility tokens for each NFT character set 
Gasless transactions 
Mini-video games for each set
Charitable cause for each set 
Mobile social app
Educational newsletter
P2E metaverse acting as an interactive internet 
Developing projects Initiative 
Independent and exclusive NFT marketplace 
Staking 
All NFTs are made in-house 

Everything shown here is being developed or has already been created. Funding and a strong partnership will benefit HolyVerse in getting to market much faster and can ultimately help grow the WAVEs ecosystem. We will do everything in our power to make WAVEs reach the top 5 in cryptocurrency dominance. 

Duration of the entire project for building the current milestones is about 6-8 months. After that we will continue to update and replicate. The grant of 300,000 WAVEs equates to $2.1Mn USD at this current moment which would really help us. We are also looking to achieve our current milestones over the next 6-8 months then do a fundraising round. If we do team up with WAVEs this will only benefit them as you are supporting a large metaverse with real world utility and unique applications never seen before. With 100,000 WAVEs we will still be able to hit everything at the same rate in our milestones. More funding would just speed things up and get us to incorporate much more plans shown in our whitepaper below.

### Ecosystem Fit

There are not projects similar to ours. There are some competitors such as Decentraland or Sandbox but they do not have a gamified marketplace or larger amounts of scalability. HolyVerse is currently on the ETH blockchain but we are looking to make a change if given proper funding.  

## 🔩 Development Roadmap 

This development roadmap outlined below the staff and resourcing requirements needed to fulfill the previously discussed technical expectations of HolyVerse over the next 6-8 months.

The primary aspects of this are the shorter term milestones plan relate to:
1. The Breeding integration
2. Holy Game & Metaverse Build
3. App build

**Breeding**
Breeding will require either of the following options:
- 1x full time, experienced web3/solidity developer for roughly 4 weeks of effort. 
- 1x full time mid web developer and 1x full time solidity developer for approx 3-4 weeks effort. 
- Money from this also helps the second milestone
 ($50k)

**Holy Game Expansion & Metaverse Build**
The expansion will see continuously developed utility as well as marketplace and functionality additions. 
- 1x senior game dev w/blockchain experience
- 2x extra mid game dev
 ($450k)

**App**
For an educational app, delivered on both web and native iOS and Android, we would need:
- 1x temp iOS developer 
- 1x temp Android developer
($200k)

### Overview

The milestones will take about about 6-8 months given proper funding. We do intend on continuing to populate our metaverse more afterwards.

We are applying for the disruptive tech grant for 300k WAVEs. We are willing to accept less as a seed investment if needed. I am looking forward to hearing back and to potentially disrupt the tech world for the better together. Overall, we will work to bring WAVEs enough demand for it to reach that top 5 market cap crypto dominance. Our integration and exclusivity of HolyVerse along with the resources that WAVEs has to bring us to fruition will create a lot of market demand. 

## Additional Information ➕

Any additional information that you think is relevant to this application that hasn't already been included.

Possible additional information to include: 
Whitepaper link: https://drive.google.com/file/d/1RD5EM1TC7xngTBaBZhJsf4JpjBzhKWz5/view?usp=drivesdk
Mini-Video Game Demo: https://holynft.io/play
Staking Link: https://holynft.io/staking
Discord: https://discord.gg/krpawReDAw (sneak peeks channel includes a lot of designs) 
Twitter: https://twitter.com/HolyVerseNFT
TikTok: https://www.tiktok.com/@holynft?is_from_webapp=1&sender_device=pc

**Comment by BlackTurtle123** [comment]
Hello,
your budgetting is a mess.
You can't just ask an amount between 100-300k.
As this seems a very planned application, we will close it for now.
