### ISSUE TITLE
WeFund Terra migration to Waves

### ISSUE THREAD

**Issue by WeFundOfficial** [Waves-Association/grants-program#77]
[Litepaper WeFund 2.3.1 (1).pdf](https://github.com/Waves-Association/grants-program/files/8746993/Litepaper.WeFund.2.3.1.1.pdf)
What is the name of your project?

WeFund

2) What is the tagline for your project?

Community crowdfunding and incubation launchpad with a focus on real-world projects implementing blockchain in their existing model.

3) What product(s) or service(s) are you planning to launch, grow, or build with the support of SCF?

The projects on WeFund’s platform do all fundraising with stablecoins. In addition to this, all projects will have a dedicated smart contract that deposits stablecoin funds into the Nexo savings protocol to generate yield. WeFund does not touch any of the funds raised. Each project will also follow a milestone fund release system managed by smart contract. The project will determine a set of milestones (with the WeFund team) that when completed will be voted on by the project investors. If the milestone is approved, the next set of funds will be automatically released to the project team to complete the next milestone. If the milestone is not approved, all remaining funds will be returned to the backers. This makes the crowdfunding process 100% transparent, holds project creators accountable, and minimizes risk for investors. By using stablecoins, WeFund will be able to host projects built on other blockchains including Binance, Ethereum, Solana, and more. 

4) Attach images for the products/services section.
Attach file(s) 

5) Awesome! Now we’d like to collect some stats about your company or project. Your project/company has been in operation since:

October 1, 2022

6) Your project/company is based in:

Dubai, United Arab Emirates

7) Does your company have a specific region of focus or operation?
No

If yes: Select the region(s) of operation for your project/company 
[Northern Africa](https://en.wikipedia.org/wiki/North_Africa)
[Eastern Africa](https://en.wikipedia.org/wiki/East_Africa)
[Middle Africa](https://en.wikipedia.org/wiki/Central_Africa)
[Southern Africa](https://en.wikipedia.org/wiki/Southern_Africa)
[Western Africa](https://en.wikipedia.org/wiki/West_Africa)
[Caribbean](https://en.wikipedia.org/wiki/Caribbean)
[Central America](https://en.wikipedia.org/wiki/Central_America)
[South America](https://en.wikipedia.org/wiki/South_America)
[Northern America](https://en.wikipedia.org/wiki/Northern_America)
[Central Asia](https://en.wikipedia.org/wiki/Central_Asia)
[Eastern Asia](https://en.wikipedia.org/wiki/East_Asia)
[South-eastern Asia](https://en.wikipedia.org/wiki/Southeast_Asia)
[Southern Asia](https://en.wikipedia.org/wiki/South_Asia)
[Western Asia](https://en.wikipedia.org/wiki/Western_Asia)
[Eastern Europe](https://en.wikipedia.org/wiki/Eastern_Europe)
[Northern Europe](https://en.wikipedia.org/wiki/Northern_Europe)
[Southern Europe](https://en.wikipedia.org/wiki/Southern_Europe)
[Western Europe](https://en.wikipedia.org/wiki/Oceania)
[Oceania](https://en.wikipedia.org/wiki/Oceania)

8) Select up to three tags that describe your use case:
Remittances
Cross-border payments
Micro-payments
B2B payments
DeFi
NFTs
Lending
Yield
Wallet
Anchor
SDK
Market platform
Community
Education
Tool
Multi-currency savings
Securities
Financial inclusion
Payment processing
Payroll
Treasury management
Compliance
Gaming
Charity
Other:
Incubation
Launchpad

9) What is the stage of your project/company?

Select one: Development / Start-up / Growth / Expansion / Maturity

10) What progress have you made so far?

WeFund has already completed the MVP and is now implementing multi-chain features, payment with fiat that is converted to stablecoin, and integrating an email wallet for Web2 users. WeFund is registered in Dubai, however, leveraging blockchain and stablecoins, we are able to host projects worldwide. We initially raised $270,000 USD to develop our MVP, however, we lost a lot of traction with the Terra crash and now looking to develop on a new chain.

11) Where do you want to be in 6 months?*

In 6 months, we aim to have a fully functioning launchpad with a strong infrastructure and network for sustainable incubation. In 3 months, we aim to have 4 projects fundraising per months and 6-8 projects per month in 6 months time. In addition to this, we will continue to a strong effort to continue our community and user growth.

12) What will you do to accomplish this goal?*
  

Initially, WeFund was primarily focused on leveraging the Terra chain, however, with the failure of Terra, WeFund is rebuilding to be multichain platform to leverage various stablecoins and easily transition Web2 users to Web3
WeFund has a broker license in accordance with United Arab Emirates regulations. All funds are managed on blockchain and WeFund does not touch any funds raised. As regulations change in various regions, WeFund will remain agile to comply with any upcoming regulatory changes.
Yes, additional support or freelance assistance is welcome to help us rebuild and scale the business.

13) What funding do you need to get there?*

Small project scope < $5,000
Experimental or hackathon-style projects
Often has a single contributor

Medium project scope < $50,000
Development or launch of a new company or product
Single or multiple contributor(s)
Solves a real-world problem

Large project scope $50,000 - $200,000
Scaling or improving an existing company or product
Solves a real-world problem
Should already have users and be fully operational
Multiple contributors

Our goal is to focus on real-world projects that are looking to implement blockchain into their current model. This includes fintech, education, environmental, health tech, and more. We currently rebuilding our platform (from Terra) to be multichain and build an efficient system to bridge Web2 users to Web3 

14) Project body

There are many cases in which projects backed by investors have malicious intent from the start and do not operate in good faith, therefore, failing investors. The China Academy of Information and Communications Technology (CAICT) claims that only 8% of the over 80,000 blockchain projects ever launched are still active today. Furthermore, blockchain projects only average a lifespan of roughly 1.22 years. Additionally, a Wall Street Journal review of 1,450 documents for digital coin offerings unveiled 271 indicators of fraudulent tactics — including “plagiarized investor documents, promises of guaranteed returns, and missing or fake executive teams.”  To increase transparency, minimize risk, and hold projects accountable for the fundsraised, WeFund has a unique community vetting and unique milestone system. This means the WeFund community will, at each milestone of a project’s development, vote as to whether the relevant milestone has been achieved, with the outcome of such vote determining the release of funds required for the project to achieve its next milestone. For example, if a project is looking to raise $50,000, the project creators will need to identify a series of milestones and their respective expected costs (WeFund can work with the project creators on this). For this example, we can assume this project will need $10,000 for platform development, $20,000 for marketing, and so on... Every project will have a dedicated smart contract that automatically deposits funds raised into Nexo, a stablecoin savings protocol. The first $10,000 will be released to the project creator to complete its first milestone within a predetermined period. When the milestone is complete, the investors of the project will vote whether or not this meets their expectations. If the milestone is approved, the next set of funds, in this example $20,000, will be automatically released to the project creators. If the milestone is not approved, the remaining funds will be returned to the investors. With this system and the use of smart contracts, WeFund does not touch any of the funds raised and the entire fundraising process is transparent.

TARGET MARKET					
WeFund can host projects being built on any ecosystem. With this in mind, WeFund primarily focuses on projects that are looking to implement blockchain technology into an existing, real-world model. WeFund’s user base is mainly intermediate crypto enthusiasts looking to be early investors in crypto/blockchain projects that will not only have strong financial returns but have a meaningful impact. WeFund has a community of nearly 8,000 on Twitter and Telegram.
	
REVENUE MODEL		
Nexo Yield - WeFund does not take a fee or commission from the incubation and fundraising process. Instead, all yield generated from Nexo, a stablecoin savings protocol, will be for WeFund. So projects will get 100% of the funds raised. Nexo generates 12-15% APY.
Transaction Fee - There will be a 1-5% transaction fee charged towards project backers
Advertising (upcoming) - As WeFund scales, we will accept payment to push projects via social media and media releases. 
	

SALES FORECAST/FINANCIAL PLAN
[Financial Forecasts.xlsx](https://docs.google.com/spreadsheets/d/160gBqjDab5zxbnZUEbPaADqgSQBY8duw/edit?usp=sharing&ouid=111493337495540514297&rtpof=true&sd=true)	

				
INDUSTRY AND MARKET RESEARCH					
The Blockchain market size (TAM) is projected to grow from $4.9 billion in 2021 to $67.4 billion by 2026. The major driving factors contributing to the high growth rate of blockchain market include increasing venture capital funding and investment in blockchain technology; extensive use of blockchain solutions in banking and cybersecurity; high adoption of blockchain solutions for payment, smart contracts, and digital identities; and rising government initiatives. By WeFund’s estimation, blockchain impact on the real world would be ~75% of the TAM, or $3.675 billion (SOM). WeFund aims to achieve ~10% of the SOM or $367.5 million as an addressable market.

THREATS AND OPPORTUNITIES
WeFund has a broker license in accordance with United Arab Emirates regulations. All funds are managed on blockchain and WeFund does not touch any funds raised. As regulations change in various regions, WeFund will remain agile to comply with any upcoming regulatory changes. In addition to this, WeFund was previously building on the Terra blockchain as the crashed caused WeFund to lose most of its development traction. To counter this, WeFund is implementing a multi-chain system to diversify blockchain risk.

COMPETITION 
There are many launchpads available, and many successful ones, however, WeFund sets itself apart in several ways
Milestone fund release system managed by smart contract for 100% transparency, minimize risk for investors,  and hold project creators accountable.
Focus on real-world projects
Do not ask any fee or commission for incubation and funds raised. Projects do not pay any money to WeFund
Does not require users to hold WeFund’s native token to invest in projects
Multi-chain, stablecoin crowdfunding
Secure and refundable deposits if project fails during milestone
[Competitive Landscape.xlsx](https://docs.google.com/spreadsheets/d/1CXYt69zl2CdS8hnK4d5P9AhAMXPfsBQC/edit?usp=sharing&ouid=111493337495540514297&rtpof=true&sd=true)

MARKETING AND  SALES		
Strategic Partnerships - Establishing strategic partnerships with other launchpads, accelerators, institutional investors, exchanges, and more. These partnerships expand our network for the projects WeFund hosts, improves media coverage, and give the WeFund project more credibility. 

Social Media - WeFund is very active on social media platforms including Twitter, Telegram, Discord, and Medium. Twitter, Telegram, and Discord are efficient tools to make announcements and directly engage with our community. WeFund leverages Medium to self publish articles related to new partnerships and development updates in WeFund. Finally, WeFund leverages YouTube to publish video content such as AMAs with projects that will be on the WeFund platform.		

RESOURCES AND RELATIONSHIPS 
WeFund has established several notable partnerships that are vitale to WeFund’s growth and strong network 

14) Summarize your project (max ... characters)

WeFund is a community crowdfunding incubator for blockchain and real-world projects
built on various blockchains. WeFund has the capability to incubate and crowdfund diverse blockchain and real-world projects, bridging the gap between the real world and blockchain. In addition to this, WeFund is being developed to be a 360- degree incubation service for projects hosted on the WeFund platform through support and guidance before, during, and after funding has been completed.

17) Introduce your team

Andrea Bello
Co-Founder & CEO
He is the person behind the development of the Fan$quad smart
contract that was deployed on Col-4 during the Hackathon organized
by Terraformlab. He has a wealth of experience in coding, with a
deep understanding of C, C++, Javascript, VBA, Java, Python, Rust
languages (to name a few). In 2018 he moved his focus into Solidity,
PHP, & HTML 5, to follow his vision of creating advanced web3.0 applications integrated
with the blockchain. His role is to ensure the delivery of the smart contracts, web app,
and technical infrastructure. A serial entrepreneur, he built a Natural Mosquito Solution
based in Bali, a hotel & restaurant (Ristorante-Bar Lanca) in Switzerland, and a smart-
home startup designed to reduce electricity consumption.
https://www.linkedin.com/in/bello-andrea-380572b4/

Ika Afifah 
Co-Founder & CMO
A dynamic individual who worked at Tencent as an Operation Specialist, in the partnership division. Before Tencent, she was Senior Partnership Manager at Bigo, a Senior Account Executive position at one of the digital marketing agencies under Jet Group, and Manager at Waves, helping founders raise $1.2M in pre-seed funding. She is one of the founding partners and driving forces behind the concept of WeFund.
https://www.linkedin.com/in/ika-nur-afifah/

Achuth Chandran
CFO
Experienced financial professional and consultant. HEC Paris alumnus. ACCA Affiliate. With experience at KPMG, Sancta Capital and Trilogy Enterprises, Achuth has vast experience in the different avenues of corporate and investment finance. He currently leads Octave Advisory, a blockchain consulting firm based out of Dubai with the goal to help promote and expand the technology.
https://www.linkedin.com/in/achuth-k-chandran-b17880102/

Austin Taylor 
CCO
Comes from a background in investment and corporate finance. After completing his education he worked as a Business Analyst for Harman International in Seattle, Washington USA building AI applications to identify high-risk sale transactions. After this, he transitioned to Investment Management for Pegasus Tech Ventures located in Jakarta, Indonesia managing investment deals in the Southeast Asia region.
https://www.linkedin.com/in/austintaylor19/

18) Add below the url to the main website of the company/project. 

www.WeFund.app

19) Do you have a link to your code (e.g. on Github)?
Yes/No

If yes: please provide the URL:

https://github.com/WeFundOfficial

20) What programming languages do you use?
JavaScript
Java
Go
C# .NET
Ruby
iOS
Scala
Qt/C++
Flutter
PHP
Kotlin
TypeScript
Rust
React JS
Other:

**Comment by BlackTurtle123** [comment]
Hello!
We would need a more detailed breakdown, like #14 
Also, how would you make staking in Nexo trustless starting from wavesplatform?
We are also in doubt about how much it would be used on wavesplatform.

**Comment by BlackTurtle123** [comment]
Close no update
