### ISSUE TITLE
Accessible Education to Accelerate US Adoption

### ISSUE THREAD

**Issue by cryptotutors** [Waves-Association/grants-program#78]
- **Proposer:** Nina Blankenship, CEO of Crypto Tutors
- **Contacts:** nina@cryptotutors.com
- **Github username:** cryptotutors
- **Reward:** 55,000 waves

## 👥  Team 

- Are you applying to implement the grant as an individual developer or do you represent a team? A team
- Are you a startup or an ongoing business? Ongoing Business 
- What’s your team or startup name? What is a website? Crypto Tutors, cryptotutors.com

### Team members  (in case applying as a team or startup)

- Name of team leader: Nina Blankenship
- Names of team members: Lisa Francoeur, Moeti Ncube

### Team experience  (in case applying as a team or startup)

- Please describe your (team/startup) development experience and technological stack? 
Crypto Tutors was launched in Orlando, Florida in 2020 by Moeti Ncube (Head of Education), Lisa Francoeur (CRO), and Nina Blankenship (CEO). Moeti is a Zimbabwean-American who has a PhD in Statistics and has one of the largest staking nodes in North America on the Waves.Exchange platform. liberateyourwealth.com. He is also the creator of the first penny auction site to accept bitcoin for payment. He has over ten years of experience working as a financial engineer and energy trader at Nextera Energy Resources. Lisa is a proud Haitian-American, world renowned motivational speaker and is often called the "Oprah of Tech'' as she pursues her vision of "scaling empowerment globally.". She has 12+ years of experience as a business development executive in Tech with Fortune 100s. Nina is Japanese-American and has a degree in finance, is a LinkedIn e-Learning Author and is the owner of a content creation company. In addition to creating Crypto Tutors, this team launched the first ever Diversity in Cryptocurrency conference, Crypto For The Culture, in 2021. In addition to the founders, Crypto Tutors has 30 contractors on staff to create and market content such as 2D and 3D animators, custom sound and music, illustrators, marketing and website administration. 

- Do(es) you(r) (team/startup) have experience in using Waves technologies?
Yes. The founders of Crypto Tutors are committed users and promoters of Waves.Exchange and have been for years. Each of the founders have invested their personal money using the platform and trust the platform so much that they created Crypto Tutors to educate people how to stake using the platform. Since 2020, Crypto Tutors has offered training to individuals, corporations and government partners using Waves.Exchange. Through individual tutoring sessions and corporate training, Crypto Tutors clients have learned how to purchase cryptocurrency from Coinbase and CashApp and transfer the currency to Waves.Exchange, buy USDN and stake on the Waves.Exchange platform. Crypto Tutors is an approved partner with CashApp and is educating all CashApp employees globally about the Waves.Exchange platform. Crypto Tutors is capable of offering tutoring sessions in English, Portuguese, Spanish, Mandarin and Cantonese. 

- Please attach your (team/startup) portfolio (projects you’ve been involved in) 
- Team website: https://www.cryptotutors.com/about-the-founders
https://www.linkedin.com/in/lisafrancoeur
https://www.linkedin.com/in/nblankenship
https://www.linkedin.com/in/moeti-ncube-492aaa8
liberateyourwealth.com

## 🔍 Overview

- Short description of the solution you suggest

Crypto Tutors is going to create accessible, simplified education tutorials for North American users that can be added to Waves.Exchange under an Education tab on the platform’s main menu. Unlike the resources currently available under Support, these tutorials will include an engaging animated host, videos and images, and step by step instructions on a variety of common topics. Together with Waves.Exchange, Crypto Tutors will identify the most valuable tutorial topics to develop, such as getting started, staking, vocabulary, blockchain technology  and more. Advanced topics may include trading pairs, developing a node and creating a token. Additionally, users will be able to access tutoring sessions for free through the Education Menu tab for one year after the launch of the training on the Waves.Exchange platform. The e-Learning portion of the project and the tutoring described later in this application. Ultimately, users will be able to follow the tutorials and become engaged and active users of the Waves.Exchange platform. 

- How does it solve the specified problem?

Currently, there is no engaging education resource that utilizes images, videos or animation that outlines the steps to complete specific actions within Waves.Exchange. Users who want to see an example or watch a tutorial, must leave the platform and search for content on YouTube or other websites. At this point, they can be encouraged to try other platforms through advertising or may become frustrated if they cannot find what they are looking for, preventing them from returning to Waves.Exchange. Readily available tutorials that offer fundamental education utilizing a friendly, diverse female avatar host and step by step instructions will build trust with users, add to the active user base in Waves.Exchange, and ultimately increase liquidity in Waves.Exchange. Crypto Tutors has the expertise in curriculum development to create high value educational tutorials that will empower Waves.Exchange users to utilize the platform confidently. 

- How you will integrate this project into Waves / Neutrino.

This project will be integrated into Waves.Exchange through a new Education tab to be added to the top menu of the platform. Crypto Tutors can also drive traffic to the page to increase educational awareness of the page in the US market. 

- Why your team is interested in creating this project.

Crypto Tutors has already built a curriculum that focuses on the Waves.Exchange platform, with the overall goal of closing the wealth gap with knowledge. The community that Crypto Tutors is cultivating through education and the Waves.Exchange platform allows anyone to be able to participate in cryptocurrency. Partnering with Waves.Exchange to bring tutorials and tutoring to users is the perfect compliment to the Waves.Exchange US debut. 

To scale adoption in the US, educate the masses. The Waves.Exchange platform is very technical and can be intimidating to new users trying to learn the fundamentals of cryptocurrency. Novices, minorities, or someone new to the Waves.Exchange platform may not feel comfortable investing a large amount of money in cryptocurrency right away. After they have been educated in how to stake using stablecoins and see their interest grow, it increases their confidence. Ultimately, that confidence results in an increase in active investment in the platform and an increase in liquidity in Waves.Exchange. 

- What is the target audience of the final solution?

The target audience is all potential and new Waves.Exchange users in the United States who want to learn how to confidently use the platform through engaging tutorials. 

- What is the “secret sauce” of it?

Crypto Tutors loves to edutain. Crypto Tutors makes learning about cryptocurrency exciting and entertaining because Lisa Francoeur, who is the face of education at Crypto Tutors, has a magnetic personality and can engage any audience. She also writes and produces crypto rap music (available wherever you listen to music, search Crypto Tutors). Additionally, Lisa and NIna only entered cryptocurrency in 2020. If they don’t understand something, they know that other people do not either. They have the ability to transform complex vocabulary and steps into easy to understand videos and training that results in a seamless onboarding experience for new users. Moreover, all of the founders of Crypto Tutors speak and teach from true experience. Each founder, and several of the tutors, have made money while using the Waves.Exchange platform. These personal testimonials and experiences are vital to building trust with new users to the Waves.Exchange platform.

- What is the duration of the whole project?

21 months. Up to 9 months of creation and development of the curriculum from the date the grant is received. The content will be updated as the Waves.Exchange platform is updated for 18 months from the date the grant is received. Tutoring services will be available for 12 months from the day the content is published. After this time, the content can live on the Waves.Exchange platform indefinitely. 

- Resources required to implement the grant task
–1 hour meeting with Waves.Exchagne to identify the most important curriculum topics to include in the tutorials
–Funding to do the following:
—Create curriculum content including videos, animations, use of an existing avatar host, and more. 
—Offer individual and group tutoring sessions for one year

### Ecosystem Fit

Are there any other projects similar to yours? If so, how is your project different?

No other company is advocating for crypto education on the Waves.Exchange platform that targets the US audience and is a certified women and minority owned business. 

## 🔩 Development Roadmap 

Month one: Identify the topics to be included in the curriculum. Transfer e-Learning content that already exists to the Waves.Exchange platform. 
Month 2-3: Draft the tutorial content and video scripts.
Month 4-8: Develop the tutorial content including videos and animations for each identified topic
Month 9: Publish the tutorials on Waves.Exchange
Ongoing after publishing: Promote the tutorials 
Months 9-21: Individual and group tutoring sessions
Months 9-21: Updating of the tutorial content as needed as Waves.Exchange is updated

### Overview

- **Total Estimated Duration:** 21 months from the date the grant is received. 
- **Total Costs:** Amount of Payment in Waves for the whole project. The total amount of funding needs to not more than 100k Waves. 55,000 waves. 

## Additional Information ➕

To preview the avatar, visit the e-Learning module created by Crypto Tutors specifically for   public libraries to offer cryptocurrency education across the United States: https://www.cryptotutors.com/library

Crypto For The Culture conference website: https://www.cryptofortheculture.io/

**Comment by BlackTurtle123** [comment]
What nodes are you guys running? We need more detailed information about the cost breakdown. 55k is a lot. We would need a justification. Check out #14

**Comment by cryptotutors** [comment]
@BlackTurtle123 One of our founders is personally running the Liberate Your Wealth node for the Waves token. 

Here is a rewrite of the cost development section that includes a cost breakdown. Thank you so much for the request. We are huge advocates of Waves.Exchange and appreciate your support. If 55,000 Waves isn't available we are open to breaking up our proposal up to receive partial funding that will still provide educational resources to accelerate US Adoption. 

Waves Development Grant - Cost Breakdown - Crypto Tutors LLC 
Development Roadmap

Month One: Identify the topics to be included in the curriculum. Identify topics for tutoring. 
Deliverable: Up to 15 new topics for tutorials identified that will each include a video ranging from 1-60 minutes long. 
Costs
Project Management ($1,000)
Educational Consultation ($5,000)

Month 2-3: Transfer e-Learning content and supplementary materials that already exist to the Waves.Exchange platform under the new Education tab in the main menu. 
Deliverable: existing content available to users under the new Education tab. 
Cost
Project Management ($5,000)
Editing existing content to fit Waves.Exchange formatting requirements ($5,000)

Month 4-9: Develop the new tutorial content including videos and animations for each identified topic.
Deliverable: All identified tutorial topics are published by the end of month 9, or earlier. 
Costs
Curriculum development ($15,000)
Video script writing ($15,000)
Storyboard ($6,000)
Video production ($100,000)
Video editing ($35,000)
Illustrations ($5,000)
Animations ($10,000)
Sound/Music editing ($4,500)
Voiceover ($15,000)
Avatar editing ($25,000)
Copywriter ($7,500)
Quality control ($7,500)
Project Management ($20,000)
Design and Animation Software ($5,500)

Ongoing after publishing: Promotion & Marketing
Deliverable: promotional package equivalent to Lambo Sponsor level of the 2022 Crypto For The Culture Conference ($50,000 package with presumed reach of 2 million+ impressions that includes branding, talent pipeline strategy meeting, panel speaker, 30 second commercial, demo of Waves.Exchange, sponsor panel speaker, see cryptofortheculture.io for details). Additionally, 3 press releases, 21 social media posts, 3 video interviews. 
Costs
Lambo Sponsor package ($50,000)
Social media posts (complimentary)
Interviews (complimentary)
National Press Releases (USA) ($7,500)

Months 9-21: Individual and group tutoring sessions
Deliverable: Tutoring sessions can be instantly booked through the Waves.Exchange Education tab through an integration with Calendly and Zoom. Analysis report monthly on tutoring topics and feedback.
Costs
Creation of a tutoring page under the Education tab on the Waves.Exchange platform where users can book tutoring sessions by topic or tutor. ($500)
Booking software for 12 Tutors across multiple time zones and languages ($6,000)
Tutoring sessions total cost (assuming 200 individual sessions at $100 per session and 12 group sessions at $5,000 per session): $80,000

Months 9-21: Updating of the tutorial content as needed as Waves.Exchange is updated
Deliverable: Updates are reflected in the tutorials within 21 days after Crypto Tutors is notified that an update has been made. 
Cost
Video Editing ($5,000)
Animation ($5,000)
Voiceover ($2,500)
Illustration ($2,500)
Copywriter ($2,500)

Total Project Success measurements include:
An increase in Waves.Exchange users between project launch date and project end date. 
An increase in the number of visitors to the educational content month over month for the duration of the project. 
Increase in platform trust as extrapolated from tutoring feedback surveys. 
2 million impressions of promotional materials, posts, videos or other marketing coverage from the project launch date to the project end date. 
200 free to the user tutoring sessions booked through Waves.Exchange

Total Estimated Duration:** 21 months from the date the grant is received. 

Total Cost: $448,500; Total requested: 55,000 Waves (approx. $44,000). See breakdown in Roadmap section. 

Thank you for your consideration. 

Nina Blankenship
CEO
Crypto Tutors

**Comment by cryptotutors** [comment]
@BlackTurtle123 Any thoughts on the above with the breakdown of costs and services? We are also open to being flexible on launching with some parts of the project vs. others. Are you free for a meeting? Nina@cryptotutors.com https://calendly.com/ninacryptotutors/30min
