### ISSUE TITLE
Funding proposal P2E and M2E Game integrated with AR/VR & NFT Rental system

### ISSUE THREAD

**Issue by Blietje** [Waves-Association/grants-program#79]
- **Proposer:** Neal Peters
- **Contacts:** neal@junglerace.io / @Nealtje
- **Github username:** Blietje
- **Reward:** Amount in USDN if different from default reward

## 👥  Team 

- Are you applying to implement the grant as an individual developer or do you represent a team?
As a team
- Are you a startup or an ongoing business? (in case applying as a team or startup)
Startup
- What’s your team or startup name? What is a website? (in case applying as a team or startup)
https://junglerace.io

### Team members  (in case applying as a team or startup)

- Name of team leader

Neal Peters (me)

Co-founder & CEO. High level of experience in IT management, coordinating developers, and overseeing technical progress. Joined the crypto world in 2017 and had several roles from marketing to CTO jobs.

https://www.linkedin.com/in/nealpeters/
Telegram: @Nealtje

Marco Colaço

Co-founder & COO. Three years of experience in
management, engineering and planning. Since
2016 in crypto as Marketing Manager and
Community Lead. Vast financial knowledge and
funding experience.

https://www.linkedin.com/in/marco-colaco/
Telegram: @Marcocolaco

- Names of team members
Please see our pitchdeck for more detailed information about our team:
https://cdn.quicq.io/jungle/uploads/pitchdeck.pdf

### Team experience  (in case applying as a team or startup)

- Please describe your (team/startup) development experience and technological stack? 
We already develop several blockchain products like staking, farming, nft marketplaces, token contracts, nft contracts etc.

- Do(es) you(r) (team/startup) have experience in using Waves technologies?
Not directly in mainnet.

- Please attach your (team/startup) portfolio (projects you’ve been involved in) 
https://blkbirds.com

- Team website
https://junglerace.io

### Team Code Repos

N/A

## 🔍 Overview

If this application in response to a public task then please indicate this on the first line of this section.

Welcome to JUNGLE RACE! 

🕹 Jungle Race is a Move to Earn and Play to Earn NFT racing game in which the objective is to drive through various race tracks based in a Jungle.

The players can trade, collect and play with their own driver and vehicle in one of the four games. In addition to fun and competition there is a wide variety of NFTs player can use. Players benefit from the M2E concept by accumulating miles driven and if you reach the podium you benefit from P2E earnings.

The game takes place in a 3D multiplayer environment that is easy to play, fun and very addictive.

One of the unique concepts that we are going to implement is a vehicle rental system. 

NFT owners can put their unused assets for rent to generate passive interest, in Jungle Race you put your vehicle up for rent while the renter plays the game, sharing the M2E and P2E earnings between both own er
and renter.

The NFT Owner will remain the ow ner of the NFT at all
times so t here is no risk of losing your vehicle when you
put it up for rent.

- - - - - - - - - - - - - - - - - - -

🏁 NFT: Users can collect rare virtual items like Karts, Planes, Boats, Drivers, Accessories and power ups. An addictive collection with more than 10,000 NFTs: unique, tradeable, and playable.

🏎 GAMING: Jungle Race has more than one game mode and racetracks, increasing the player's fun even more and boosting their earnings, “Earn while having fun”.

💲M2E: Jungle Race has a Digitalized Move to Earn concept where the miles raced will be recorded for the first 5 races of each day. Players will earn $JRG tokens based on the numbers of miles raced.

💲P2E: Jungle Race is a Play to Earn concept. If you reach the podium on a race you will earn $JRG tokens.

⛵️🏃🏎 ✈️ GAME TYPES: Jungle Race - Fly will be available before TGE. After TGE three other game types will be released. Jungle Race - Boats, Fly and Run.

🚘 METAVERSE: AR/VR gaming in which players can have an immersive experience in a realistic landscape. In addition to being able to have interactions with other users in the racetrack hall.

🔥 DEFI: Staking and Farming will help in the growth of liquidity and also serve as an incentive for $JRG holders who believe in the project in the long term.

- - - - - - - - - - - - - - - - - - - 

🌟 $JRG TOKENOMICS

⚡️ Total Supply: 100M tokens
⚡️ Initial Circ. Supply: 2.08M tokens
⚡️ IMC: $208,000
⚡️ FDV: $10,000,000

- - - - - - - - - - - - - - - - - - - 

🛻 FEATURES

✅ R2E: Rank on the podium to Earn
✅ M2E: Race miles to Earn
✅ Playable NFT Collections
✅ Vehicle Rental System
✅ Play To Earn
✅ NFT Marketplace
✅ Upgrade System
✅ Staking & Farming 

- - - - - - - - - - - - - - - - - - - 

💸 REVENUE 

💰 In-Game Purchases: Karts, Planes, Boats, Drivers, Power-ups, Weapons, etc
💰 NFT Sales & Royalties
💰 On-platform Ads
💰 Token appreciation
💰 Platform Transaction Fees

- - - - - - - - - - - - - - - - - - - 

🌐 SOCIAL LINKS

Website (https://junglerace.io/) (https://junglerace.io)
Twitter (https://twitter.com/junglerace_) (https://twitter.com/junglerace_)
Email (info@junglerace.io)
Telegram (https://t.me/junglerace) (https://t.me/junglerace)

- - - - - - - - - - - - - - - - - - - 

📎 DOC

Pitchdeck

(https://junglerace.io/wp-content/uploads/pitchdeck.pdf)

- - - - - - - - - - - - - - - - - - -

🤝 PARTNERS & BACKERS 
Wopp (https://wopp.io/)
FinalFilm (https://finalfilm.nl/)
BlkBirds (https://blkbirds.com/)
Gotbit (https://gotbit.io/)
Babylons (https://app.babylons.io/)
MobiPad (https://mobipad.io/)
DAOStarter (https://www.daostarter.pro/#/)
Popkon (https://popkon.io/) 
Infinitypad (https://infinitypad.io/)
Synapse (https://synapse.network)
Polygon Studios (https://polygonstudios.com/)

**Comment by Blietje** [comment]
@BlackTurtle123 (Bram) can we set up a call / meeting to discuss this? I believe we speak the same language so would be easy ;-)!

**Comment by BlackTurtle123** [comment]
Hello @Blietje 
Could you update the application to be more in-line with #14 
Also could you give us some kind of demo?
What has waves to do with the application? The token is on BSC and the nft/game logic on polygon?
We don't see waves involved anywhere...

**Comment by BlackTurtle123** [comment]
No update so we will close it.
