### ISSUE TITLE
Solido.Games

### ISSUE THREAD

**Issue by maksim-solido** [Waves-Association/grants-program#80]
- **Proposer:** Maksim Kuznetsov(Affiliate-manager)
- **Contacts:** https://t.me/maxkuzzz
- **Github username:** https://github.com/maksim-solido

## 👥  Team

- Are you applying to implement the grant as an individual developer or do you represent a team?

Solido.Games team

- Are you a startup or an ongoing business? (in case applying as a team or startup)

Startup

- What’s your team or startup name? What is a website? (in case applying as a team or startup)

Solido.Games 
[https://solido.games](https://solido.games/about)

### Team members  (in case applying as a team or startup)
 - Name of team leader 
Anton

- Names of team members
Evgeniy
Isom
Phillip
Axinia
Kevin
Sergio 
Natali
Petr

### Team experience  (in case applying as a team or startup)

- Please describe your (team/startup) development experience and technological stack? 

Anton CEO - https://www.linkedin.com/in/anton-kanavalau/
Extensive experience in creating Game Aggregators and marketplaces. Ex CEO at Cointelegraph store.

Evgeniy CTO - https://www.linkedin.com/in/evgeniy-mil/
Solid experience in creating CRM systems, marketplaces, game aggregators. High performance.

Isom CBDO 
Professional gamer. Web3 investor. Founder in Decorative smart system Diodey. 

Axinia CMO - https://www.linkedin.com/in/kseniashliakhtina/
Ex CMO Cointelegraph store. Experienced Digital Marketer.

Phillip Adviser - https://www.linkedin.com/in/philip-devine-a86b8538/
CEO Riveted Games, CryptoBlades, the world’s largest game marketplace.

Kevin Strategic Adviser - https://www.linkedin.com/in/Kevinabdulrahman
Strategist to Gaming, NFT & Metaverse projects. Public speaking coach to CEOs and world leaders. 

Sergio CFO 
Financial genius, Excel’s best friend. Ex-finance director with expensive experience.

Natali Designer
UI/UX professional. Winner of international design awards.

Petr SEO Director
Expert in SEO, 3D design. Gamer. Very proactive and creative.

- Please attach your (team/startup) portfolio (projects you’ve been involved in) 

Project:
https://store.cointelegraph.com/

- Team website
https://litepaper.solido.games/

## 🔍 Overview

- Short description of the solution you suggest

Solido Games – Decentralized P2E and Metaverse Ecosystem
Combining technologies of the metaverse, blockchain ledgers, and decentralized networks into a unified platform with an intuitive user interface, Solido Games represents the state-of-the art in gaming today bringing players, developers, and NFT traders together in one interactive ecosphere. Solido Games platform includes three important elements (i) a P2E Game Aggregator, (ii) a MVP Launchpad, and (iii) an NFT marketplace. Specifically, Solido’s P2E Aggregator provides players convenient access to a wide selection of online and play-to-earn (P2E) games hosted across multiple blockchain networks. In the P2E Aggregator, players are able to sort and select games by cost, genre, devices, blockchain, NFT and crypto support, popularity, ratings, and by special offers. In its MVP Launchpad, game makers are able to fund, develop, and launch new games in the Solido ecosphere, and promote their releases to gamers through special offers and token incentives, thereby bridging the gap between players and developers. Another unique innovation of Solido is its Metaverse Market, a market for swapping or procuring NFTs or exchanging for crypto (SLG token).

- How does it solve the specified problem?

The project solves two of the biggest problems for an ambitious game developer - no money and no customers.
And also solves two main problems of the gamer - high prices for trying out the game and big risks of losing everything.

- How you will integrate this project into Waves / Neutrino.

We often get new games that don't know which blockchain to run on, and here we can push them towards you. We can also show projects on your blockchain in priority, which will give more attention to the development of your ecosystem

- Why your team is interested in creating this project.

Last year, several members of our team faced problems in the GameFi industry: not understanding where to find a suitable game according to the criteria, a high price for admission without preliminary testing (there was no possibility of short-term testing) and poor quality of most games.

- What is the target audience of the final solution?

Gamers (GameFi) and game developers

- What is the “secret sauce” of it?

The only service in GameFi that combines a convenient aggregator, launchpad, marketplace and social score.

- What is the duration of the whole project?

We assembled a team and started implementing the project in 2021 Q4. During this time, we have already managed to consolidate a partnership with 10+ game developers.

- Resources required to implement the grant task

Providing grants for brand development and marketing.
Consulting and marketing support.

### Ecosystem Fit

Are there any other projects similar to yours? If so, how is your project different?

Competitive Positioning:
A comparative evaluation of Solido Games technology portfolio and ecosphere reveals its unique advantage over all other launchpads. Moreover, most game platforms today are centralized- server based Web-2 legacy constructs lacking decentralization, blockchain processing, and autonomously authored smart contracts, the hallmarks of Solido’s advanced design. In fact, Solido has recently been recognized as a Top 10 blockchain games aggregator on the Solana network.

![D0F7188B-2F96-483E-9C64-7614E1D6705A](https://user-images.githubusercontent.com/106735019/171790477-e99919c4-9991-4404-820e-dfac6041ec44.png)

## 🔩 Development Roadmap 

![Solido Games_ DevelopmentRoadmap](https://user-images.githubusercontent.com/106735019/171790564-5935eaf8-1fe6-403a-9fb5-4cad5c683052.JPG)

## Additional Information ➕

Video: https://youtu.be/a3tWC8Ogm5Y
   Website: https://solido.games/about
   One Pager: https://app.solido.games/files/solido.games_onepager.pdf
   Whitepaper: https://app.solido.games/files/solido.games_whitepaper_v18.pdf
   Gitbook: https://litepaper.solido.games
   Pitch Deck: https://app.solido.games/files/solido.games_pitch.pdf
   Tokenomics - https://docs.google.com/spreadsheets/d/1xxaD9Zuk6PjpeHW82rq_VsqETVDm3WcQbJiTk9eLEAM/edit#gid=1785940346

**Comment by BlackTurtle123** [comment]
Hello please check #14 for a proper application

**Comment by BlackTurtle123** [comment]
No update, so denied
