### ISSUE TITLE
GetBlock Explorer for Waves - [Track 2. Web3.0 Development Grant] 

### ISSUE THREAD

**Issue by LizaGetBlock** [Waves-Association/grants-program#81]
- **Proposer:** Liza Allen
- **Contacts:** @Liza_GetBlock
- **Github username:** https://github.com/LizaGetBlock 

## 👥  Team 

- Are you applying to implement the grant as an individual developer or do you represent a team?
Team GetBlock
- Are you a startup or an ongoing business? (in case applying as a team or startup)
GetBlock is an ongoing business, and the GetBlock explorer is a project within this business, although it is not launched yet
- What’s your team or startup name? What is a website? (in case applying as a team or startup)
GetBlock Explorer, https://getblock.io/

### Team members  (in case applying as a team or startup)

- Name of team leader
Alex
- Names of team members
Frank, Mike, Tyrell, Arthur, Liza

### Team experience  (in case applying as a team or startup)

- Please describe your (team/startup) development experience and technological stack? 
Team experiences include:
Project Management: 7+ years of experience in marketing along with 3+ years of experience in IT projects management
Backend: 3+ years of experience (Go, Cassandra, Clickhouse, NATS, Redis)
Frontend: 3+ years of experience (Nuxt, Vuex, Tailwind, Jest, Sentry)
DevOps: 5+ years of experience (Docker, Nomad, Grafana, Prometheus, Loki, Consul, Envoy)
Design: 3+ years of experience in UX/UI design along with 4+ years of experience in graphic design
BizDev/Marketing: 2+ years of experience in SMM, PR, digital and growth marketing of crypto and blockchain projects, lead generation and partnerships
In general, we have experience in building blockchain explorers for other blockchains. During the following weeks we will release a working real-time explorer for NEAR blockchain. 

- Do(es) you(r) (team/startup) have experience in using Waves technologies?
Yes, GetBlock has Waves nodes in operation.

- Please attach your (team/startup) portfolio (projects you’ve been involved in) 
GetBlock - blockchain nodes provider: https://getblock.io/
- Team website
https://getblock.io/

### Team Code Repos

The project code will be kept private.

## 🔍 Overview

Please describe your solution idea by the following structure:

- Short description of the solution you suggest
Our aim is to build a user-friendly blockchain explorer in an app-like modern interface. We want to build a tool for the entire community that will facilitate on-chain data and high-end analytics in an easy-to-read and to-understand format fit for both newbies and crypto-savvy individuals. 

- How does it solve the specified problem?
The explorer is one of the most important tools for a blockchain, and we believe that transparency and reliability are two key values that such a tool transmits. A user-friendly and easy-to-read interface is a majorly overlooked aspect for many explorers including the ones built for Waves. Our goal is to build an explorer in an intuitive and attractive interface that the users will find modern and smooth. Moreover, since the explorer will have multiple blockchains, the users will be able to switch between them and see diverse on-chain data for a handful of blockchains in one place.

- How you will integrate this project into Waves / Neutrino.
The explorer development will require our team to deploy the archive node for fast and consistent Waves blockchain data retrieval. The data will be processed and displayed in a graphic app-like user interface. 

- Why your team is interested in creating this project.
Our team’s end goal and motivation is to build a wholesome multichain explorer in an intuitive and attractive interface that the users will find modern and smooth. Moreover, since the explorer will have multiple blockchains, the users will be able to switch between them and see diverse on-chain data for a handful of blockchains in one place.
Furthermore, Waves is one of the well-established blockchains with a reputable name in the industry. Building an explorer for such a community and being trusted by it speaks for itself.  

- What is the target audience of the final solution?
Users of Waves blockchain, token holders, developers.

- What is the “secret sauce” of it?
User-friendly, app-like UI, easy-to-understand format of data and attractive and smooth design.

- What is the duration of the whole project?
Although the plan is to complete the project within 5 months from the date of grant approval, we’re actively expanding our team to reduce this timeframe. 

- Resources required to implement the grant task
The grant will be used for product development. We are also open to include the features to the explorer upon request. Marketing support would also be appreciated. 

### Ecosystem Fit

Are there any other projects similar to yours? If so, how is your project different?
Currently there are 3 explorers for Waves: wscan, Waves Explorer and Waves Blockexplorer. One of them seems to not display any data at all at the moment, while 2 others have a time-proven functionality in an interface we see fit modernizing. We believe the UI and UX can be improved and this is one of the key aspects of our project. 

## 🔩 Development Roadmap 

**Milestone #1**

- Analytics research
- Infrastructure for explorer 
- Supporting services
- Frontend environment 
- Data scheme
- DB analytics
- Prototyping + web design
- Frontend initiation

**Milestone #2**

- Core adoption
- Moving API from DB to front
- Scaling
- Deployment
- Testing.

**Milestone #3**

- Bug Fixing
- Marketing and Partnerships

Within this application we are requesting funding with a total cost of $50,000. We're hoping to attract around 10k users in the first 6 months and then doubling it by the end of the first year. We have an experienced marketing assistance on board to execute our go-to-market strategy. Our foremost focus would lie within referral and social media traffic. These channels have a potential in terms of attracting the desired numbers of users.

### Overview

- **Total Estimated Duration:** 5 months to deliver 
- **Total Costs:** $50,000 with the following distribution by categories: 

Backend: 40%
Frontend: 20%
DevOps: 15%
UX/UI: 15%
Management: 10%

## Additional Information ➕

Here you can take a look at our pitch deck with design layouts and detailed list of explorer functionalities: https://drive.google.com/drive/folders/17IIHyzKT0o9DvXiLh50Meq6qhqwzbqo_?ths=true

**Comment by BlackTurtle123** [comment]
Hello,
Did compare yourself to other explorers in the ecosystem? Do you know what explorers this are? Why should we fund you to create a new explorer?
What is your USP.
Also we would need a more detailed breakdown, check out #14

**Comment by LizaGetBlock** [comment]
> Hello, Did compare yourself to other explorers in the ecosystem? Do you know what explorers this are? Why should we fund you to create a new explorer? What is your USP. Also we would need a more detailed breakdown, check out #14

Hello Bram,

Thank you for taking your time to review our application. Let me expand on the questions that you asked. 

1) USP and competitive advantages.
We emphasise the UI and UX of our explorer - thus, it will be far more user-friendly and intuitive. People are used to app-like interfaces that flow smoothly. It is especially important when it comes to blockchain analytics - the data may be complex and overwhelming for both newbies and blockchain-savvy individuals. That is why our team focuses on framing this data in an easy-to-read format. You can check out our testnet version of the NEAR explorer here: https://getblock.tech/near/. It already has real-time data and we're now fixing some little bugs we have before the official release. This is approximately what we aim at when building Waves explorer as well. 
Moreover, we're now conducting a series of user research interviews to identify when exactly blockchain community uses explorers so we can build on user needs. We've already collected some insights on this matter, and we'll keep doing it for the next few weeks. 

2) Detailed breakdown.

We'd like to clarify whether you're asking about costs breakdown and want us to write down the grant allocation for each milestone.  If this is the case, let us know.
Also, in the timeline we provided in the application, we specified the scope of works that needs to be done. However, we understand that you need a "tangible" step-by-step result of our work and we'll be releasing the explorer page after page so you can see our progress once we have the architecture and DB set.

**Comment by BlackTurtle123** [comment]
Hello,
We will have to deny this one as your explorer has almost the same info and other things as the default wavesexplorer one.
