### ISSUE TITLE
UnicusOne - Web3.0 Development and Waves Integration Grant

### ISSUE THREAD

**Issue by UnicusOne** [Waves-Association/grants-program#84]
\[BEFORE YOU START\]:

1. Please use [Certificado project issue as an example of good application for a grant](https://github.com/Waves-Association/grants-program/issues/14)
2. Waves Assocation Members can ask questions about your project and they will leave questions in this issue, so please keep an eye on the issue and reply to comments and questions.

---

- **Proposer:** Introduce yourself (name, surname) 

Tashish Rai Singhani

- **Contacts:** Your email or telegram handle

tashish@unicus.one

- **Github username:** Your Github login

UnicusOne

## 👥  Team 

- Are you applying to implement the grant as an individual developer or do you represent a team?

UnicusOne Team

- Are you a startup or an ongoing business? (in case applying as a team or startup)

Ongoing Business

- What’s your team or startup name? What is a website? (in case applying as a team or startup)

Unicus One 
http://www.unicus.one/

### Team members  (in case applying as a team or startup)

- Name of team leader

Tashish Rai Singhani

- Names of team members

Shrishti Singh (Co-Founder)
4 Software Engineers along with 5 Team mates who manage Community, Operations, and Marketing.

### Team experience  (in case applying as a team or startup)

- Please describe your (team/startup) development experience and technological stack? 

Smart Contracts- Solidity, Rust - 3 year
MEAN/MERN - 5 years
DevOps - 3 Years

- Do(es) you(r) (team/startup) have experience in using Waves technologies?

No

- Please attach your (team/startup) portfolio (projects you’ve been involved in) 

[Project](https://github.com/UnicusOne?tab=repositories)
[Dev1](https://github.com/shrishtieth)
[Dev2](https://github.com/Nayan96)
[Dev3](https://github.com/Kartikpjpt)
[Dev4](https://github.com/Ap8690)

- Team website

[UnicusOne](http://www.unicus.one/)

### Team Code Repos

[Project](https://github.com/UnicusOne?tab=repositories)
[Dev1](https://github.com/shrishtieth)
[Dev2](https://github.com/Nayan96)
[Dev3](https://github.com/Kartikpjpt)
[Dev4](https://github.com/Ap8690)

## 🔍 Overview

Please describe your solution idea by the following structure:

- Short description of the solution you suggest

UnicusOne is a Multi Chain Web3 as a Service (WaaS) platform which aims to transform the Web2.0 economy into Web3.0 instantly. Our API based widget solution makes a traditional web application into a Web3 one within few minutes. The No Code Web Storefront solution enables you to make your own NFT Marketplace with a DIY approach. Our Master NFT Marketplace also have an option to trade NFT users with Fiat currency as well. We also have a module of Web3 payment gateway for businesses.

- How does it solve the specified problem?

One of the biggest problems in the Web3 sector is finding good Web3 developers. The issue is with the expense, availability, and development time required. Our modules and solutions are mild code and ready to deploy. We can enter the market quickly with no or negligible entry cost. As we provide Audited smart contracts, our partners need not get it done and we will maintain it as well.

- How you will integrate this project into Waves / Neutrino.

Our Web3 team will write smart contracts - Minting, Listing and Trading NFTs and integrate them with the platform as quickly as possible. Once the integration with Waves is complete, Any project, which wishes to build on Waves, can use our Web3 services and launch it instantly.

- Why your team is interested in creating this project.

We are building a Web3.0 as a service platform, targeting partnership model. We are not running the B2C race but aim to achieve our revenue using the B2B approach of onboarding partners who are established in the Web2 space and wish to enter the Web3 world. We provide quick Go To Market solutions to these partners using UnicusOne infrastructure.

- What is the target audience of the final solution?

We have 2 primary set of target audiences:
1. Any new project in the NFT economy - Gaming, Metaverse, and Real World asset tokenization. 
2. Any B2B partner in the following domains - Virtual Real Estate, Supply Chain, Digital Fashion.

- What is the “secret sauce” of it?

Our secret sauce which makes us different from all the other projects out there is the NPM package (APIs) based widget solution for quick implementation.

- What is the duration of the whole project?

4 weeks for the Wave integration. 

- Resources required to implement the grant task

USD 30,000 for tech development hence spreading the word in the community. 

### Ecosystem Fit

Are there any other projects similar to yours? If so, how is your project different?

Frankly, we do not see any competitor who is providing Web3.0 on a SAAS model, like I mentioned Web3.0 as a service.

## 🔩 Development Roadmap 

This section should break out the development roadmap into a number of milestones. It helps to describe the functionality we should expect, plus how we can check that such functionality exists in the product. Whenever milestones are delivered, we refer to the roadmap to ensure that everything has been delivered as expected.

STEP 1: Integrating Waves into UnicusOne NFT Marketplace (USD 10,000)

STEP 2:Integrating Waves into UnicusOne store-front solution (USD 10,000)

STEP 3:Integrating Waves into UnicusOne widget solution (USD 10,000)

### Overview

- 4 Weeks estimated duration for the implementation.
- USD 30,000

**Comment by BlackTurtle123** [comment]
The idea is kinda cool, but we are doubting that the wavesplatform users are waiting for this.
So for now we have to deny it.
