### ISSUE TITLE
Interhack Grant: Project Keila

### ISSUE THREAD

**Issue by devreetd** [Waves-Association/grants-program#85]
Hi my name is Devreet Dulay and I am representing Project Keila!
Telegram: devreett
Email: projectkeila@gmail.com
Github: devreetd

## 👥  Team 
We are a team of 5 applying for this grant. We are a startup, a new project in the launch phase.
Team name is Project Keila, we don't have a website at this moment, it will be up soon, but we do have a pitch deck.

### Team members  (in case applying as a team or startup)
Team Leader: Joshua Porter
Team Members: Devreet Dulay, Hashir, Jivan & Beret

### Team experience  (in case applying as a team or startup)
Hashir  - 5 years of experience in business development, opening new markets (Blockchain and IT Strategic Market Analysis) business coaching, leadership. Previous served as C-level positions at various Web 3.0 companies.
Devreet - 4 years of experience in business model and financing, team management, sales strategies. 
Joshua - 2 years of experience in startups, negotiation strategies, project management, conflict management. Worked as CEO for The 97 Universe and IsNowGlobal.
Jivin - 7 years of experience fullstack developer, Blockchain experience in Rust, IIT graduate top of the class. Worked at Google and Microsoft.
Beret - Environmentalist science graduate and associate professor at University of Delhi.
No experience using Wave Technologies.

### Team Code Repos
https://github.com/orgs/Project-Keila/people/Alexbacker001
https://github.com/orgs/Project-Keila/people/best-lucky1030
https://github.com/orgs/Project-Keila/people/JIVIN0902
https://github.com/orgs/Project-Keila/people/Mister-97
https://github.com/orgs/Project-Keila/people/oroghene

## 🔍 Overview
Project Keila is combating climate change by using NFT’s to offset carbon emission. We all know the blockchains energy footprint can be detrimental to the environment and we found the perfect solution to reverse those effects. By buying a NFT you’ll be buying a digital twin of a real life tree, a NFT= 1 tree planted. Each tree will also be serialized, which gives you the gps coordinates as well. 

### Ecosystem Fit
KlimaDAO tokenizes carbon credits. Nothing is actually being done, they’ve established a token to incentivize parties to be a part of a bigger picture that offset carbon emissions, but there is no actual plan in motion as to how they are planning on doing this. Another competitor is [Moss.earth](http://moss.earth/), they offer NFTs that get you a piece of land in the Amazon forest, and you are protecting this land. This is one part of their initiative that is similar to ours, but right now they are only focusing on South America.

## 🔩 Development Roadmap 
#1 Community growth: generating traction around company's mission, acquire waitlist customers, get 500 people within the 1st week of launching website. 

#2 Finalizing land agreements: Securing our land to plant the trees, getting enough funding to pay for the legal costs, taxes and licenses. 

#3 Attending conferences: Meeting people in the space and setting up booths to get brand awareness, attend 2-3 conferences by December 2022.

#4 Plant 10,000 trees by April 2023, this will be through partnerships and customers.

### Overview
This is an ongoing project, but our first year is the most critical, to have a successful launch. We are requesting 65,000 waves, here is a breakdown for our cost request. 

1.) Community growth: generating traction around company's mission, acquire waitlist customers. Funds - $5,000.
2.) Attending conferences: Getting a booth for brand awareness, travel/accommodation, ticket cost, food. Funds - $10,000
3.) Plant 2,000 Trees: Labor costs ($10 per tree), samplings ($5 per tree), transportation & storage ($5 per tree). Fund - $40,000
4.) Operations: Finalizing land agreements where we will plant the trees, this will entail legal cost, auditor, taxes and licenses. Fund - $10,000

## Additional Information ➕
Pitch deck link:
https://docs.google.com/presentation/d/131r2mzPvcg8ouiAy3zd4hxqoEt8zsma5qdeUoQaM5cA/

**Comment by BlackTurtle123** [comment]
Hello,
We think this project is requesting to much funds, and is not unique in it's kind. A lot of projects and environment groups are doing similar projects
