### ISSUE TITLE
Waves Launchpad

### ISSUE THREAD

**Issue by ravindrareddychitla** [Waves-Association/grants-program#86]
\[BEFORE YOU START\]:

1. Please use [Certificado project issue as an example of good application for a grant](https://github.com/Waves-Association/grants-program/issues/14)
2. Waves Assocation Members can ask questions about your project and they will leave questions in this issue, so please keep an eye on the issue and reply to comments and questions.

---

- **Proposer:** Introduce yourself (name, surname) 
Ravindra Reddy Chitla
- **Contacts:** Your email or telegram handle  
ravindrareddychitla@gmail.com or https://t.me/ravchit
- **Github username:** Your Github login
https://github.com/ravindrareddychitla
## 👥  Team 

- Are you applying to implement the grant as an individual developer or do you represent a team?

It will be a team but not formed yet

- Are you a startup or an ongoing business? (in case applying as a team or startup)

This will be a startup but with experience people in crypto and launchpads

- What’s your team or startup name? What is a website? (in case applying as a team or startup)

Not named yet and this is at the idea stage so the business name and website will be created in later stages

### Team members  (in case applying as a team or startup)

- Name of team leader
Ravindra Reddy Chitla

- Names of team members
I have many friends with the required skills like typescript, javascript, rust, python, react.js, node.js, web3.js and ethereum.js but I need to choose the best fit once this proposal gets approved

I am also working for multiple IDO launchpads (I can disclose names privately) so I can get their help in hiring team if required

### Team experience  (in case applying as a team or startup)

- Please describe your (team/startup) development experience and technological stack? 

- Do(es) you(r) (team/startup) have experience in using Waves technologies?
We have used other blockchain technologies but BNB Chain, Polygon and Solana etc but we will use Waves 1st time

- Please attach your (team/startup) portfolio (projects you’ve been involved in) 
Currently, I am working for https://coinxpad.io/ and https://dexcheck.io/

- Team website
As mentioned, the website will be created in later stages

### Team Code Repos

Will be provided in later stages once I pick the right team members

## 🔍 Overview

Please describe your solution idea by the following structure:

- Short description of the solution you suggest

Waves Launchpad helps launch the projects that are built on Waves Blockchain Technology. This launchpad will bring all the investors together and create  a strong community to help grow Waves Eco-system. With WAVES partnership all the new projects that are being launched on WAVES will be launched on this dedicated launchpad. This launchpad will help the new projects with all the marketing help like Community building, Brand Awareness, Fund Raising and KOL introductions, Pressrelease marketing any many more

- How does it solve the specified problem?

Evey new project that gets built on WAVES need to be launched in the marketing and the new tool that I am proposing can help in multiple ways to the founders and it makes their journey easier prelaunch stage

- How you will integrate this project into Waves / Neutrino.

This launchpad will have token system so all the tokens will be issued on WAVES blockchain technology

For the fundraising, we use USDN as a primary stable coin like NEWWAVESTOKEN-USDN pairs

If any user has to participate in IDO's they need to buy the USDN and then exchange it for the new project tokens that we are raising funding. 

This will just not help WAVES and Neutrino but also help growth of Waves Exchange/Puzzle Swap because all the new coins will be listed on DEX's at token generation event. It also creates utility for Swop.fi as we may use AMM for the all the new tokens 

- Why your team is interested in creating this project.

Because I have been working with launchpads for over a year and I know how difficult for the new projects to get into the market. They need lot of marketing help and good connections to bring their project in to the real world. Lot of the projects wasting lot of money and time to get the pre-launch help and they are not really focusing on the development rather marketing

So, providing the prelaunch help can take half of the pain for the founders and they can fully concentrate on the roadmap and developments

- What is the target audience of the final solution?

It will be 2 siders

1) The Founders/Developers who are building on WAVES because they need a launchpad to market their new project
2) Retail investors and VCs who can invest help grow the projects on WAVES blockchain technology

- What is the “secret sauce” of it?

It may not be a new idea but a dedicated launchpad for WAVES is need to grow the WAVES ecosystem but we can add som innovation with this implementation 

We can also charge low marketing fees for the standard services 

- What is the duration of the whole project?

It can be realistically take 6 months to 9 months but I can try to deliver the project much sooner if I get right technical team

- Resources required to implement the grant task

I need grants for hiring a development team, buy the tools and required technology, marketing tools, advisor fees, marketing services like community building, brand awareness, completions, fundraising & PR etc

### Ecosystem Fit

Are there any other projects similar to yours? If so, how is your project different?

I think https://swop.fi/ has some sort of launchpad functionality but they have lot of products to-gether but ours is a  specific launchpad for WAVES create awareness in the market and keep the investors ready for the new project that will be built on WAVES technology. Also, we provide all the pre-launch marketing help for the new projects that will be launching on WAVES

## 🔩 Development Roadmap 

This section should break out the development roadmap into a number of milestones. It helps to describe the functionality we should expect, plus how we can check that such functionality exists in the product. Whenever milestones are delivered, we refer to the roadmap to ensure that everything has been delivered as expected.

**Step #1**: Front End Website Design

Front End Website Design ($10000)

**Step #2**:  Launchpad Development

Launchpad Functionality Development including wallet intergrations  ($50000)

**Step #3**:  Smart Contract Development & Integration

WAVES Smart Contract Development & Integration ($5000)

**Step #4**:  Contract Auditing

Contract Auditing ($5000)

**Step #5**:  PR & Marketing

PR and Marketing to Awareness and Community ($20000)

**Step #6**:  2nd Audit

2nd Audit ($5000)

**Step #7 **:  Functionality Recheck

Design and Functionality Recheck ($5000)

### Overview

- **Total Estimated Duration:** Duration of the whole project is 6 months and expected delivery by 31st Dec 2022

- **Total Costs:** Amount of Payment in Waves for the whole project. The total amount of funding needs to not more than 18500 Waves.

**Comment by BlackTurtle123** [comment]
We are missing a whole lot of details.
We need a lot more details, screenshots, UI/UX examples,..
How can you estimate a budget or request money without a team, so without knowing the technical challenges and timeframes

So we will close this application
