### ISSUE TITLE
MyMetaverse: Web3 Gaming Platform with 4 LIVE Games

### ISSUE THREAD

**Issue by SimonKertonegoro** [Waves-Association/grants-program#88]
\[BEFORE YOU START\]:

1. Please use [Certificado project issue as an example of good application for a grant](https://github.com/Waves-Association/grants-program/issues/14)
2. Waves Assocation Members can ask questions about your project and they will leave questions in this issue, so please keep an eye on the issue and reply to comments and questions.

---

- **Proposer:** 
Simon Kertonegoro
- **Contacts:** 
simon@mymetaverse.io and Esscay 
- **Github username:** 
SimonKertonegoro

## 👥  Team 

- Are you applying to implement the grant as an individual developer or do you represent a team? 
MyMetaverse has a team of 20 developers and designers

- Are you a startup or an ongoing business? (in case applying as a team or startup) 
We are a startup that has been going for nearly 4 years

- What’s your team or startup name? What is a website? (in case applying as a team or startup) 
Our project is called MyMetaverse, our website is mymetaverse.io, and our whitepaper is available at whitepaper.mymetaverse.io

### Team members  (in case applying as a team or startup)

- Name of team leader
Simon Kertonegoro

- Names of team members
Steve McIntyre (COO)
Ricardo Rodriguez (CTO)
Justin Martin (CIO)
David Schiller (CMO)
+ 15 more developers and designers

### Team experience  (in case applying as a team or startup)

- Please describe your (team/startup) development experience and technological stack? 

We have successfully built and launched blockchain integrated gaming platform with four games.

The platform is currently connected to Ethereum, and JumpNet, we would like to connect it to WAVES as well.

This would mean WAVES NFTs would become usable in all of our games:

[Infinity Realms](https://mymetaverse.io/games/infinity-realms) - A 3D MMORPG where players can create communities of Meta characters that farm, mine, fight, and breed.

[Survival Infinity](https://mymetaverse.io/games/survival-infinity) - A Minecraft network that fuses the most popular Minecraft game modes like Survival and Arenas with powerful NFT mechanics.

[Infinity Auto](https://mymetaverse.io/games/infinity-auto) - A Grand Theft Auto 5 missions server where players can create their own stories and build NFT characters.

[Governors Paradise](https://mymetaverse.io/games/governors-paradise) - An exclusive Minecraft network that can only be accessed by the Governors of Infinity

- Do(es) you(r) (team/startup) have experience in using Waves technologies?

No

- Please attach your (team/startup) portfolio (projects you’ve been involved in) 

You can use our platform and play our games at MyMetaverse.io

- Team website

MyMetaverse.io

### Team Code Repos

https://github.com/MyMetaverse

## 🔍 Overview

Please describe your solution idea by the following structure:

- Short description of the solution you suggest
The games market currently captures a lot of player time and money but don't reward them with life-changing value.

- How does it solve the specified problem?

MyMetaverse is a games library, app store, and metaverse explorer for NFT-powered Play-and-Earn games. 
Players can come to our platform to find games that offer them real value and money. Developers can use our platform to integrate real value into their games. 

- How you will integrate this project into Waves / Neutrino.
We will connect the WAVES blockchain into our ecosystem so we can start reading the chain and providing in-game utility to NFTs on WAVES

- Why your team is interested in creating this project.
Because gamers deserve real-value rewards in exchange for their time. Without real-value rewards, gaming creates guilt and shame for many gamers. By adding a value economy into the gaming experience we can relieve people's boredom while providing them with life-changing opportunities at the same time.

- What is the target audience of the final solution?
The games market

- What is the “secret sauce” of it?
Clean and Simple User Experience, focussing on the features that players really want.

- What is the duration of the whole project?
2 months.

- Resources required to implement the grant task
We request 30,000 WAVES + introduction to some of your NFT communities so we can work with them to add in-game utility to their NFTs.

### Ecosystem Fit

Are there any other projects similar to yours? If so, how is your project different?

Our biggest competitor is Steam, which is currently the world's largest games library.

## 🔩 Development Roadmap 

This section should break out the development roadmap into a number of milestones. It helps to describe the functionality we should expect, plus how we can check that such functionality exists in the product. Whenever milestones are delivered, we refer to the roadmap to ensure that everything has been delivered as expected.

**Step #1**: Integration into WAVES

Please remember that our platform is already LIVE and usable. 
- We will integrate the most popular WAVES wallet so users can connect them to our platform.
- We will read the WAVES blockchain so we can see what NFTs users own

**Step #2**:  Collaboration with WAVES projects

- We would appreciate an introduction to some of the most poplar NFT projects on WAVES
- We will start working with them to integrate their NFTs into our games and conducting co-marketing campaigns with them

Within this application we are requesting **Step #1** funding with a total cost of 30,000 WAVES and the following KPIs to deliver:

- Supporting the most popular WAVES wallet
- Collaborating with the most popular WAVES NFT project

### Overview

- **Total Estimated Duration:** 
2 months

- **Total Costs:** Amount of Payment in Waves for the whole project. 
30,000 WAVES

## Additional Information ➕

Any additional information that you think is relevant to this application that hasn't already been included.

Possible additional information to include:

- Website: MyMetaverse.io
- Whitepaper: whitepaper.mymetaverse.io
- Play Survival Infinity Now (Minecraft Server): https://mymetaverse.io/games/survival-infinity
- Play Infinity Auto Now (GTA 5 Server): https://mymetaverse.io/games/infinity-auto

**Comment by BlackTurtle123** [comment]
1) We miss a more detailed breakdown how the 30k waves are spend
2) How will you handle big companies saying no? How will you handle minecraft recent policy update?
3) Did you identify the wavesplatform nft projects? Are they up for collaboration? What projects you target?

**Comment by BlackTurtle123** [comment]
No comments anymore so will be closed

**Comment by SimonKertonegoro** [comment]
Sorry @BlackTurtle123, I didn't see your requests for more information... I understand your decision, have a great day!
