### ISSUE TITLE
Mytracknet

### ISSUE THREAD

**Issue by Mytracknet** [Waves-Association/grants-program#9]

**Comment by KardanovIR** [comment]
Hey, Waves Association Grants & Funding working group reviewed your application and did not recommend your project to the Waves Association board.

Here are feedback and recommendations on what you can do before the working group will re-evaluate your application:

**Feedback:**

- After 4 years of development (including fundraising though ICO), there is no valuable traction
- The product is not alone on the market and it is not clear how MyTrackNet is better than competitors and what’s the “secret sauce”
- Dubious perspectives during lockdowns
- It is not clear from the application how the team will solve the so-called “Chicken-egg problem”

**Recommendations:**

- Add expenses breakdown
- Show your traction numbers after 4 years of development 
- Partner up with car/rental company to solve the so-called “Chicken-egg problem” and get first users

**Comment by Mytracknet** [comment]
Thank you for the suggestions. Please make me the favor and delete the
application of mytracknet from the github repository.
