### ISSUE TITLE
Referable NFT Proposal

### ISSUE THREAD

**Issue by mryings** [Waves-Association/grants-program#90]
- **Proposer:** Jieliang Yin
- **Contacts:** jieliany@andrew.cmu.edu
- **Github username:** mryings
- **Reward:** Estimated about $10,000 but highly negotiable and flexible 

### Team members 

1. **Jieliang Yin**: Jieliang Yin is a graduate student studying in Carnegie Mellon University proposing and leading this project. He has PhD offer from Digital Finance Co-operative Research Centre (DFCRC) and Commonwealth Scientific and Industrial Research Organisation(CSIRO) in Australia. He had several blockchain research and design experiences, and recently did industry research about MEV on Flashbots.

2. **Xiaotong Sun**: Xiaotong Sun is a PhD student at the Adam Smith Business School, University of Glasgow. Her research interests generally lie in the area of blockchain and crypto finance. She is particularly interested in Ethereum and Decentralized Finance (DeFi). Currently, she focuses on empirical evidence of centralization in blockchain.

3. **Economics Supervisor Professor Luyao (Sunshine) Zhang**: Professor Zhang is Assistant Professor of Economics and Senior Research Scientist at the Data Science Research Center at Duke Kunshan University (DKU). Her current research interests are around the application scenarios of “Blockchain +” including cryptoeconomics, Blockchain for social good, tokeneconomics, and consensus algorithms.

4. **Technical Supervisor Dr.Shiping Chen**: Dr. Shiping Chen is a senior principal research scientist in CSIRO Data61, Australia. He also holds an adjunct associate professor title with the University of Sydney. He has been working on distributed systems for over 20 years with focus on performance and security. He has published 240+ research papers and technical reports in these areas. His current research interests include: distributed systems and blockchain. He is a Fellow of Institute of Engineering Technology (FIET) and a senior member of the IEEE (SMIEEE).5. 

5. **Industry Research Supervisor Dr. Yulin Liu**: Dr.Liu holds PhD in Economics from ETH Zurich. He led the economics research team on token economics and the on-chain governance system at DFINITY Foundation from 2018 to 2020. His research interests are macroeconomics, monetary economics, financial stability, blockchain and cryptocurrency.

We welcome more people to join and contribute to our research and will give them corresponding returns!

## 🔍 Overview

Non-Fungible Token (NFT) is the digital object that represents unique and unreplicable value on blockchain network. Our project is a new standard of token system that makes NFT referable. By referring to the existing NFT, new NFT can freely improve and extend the original NFT to add new value to it. In this way the referred NFT can be more and more valuable by accepting all kinds of contributions, and new NFT can also be more valuable by directly building on the referred NFT. Our goal is to make everyone can equally contribute to valuable NFT with corresponding returns, and the value creation and exchange of NFT could be more inclusive, efficient, and decentralized.

### Ecosystem Fit

**Existing Works**

As for the token standard, ERC721 defines the standard of NFT, ERC1155 allows multiple NFTs be generated at one time, and ERC998 make NFT composable. However, they couldn’t support others rewrite and improve existing NFT to create new NFT, and connect the new NFT to the original NFT. In this way NFTs are developed and maintained mainly by a single entity like the founder or a company, while others can only make monetary contributions like buying and selling, which limits the decentralization and value of NFT.

Current NFT creators don’t have a good solution for reuse and recreation of their NFTs yet. Larva Labs restricts others to make derivatives based on their NFTs, which causes the complaints and resistance of their NFT holders. Yuga Labs gives the copyright of their NFTs to their corresponding NFT holders, but limiting to the copyright, and only NFT holders. CC0 NFT (Creative Commons 0 NFT) tries to make the use, modification and recreation of NFT totally free without permission and limitation, but it doesn’t define the economic model especially the revenue distribution scheme among different works, which limits the incentives of NFT creators opening and sharing their work.

Some NFT projects has already begun to explore the recreation of existing NFTs. Loot is such a project that its NFTs only have the characters of some equipments in the game like Linen robe, Platinum ring, and Wool shoes. It’s actually a building block that allows others to freely design new NFT games based on those characters. However, it only limits to composability, and also only the owner of the NFT.

**Impact**

As the value of NFT depends on its valuable community or network, we estimate our referable NFT will promote the value of NFTs by making their community or network more valuable.

For NFT creators, if others want to contribute to their NFT, they need to join their team first because the development and management of their NFTs are still highly internal and centralized, which is highly inefficient. Even if some NFTs try to have DAO, the effectiveness of the governance based on voting is still very limited. On the contrary, our referable NFT allows creators fully open and share their NFTs with others, and accept not just monetary, but all kinds of contributions from the community. Relying on the new value brought by them, the original NFT could have long-term development and growth in value, and such unlimited collaboration and recreation will be fully efficient and decentralized.

For NFT users, they can have equal opportunity to participant in the management and improvement of existing NFTs, and freely contribute to them in different ways besides buying and selling, but all kinds of contributions to them by directly building new NFT based on them. Different contributions can coexist without limitations to meet the needs of different users, and contributors can get corresponding returns fairly according to the predefined revenue distribution scheme. In this way, the value production and distribution of NFTs are fully open, free and equal to everyone, and the community and network of NFTs could be more incentive, expanded and valuable.

## 🔩 Development Roadmap 

**August 2022** ($2,000): Finish the technical design of our system to achieve full interconnectivity, interoperability, and composability among original and new versions directly and seamlessly. By referring to others’ version they are based on, everyone can freely connect, change, and improve others’ version to build their new version with better security and privacy.

**September 2022** ($2,000): Design the token standard that confirms, records and tracks reference relationships among different versions immutable on blockchain to protect the rights and interests of the owners opening and sharing their version to others, and allow others to improve the security and privacy of their projects.

**October 2022** ($2,000): Design the economic model and incentive mechanism to incentivize the owners to open and share their version with others and encourage others to build their new versions based on the original version to improve rather than damage the original version. Earnings within the reference system will be collected and distributed between both new and original versions fairly.

**November 2022** ($2,000): Develop the maintenance and improvement of the security and privacy features in the system to support the contributions to the security and privacy of a project.

**December 2022** ($2,000): Build and test the demo, evaluate and improve the design, write and publish the research report. Everyone in the community is welcome to participant in the research like giving any insights or undertaking any version. All valuable contributions will be counted and rewarded including the nomination of the research paper and shares of the realistic application.

After getting the grant, the whole research process will be fully open in the community and everyone in the community is welcome to join and contribute to our research. They can also make all kinds of contributions besides research like development, testing, feedback, and promotion. The given grant will be used to reward all contributors in the community to reward their valuable contributions.

### Overview

- **Total Estimated Duration:**  About 6 months
- **Total Costs:** Estimated about $10,000 but highly negotiable and flexible 

## Additional Information ➕

**Use Cases**

Our reference feature can be applied to all kinds of valuable NFT with its community or network including digital artwork, social network, and Web3 services.

**Community:**

The value of an artwork NFT depends on the community including all kinds of roles including collectors, fans, experts, artists, investors, and buyers. Our referable NFT could make the artwork NFT decentralized and incentive to everyone in the community that everyone could freely contribute to the artwork like recreation or promotion by making a new NFT and referring to the original NFT. To encourage more valuable contributions, the earnings of the new NFT from the community like purchase and investment will be distributed with all other NFTs the new NFT refers to as incentives.

**Network:**

The social profile NFTs like Cryptopunks and Bored Ape occupy the most market value among all NFTs now. They could be used as profile in the online social network to represent the identity, status, and interests of the owner recognized by other people within the network, which is why they have such a high price. Referring to such NFTs having the valuable network, new NFTs could be built more easily and successfully by accessing the users and resources within the network. They can also bring new value to the referred NFTs, making its network more valuable and sustainable. In this way, different NFTs can collaborate with mutual benefits for more valuable network by building reference relationship via our referable NFT.

**On-chain services:**

Some NFTs are valuable because of the online services behind them like game, DeFi, and Web3 DApps. As our referable NFT can represent smart contracts, it can make on-chain services more decentralized by achieving full interconnectivity, interoperability, and composability among them.

With full composability, each on-chain service could have different new versions made by different contributors out of the original version like permissionless branches or forks. With full interoperability, new versions can freely change and improve the original versions while still directly connecting to the other parts of the original version, especially accessing its internal network seamlessly. In this way there could be many versions of each online service without limitations to meet the needs of different users, and they could coexist equally to make the service better.

Any questions, critiques, and requirements, feel free to leave message here or contact jieliany@andrew.cmu.edu. Thanks a lot!

**Comment by BlackTurtle123** [comment]
Hello,
We don't see the real use-case.
Why do we want to have this?
Doesn't it defeat the purpose of a NFT when you can edit it?
We are not very convinced 

How can you defend your budget request, we would need more details, especially since it's negotiable, it seems like the money is really needed.

**Comment by mryings** [comment]
Hi we have got enough funding sponsored by others and sorry I forgot to withdraw this application. Thanks a lot!
