### ISSUE TITLE
Waves LDEX Adapter Module

### ISSUE THREAD

**Issue by jondubois** [Waves-Association/grants-program#95]
- **Proposer:** Introduce yourself (name, surname)
Jonathan Gros-Dubois
- **Contacts:** Your email or telegram handle
grosjona(at)yahoo.com.au
- **Github username:** Your Github login
[jondubois](https://github.com/jondubois)

## 👥  Team

- Are you applying to implement the grant as an individual developer or do you represent a team?

Team

- Are you a startup or an ongoing business? (in case applying as a team or startup)

An ongoing business/DAO

- What’s your team or startup name? What is a website? (in case applying as a team or startup)

LDEX https://ldex.trading/

### Team members  (in case applying as a team or startup)

- Name of team leader

No leader.

- Names of team members

Jonathan Gros-Dubois, Maarten Coppens, Rajmond Berisha, Reo Elliott, Olga Novoselova and Sachin Shinde.

### Team experience  (in case applying as a team or startup)

- Please describe your (team/startup) development experience and technological stack?

Front end (JavaScript, TypeScript, VueJS, React, CSS, Electron, ...)
Back end (Node.js, C, C++)
Databases (Postgres, MySQL, SQLite, MongoDB, RethinkDB)
Mobile (iOS, Android)
Embedded (ATMEL ATMEGA8-16PU using C and AVR Studio IDE)

- Do(es) you(r) (team/startup) have experience in using Waves technologies?

No, though we read the documentation carefully to determine suitability for this project.

- Please attach your (team/startup) portfolio (projects you’ve been involved in)

We don't have a 'portfolio' website but here are a list of projects which I and my team have been involved in:

Mathspace https://mathspace.co/ [I was involved in as an early employee/developer] - An AI-based mathematics education platform - https://mathspace.co/

SocketCluster https://socketcluster.io/ [I created and maintain the project] - An open source pub/sub server and client library for JS/Node.js with almost 6K stars on GitHub

Capitalisk https://capitalisk.com/ [Built entirely by our team members] - A lightweight (~5K lines of JavaScript/Node.js code) quantum-resistant DPoS blockchain with instant finality - Also, see wallet application built by our team (works on web, mobile and desktop, built with VueJS): https://capitalisk.com/wallet/ldpos/

Leasehold https://www.leasehold.io/ [With many contributions from our team members] - A blockchain for real estate rental industry.

- Team website

https://ldex.trading/

### Team Code Repos

- https://github.com/socketcluster/
- https://github.com/capitalisk/
- https://github.com/leasehold/

## 🔍 Overview

Please describe your solution idea by the following structure:

- Short description of the solution you suggest

The Waves LDEX Adapter module for LDEX will allow WAVES to be integrated into LDEX https://ldex.trading/trade/ - This adapter will allow any WAVES-based market to be created and listed for trading against tokens as part of the LDEX decentralized exchange.
We have successfully built adapters for other blockchains including Lisk (Lisk v3 SDK), Leasehold (based on Lisk v2 SDK) and Capitalisk (LDPoS SDK).

- How does it solve the specified problem?

The Waves LDEX adapter will allow any group of people to create a DEX market for trading tokens from potentially any custom (distinct) blockchain against the Waves blockchain. LDEX has several unique features; each market is independent and can support different degrees of decentralization (can require a different number of validators and signature thresholds), fully transparent (every trade is fully traceable as tokens are converted between different chains; it CANNOT be used as a mixer to obfuscate the origin of funds). Members of the Waves community will be able to participate as validators and earn fees from trades.

- How you will integrate this project into Waves / Neutrino.

The adapter will use Waves APIs to monitor the blockchain state and broadcast transactions. This typically involves validators running their own blockchain nodes so it should add capacity/security to the Waves network.

- Why your team is interested in creating this project.

We read though the documentation of over 70 popular blockchain projects and identified Waves as one of a tiny handful which has an API which meets the requirements of this integration (this saves a lot of work).

- What is the target audience of the final solution?

Project founders, developers, investors and community members.

- What is the “secret sauce” of it?

The secret sauce is based on 2 key ingredients; the first is that it uses multisignature wallets as a decentralized primitive for validating trades across different blockchains; these multisig wallets can have any number of members (dynamic membership is also supported). The second ingredient is the determinism - Any sequence of orders/trades placed on the DEX can only produce 1 valid history; this makes it highly reliable and also makes it fork-resistant as DEX validators rely on the majority consensus of nodes across of both underlying blockchains in order to process trades.

- What is the duration of the whole project?

The LDEX project started in 2019 and has been operating on a small scale for 2 years in the Lisk ecosystem. We only just started trying to branch out this month to try to integrate LDEX with other blockchains.
The Waves LDEX Adapter module is expected to take up to 8 weeks to implement (this is a pessimistic estimation; it could be much faster depending on implementation details of the Waves blockchain).

- Resources required to implement the grant task

Funds to cover development of the adapter. Funds to cover marketing would be a plus.

### Ecosystem Fit

Are there any other projects similar to yours? If so, how is your project different?

There are other DEXs in the industry. Compared to a DEX like Uniswap, LDEX has the advantage that it operates across multiple distinct blockchains; this allows it to keep fees low since much of the processing is offloaded to different networks which do not overlap in terms of computational resource usage. LDEX supports a decentralized order book with limit and market orders instead of AMMs which tend to be capital-inefficient (LDEX does not suffer from issues such as impermanent losses). LDEX reads all its input data from participating blockchains and all its outputs are therefore deterministic. This determinism means that even if (hypothetically), the majority of validators were taken down for a whole year (which is itself extremely difficult to do given a sufficient number of validators), once the validators are restarted, the DEX would catch up and all orders which were placed in the past would be executed exactly as they would have occurred in the past.

LDEX could provide first-class support for the Waves ecosystem to bridge it to additional ecosystems.

## 🔩 Development Roadmap

This section should break out the development roadmap into a number of milestones. It helps to describe the functionality we should expect, plus how we can check that such functionality exists in the product. Whenever milestones are delivered, we refer to the roadmap to ensure that everything has been delivered as expected.

**Step #1**: \[Example\] Analysis and planning

- Study the Waves APIs (REST/HTTP and clients) to identify all specific endpoints and parameters for integration ($3000).

**Step #2**:  \[Example\] Implement the Waves DEX Adapter

- Use https://github.com/Capitalisk/lisk-v3-dex-adapter as boilerplate; cleanup main logic to prepare for integration with Waves ($3000).
- Modify/adapt test suite (https://github.com/Capitalisk/lisk-v3-dex-adapter/blob/master/test/dex-api-tests.js) for Waves blockchain ($3000)
- Make all the tests pass ($6000)
- Implement 'ChainCrypto' plugin to allow LDEX to sign transactions on the Waves blockchain ($3000).

**Step #3**:  \[Example\] Deploy and test manually

- Once all the integration tests for the Waves adapter are passing (from previous step), manually test all main scenarios on testnet ($2000).
- Once all testnet manual tests are passing, deploy a market and test on mainnet ($2000).

Within this application we are requesting **Step #1** funding with a total cost of 650 WAVES and following KPIs to deliver:

- A script which demonstrates calls to all the endpoints which are needed to implement the Waves LDEX Adapter.
These endpoints should provide all necessary data for all the test cases mentioned in Step 2.
If, for whatever reason, it turns out to be infeasible to get the necessary data or functionality to integrate Waves APIs, a report should be produced which describes the hurdles along with recommendations for Waves team to implement the missing functionality.

### Overview

- **Total Estimated Duration:** 2 months (pessimistic estimate)
- **Total Costs:** ~5000 WAVES

## Additional Information ➕

Any additional information that you think is relevant to this application that hasn't already been included.

Possible additional information to include:

- The main stack is JavaScript/Node.js but it can integrate with any other stack through HTTP APIs or clients.
- LDEX FAQs: https://ldex.trading/docs/faqs/
- Trading UI: https://ldex.trading/trade/
- Our team is open to further collaboration with Waves beyond the scope of this grant.

**Comment by jondubois** [comment]
Here are some advantages of LDEX compared to Waves DEX:

- Orders are matched on-chain and produce a full, deterministic order history which can be used to determine the relative value of any token in the ecosystem at any point in the past (this history is generated in a decentralized way using real tokens so it's reliable).
- Does not rely on centralized nodes for order matching. The order book itself is decentralized; it can be derived directly from the blockchain state and so it cannot be misrepresented to users.
- Orders can be matched (locked in) even while the majority (or even all) DEX validator nodes are offline. The settlement of trades could happen at any time in the future as settlement is a distinct step from the order matching. The order matching is fully deterministic and decentralized; it is derived entirely from on-chain data across the two affected blockchain.
- Each DEX market is independent though some validators can participate in multiple markets (markets with reputable validators are more reliable. Also, each validator's history can be determined and ranked trustlessly).

Here are some disadvantages of LDEX compared to Waves DEX:

- All orders need to be written on-chain as transactions; this costs blockchain fees so LDEX is not suitable for high-frequency trading. It is targeted at investors, instead of traders with less frequent trades.
- UI is much more basic.
- Tokens which are sitting in the order book are held in multisig accounts instead of directly in the user's own wallets. (However, the security of these multisig wallets can be increased to the desired level by adding more validators and higher signature thresholds).

**Comment by BlackTurtle123** [comment]
Hello,
We would like to have a more in depth explanation about how the multichain trading system would be working. EG between waves chain and lisk chain
How would you do order matching on chain with a non-turing complete language like ride?
Can you provide KPIs about your current working platform, amount of uders, trades, volume,...

**Comment by jondubois** [comment]
@BlackTurtle123 To be able to integrate with LDEX, the underlying blockchain only needs to support the following key features:

- Must be a blockchain (DAGs, Hashgraphs or other more exotic architectures are not supported).
- Multisignature accounts/transactions.
- Transactions need to allow up to 64 bytes of custom data (a message) to be stored as part of the transaction (the authenticity of the message should be verifiable from the transaction signature).

Instant finality is not required. LDEX can detect and recover from forks.
It relies on APIs provided by the blockchain node in order to watch for new blocks and incoming transactions.

Smart contracts are not required (though they could be used to implement more flexible kinds of multisig accounts; so they can still be useful). Decentralization is achieved entirely via multi-signature accounts (1 multisig account on each participating blockchain for each market). Currently, it supports multisig accounts with up to 100 members. The membership of multisig accounts can optionally be updated dynamically over time if the underlying blockchain(s) support this (for example, existing multisig accounts could add new members/DEX validators though a voting mechanism).

The way it works is basically like this; users send on-chain transactions (containing DEX commands in the transaction message) to a specific multisig address on either participating blockchain and the DEX validators see these transactions arriving in the multisig wallets (which they are members of). They all have an exact matching copy of the 'decentralized order book' (which is derived entirely from the on-chain data) so they always agree about the order history. This means that they all end up producing the exact same transactions; this allows validators to share their signatures with each other; the first DEX validator to gather enough signatures to exceed the multisig threshold can submit the transaction to the blockchain; validators which act fast have a higher chance of having their own signature included on the final multisignature transaction (and this affects how much fees they will receive later).

About KPIs. We only have 2 markets currently (CLSK/LSK and LSH/CLSK) but we are currently working on adding more mainstream ones. Our trade volume has been around $1K to $1.2K USD per month across our 2 existing markets. We haven't done any marketing or received any exposure from other projects so this is 100% genuine trade volume.

**Comment by BlackTurtle123** [comment]
For now with the current market, we are not too interested.
The project/idea seems cool, but we think it's better fit to apply when you would have more markets/usage.
Therefore we will close it for now.
