### ISSUE TITLE
Be Your Own Bank

### ISSUE THREAD

**Issue by AccelerateMax** [Waves-Association/grants-program#99]
\[BEFORE YOU START\]:

1. Please use [Certificado project issue as an example of good application for a grant](https://github.com/Waves-Association/grants-program/issues/14)
2. Waves Assocation Members can ask questions about your project and they will leave questions in this issue, so please keep an eye on the issue and reply to comments and questions.

---

- **Proposer:** Introduce yourself (name, surname) 
Max Yare
- **Contacts:** Your email or telegram handle
- max.y@accelerate-bank.com
- **Github username:** Your Github login
- n/a

## 👥  Team 

- Are you applying to implement the grant as an individual developer or do you represent a team? 
Our team includes 4 developers
- Are you a startup or an ongoing business? (in case applying as a team or startup) 
it is a startup business registered in Australia
- What’s your team or startup name? What is a website? (in case applying as a team or startup)
https://accelerate-bank.com/

### Team members  (in case applying as a team or startup)

- Name of team leader
Max Yare
- Names of team members
explained in the doc: https://tinyurl.com/2lauweel

### Team experience  (in case applying as a team or startup)

- Please describe your (team/startup) development experience and technological stack?
working in web3 development from 2017
- Do(es) you(r) (team/startup) have experience in using Waves technologies?
some previous exposure
- Please attach your (team/startup) portfolio (projects you’ve been involved in)
https://bc-nft.vercel.app/
https://cosmicpaws.io/
https://www.powned.co/

### Team Code Repos

https://github.com/V-perseus
https://github.com/aryabhat1
https://github.com/mojowlekaz

## 🔍 Overview

Please describe your solution idea by the following structure:

- Short description of the solution you suggest
The mobile app to issue personal e-money as quickly as a Gmail account with zero-added fees. The solution to deal with an inflationary economy. This is a DAO project - Community owned and operated.
- How does it solve the specified problem?
The users and local businesses are able to control the value of their e-money with their own ideas in our app. Buy, sell, exchange and grow the value of their own coins. Reward their supporters and business clients.
- How you will integrate this project into Waves / Neutrino.
Waves to be used as a primary blockchain to register new user wallets and issue personal tokens.
- Why your team is interested in creating this project.
As it brings an idea of personal money into life. It creates a set of technological challenges to allow my grandma to use blockchain technology.
- What is the target audience of the final solution?
mass adoption with the initial focus on social influencers and local business in real life
- What is the “secret sauce” of it?
new idea  - The macro economics on a micro level.
- What is the duration of the whole project?
development stage would take 15 weeks
- Resources required to implement the grant task
financing, time

### Ecosystem Fit

Are there any other projects similar to yours? If so, how is your project different?
some of the projects have a partial overlap
https://www.pinksale.finance/ (token creator, tokens have an investment purpose - not a mass adoption or real life usage - still pretty technical for users)
https://bonuz.market/ (project is at the development stage - token creator for celebrities and brands only - not a mass adoption. Track followers contribution and issue NFTs as a reward)
https://www.peoplez.io/ (at the development stage - token creator for celebrities - no mass adoption)
https://www.personaltokens.io/ (basic token creation tool - 500 users only - knowledge required - no utility tools provided)

## 🔩 Development Roadmap 

This section should break out the development roadmap into a number of milestones. It helps to describe the functionality we should expect, plus how we can check that such functionality exists in the product. Whenever milestones are delivered, we refer to the roadmap to ensure that everything has been delivered as expected.

please refer to the RoadMap: https://tinyurl.com/2luthrku
MilesStones and Budget: https://tinyurl.com/2mf4tkkw

### Overview

- **Total Estimated Duration:** Duration of the whole project
An overall development phase takes 15 weeks
- **Total Costs:** Amount of Payment in Waves for the whole project. The total amount of funding needs to not more than 100k Waves.
Development cost is $50k

## Additional Information ➕

We have created a full prototype of the mobile app.
Project overview on one page: https://tinyurl.com/y5pooyhu

**Comment by BlackTurtle123** [comment]
Hello,
Please reread nr1 of your own application, and follow the steps.
We don't get your application, you might need to explain it better.
How would this e-money work?

**Comment by AccelerateMax** [comment]
Hi Team, thanks for your response. I have added a few more details below. Happy to show you our Figma prorotype to understand the functionality better.

here is a quick project overview: https://tinyurl.com/y5pooyhu

New users deploy their tokens in a few clicks. These tokens are listed on DEX with some liquidity provided by the issuer. That would drive the numbers of the Waves blockchain users up and increase TVL respectively. 

Users could trade their coins from the social pages across the web. Accept crypto payments in their local businesses. Offer a crypto-based customer loyalty program. Exchange your own coins with the friends. Reward your supporters. Grow the value of your coins with your ideas. 

 
 
 Target audience:
 • the influencers use e-money to sell content and receive support from the followers online. 
 • the local businesses use e-money as an advanced customer loyalty program in real life. The customers receive entitlements based on their position on the reward ladder.
 
 Viral onboarding mechanism:
 • get a digital wallet by sending a text message on mobile
 • once Tom has coins in his digital wallet > Tom sends coins to John’s mobile > thus creating a new wallet for John
 
 User-friendly features:
 • Sell your coins with the direct link from Instagram, Facebook or TikTok page
 • Send coins to the mobile number, email or your Facebook friend
 • Dispute transaction if coins sent to a wrong address
 • Choose the rewards for the holders of your business coins
 • Shake&Pay in local store
 • Cash out with your personal card
 • No internet required to send out or receive coins. Cash out by sending a text.


Just let me know if you need any further information.

Kind regards,
Max

**Comment by BlackTurtle123** [comment]
We dont believe in this idea.
We will have to deny this.
You can already create on assets on wx and sell them.
